### ISSUE TITLE
Como realizar a atualização do repositório que foi "forkado"?

### ISSUE THREAD

**Issue by amsdbarreto** [iurygdeoliveira/novos_caminhos#102]
Como realizar a atualização do repositório que foi "forkado"?

É outro problema, quando clono utilizando o SSH: 

Warning: Permanently added 'github.com,140.82.114.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).

**Comment by iurygdeoliveira** [comment]
@amsdbarreto 


Depois que você forka um projeto no Github, você faz as alterações necessárias e envia um Pull Request para o repositório original.

Se você precisa fazer mais alguma alteração no mesmo repositório no futuro, mas já tem outras colaborações no repositório original, como você procede para manter seu repositório atualizado? Copia as alterações manualmente para o seu repositório? Apaga e forka novamente? Chora?

O Git é uma ferramenta excepcional e, quando você passa a conhecê-lo mais a fundo, vai ver que não vai precisar fazer mais nada manualmente quando ele é usado no seu projeto. Existe uma forma muito prática de sincronizar os dois repositórios, e vou mostrá-la agora mesmo! 

O seu repositório forkado normalmente é adicionado como origin quando você faz o clone. Para sincronizar com o repositório principal, adicione esse repositório com outro nome (no caso do exemplo, upstream), com o comando abaixo:

git remote add upstream [ENDEREÇO DO REPOSITÓRIO PRINCIPAL]

Substituindo [ENDEREÇO DO REPOSITÓRIO PRINCIPAL] pelo endereço do repositório (não diga :P)

Depois, para sincronizar os repositórios, execute o comando:

git fetch upstream

Finalmente, só dar merge na branch master:

git merge upstream/master

And done! ;)

**Comment by amsdbarreto** [comment]
Professor,

Como sou inquieto, eu pesquisei hj e descobri como fazer. A mesma forma que
o Sr. fez. rsrsrs.

Grato pela atenção. Da próxima vez irei pesquisar antes de encher o Sr. com
perguntas tolas.

Grato.

Iury Gomes de Oliveira <notifications@github.com> escreveu no dia sábado,
29/08/2020 à(s) 19:42:

**Comment by iurygdeoliveira** [comment]
@amsdbarreto 

Não pense assim, isso não é pergunta tola, na verdade é a dúvida de muitos outros alunos. 

Que bom que funcionou.

@UMJS dá uma olhada aqui.

**Comment by amsdbarreto** [comment]
Grato professor.

Uma observação, eu utilizei estes comandos para sincronizar os
repositórios. ( o meu " upstream " , chamei de :novos_caminhos ) , aí criei
um arquivo bat chamado atualiza.bat com os comandos abaixo. Assim não
necessito digitar tudo novamente quando quiser sincronizar.

git fetch novos_caminhos
git rebase novos_caminhos/master
git push origin master
git merge novos_caminhos /master

Iury Gomes de Oliveira <notifications@github.com> escreveu no dia sábado,
29/08/2020 à(s) 22:58:
