### ISSUE TITLE
Qual a diferença do GIT PULL do GIT CLONE?!

### ISSUE THREAD

**Issue by eunayaraoliveira** [iurygdeoliveira/novos_caminhos#103]
Qual a diferença do GIT PULL do GIT CLONE?! Como devo saber qual dos dois comandos usar na hora de pegar os projetos no GitHub para o VSCode?!

**Comment by iurygdeoliveira** [comment]
git pull = realiza o download e atualiza o repositório local já existente a partir de um repositório remoto definido com o comando git remote anteriormente

git clone = cria um repositório local que ainda não existe a partir de um repositório remoto;
