### ISSUE TITLE
duvida de atualização entre repositório local e repositório remoto

### ISSUE THREAD

**Issue by aknazevedo2** [iurygdeoliveira/novos_caminhos#107]
professor mesmo depois de git push a pasta criada para contribuição que está no meu repositório local não aprece no repositório remoto.

[https://drive.google.com/file/d/1JRpOTXZoJdguNDI12KbMxfPxLP3BRtlg/view?usp=sharing](url)
[https://drive.google.com/file/d/1Ljj3yGMgBQxNXO5-raVYPDsXNL_H2-Ri/view?usp=sharing](url)

**Comment by iurygdeoliveira** [comment]
Ana, não consigo visualizar a imagem pelo link.

Se for uma imagem, pode adicionar dentro da issue mesmo aqui, copiando e colando, tbm funciona

**Comment by iurygdeoliveira** [comment]
Dá um comando git remote no terminal, dentro da pasta do repositorio, qual o link que aparece ?

**Comment by LuizAlves99** [comment]
Estou co mesmo problema
Quando uso "git remote" aparece ORIGIN

O que devo fazer?

**Comment by jalexandrersilva** [comment]
Professor, depois do comando git remote github https://github.com/iurygdeoliveira/novos_caminhos https://github.com/jalexandrersilva/novos_caminhos

qual os próximos comandos pra finalizar?
