### ISSUE TITLE
Como usar o gitignore no Windows ?  Como instalar o cmder no vscode no Windows ? 

### ISSUE THREAD

**Issue by JohnnyfWSilva** [iurygdeoliveira/novos_caminhos#113]
1 - Como usar o gitignore no windows?

2 - Segui o passo a passo de instalação do cmder, mas ele não aparece no terminal mesmo depois de reiniciar a máquina.

3 - Eu fiz o git clone no repositório forkado e enviei minhas contribuições. Minha dúvida é: no momento do git push foi tudo enviado para o repositório forkado sem que eu especificasse (como foi feito na prática do repositório com nome de usuário), por que isso aconteceu?

**Comment by iurygdeoliveira** [comment]
> 1 - Como usar o gitignore no windows?
> 
> 2 - Segui o passo a passo de instalação do cmder, mas ele não aparece no terminal mesmo depois de reiniciar a máquina.
> 
> 3 - Eu fiz o git clone no repositório forkado e enviei minhas contribuições. Minha dúvida é: no momento do git push foi tudo enviado para o repositório forkado sem que eu especificasse (como foi feito na prática do repositório com nome de usuário), por que isso aconteceu?

1 -  Da mesmo forma que no linux, vc adiciona na raiz do projeto um arquivo começando com ponto dessa forma .gitignore

2 - Voce fez a configuração recomenda no pagina oficial do vscode esta aqui
![image](https://user-images.githubusercontent.com/30157522/91585241-2bbe2000-e92a-11ea-98c3-856d5106d78c.png)

Link: https://code.visualstudio.com/docs/editor/integrated-terminal

3 - A resposta é sim,  quando vc faz o git clone, ele automaticamente no ato da criação do repositório local em seu computador, ele já faz o link com o repositorio forkado, não necessitando indentificar a branch
