### ISSUE TITLE
Atualizar repositório depois de formatar o computador ?

### ISSUE THREAD

**Issue by suelmartins15** [iurygdeoliveira/novos_caminhos#116]
Tive que formatar meu notebook e não está atualizado conforme o do curso, preciso refazer processo de excluir repositório e clonar novamente e fazer Fork? ou como faço para atualizar arquivos no meu repositório?

**Comment by iurygdeoliveira** [comment]
@suelmartins15 

Se já estiver forkado, e você não tiver feito nenhum git clone ainda:
git clone <url do repositorio>

Se já tiver feito um git clone antes, acessar o repositorio local em seu computado e dar um git pull
