### ISSUE TITLE
DUVIDA GIT

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#118]
PROFESSOR GOSTARIA DE SABER SE EU DESISTA LAR O MEU GIT DA MINHA MAQUINA,  DEPOIS INSTALAR NOVAMENTE DE DENTRO DO REPOSITÓRIO VS CODE, EU CORRO O RISCO DE PERDER O QUE JÁ [DUVIDA]() FIZ ATE O MOMENTO?

**Comment by iurygdeoliveira** [comment]
@josepereirakls 

Se não deletar a pasta .git de dentro do repositorio, não vai dar problema.

Pode desinstalar e instalar o git quantas vezes quiser
