### ISSUE TITLE
DUVIDA SOBRE O GIT, QUAL E A MELHOR FORMA DE INSTALAÇÃO, FORMA PADRAO OU DENTRO DO VS CODE

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#119]
![IMG_20200828_151352](https://user-images.githubusercontent.com/70108902/91602923-78155a00-e942-11ea-8f34-e86b2d39aea5.jpg)

**Comment by iurygdeoliveira** [comment]
@josepereirakls 

Para fazer a instalação, eu recomendaria a forma padrão mesmo, baixando o programa é instalando no computador
