### ISSUE TITLE
SOU INCIANTE, VOU CONSEGUIR FAZER O CURSO ?

### ISSUE THREAD

**Issue by luisdalmeida** [iurygdeoliveira/novos_caminhos#122]
gostaria de saber qual o nivel de conhecimento de programação o aluno deve ter para esse curso?, o meu nivel esta abaixo do basico, sou esforçado,determinado e curioso. estou acompanhando mas tenho muitas duvidas; vou começar a postar as minhas duvidas ok.

**Comment by iurygdeoliveira** [comment]
@luisdalmeida arrocha o buriti, poste suas dúvidas mesmo, estamos aqui para isso ! Vc tem o que precisa para o curso !
