### ISSUE TITLE
Erro na extensão settings sync

### ISSUE THREAD

**Issue by luisdalmeida** [iurygdeoliveira/novos_caminhos#125]
toda vez que eu abro o vscode aparece isso.
¨sync: unable to read synclocalsetting.json make its valid json¨ 
não sei o que fazer.

**Comment by iurygdeoliveira** [comment]
@luisdalmeida 

Esse erro é na extensão settings sync, me parece que existe algum erro no arquivo synclocalsetting.json.

Faça o seguinte, instale e desinstale a a extensão settings sync
