### ISSUE TITLE
Programa a ser utilizado

### ISSUE THREAD

**Issue by ingridsantoli** [iurygdeoliveira/novos_caminhos#132]
Olá, professor. Gostaria de saber se posso usar somente o programa CMDER para executar os comandos ou necessito fazer isso no VSC também? Pois, como uso windows, consegui acompanhar com uma facilidade muito maior no CMDER.
Obrigada.

**Comment by iurygdeoliveira** [comment]
A integração entre cmder e vcscode é apenas uma facilidade a mais. Contudo, você pode utilizar os dois separados sem problema.
