### ISSUE TITLE
Iniciante em Programação WEB

### ISSUE THREAD

**Issue by Lana-Monteiro** [iurygdeoliveira/novos_caminhos#133]
**Me perdi um pouco e confundi com as aulas no linux(já que uso windows), mas estou conseguindo me achar novamente, tive que refazer tudo do inicio pra ver no que errei, mas quero somente dizer como me sinto em relação a este curso...
Dá uma dor de cabeça viu? kkk
Mas é divertido, depois de conseguir fazer tudo, o sentimento de ter conseguido sobressaí todas as dores de cabeça, chega a ser bastante prazeroso!** @iurygdeoliveira

**Comment by iurygdeoliveira** [comment]
@Lana-Monteiro , que legal ! Muito bom ! #BoraEstudar !

Tbm me sinto assim, quando consigo resolver os problemas
