### ISSUE TITLE
E possível separar a programa do Linux da programação do Windows

### ISSUE THREAD

**Issue by Lana-Monteiro** [iurygdeoliveira/novos_caminhos#134]
Professor sei que pode ser bem trabalhoso, mas não tinha como fazer como vc fez em outras atividades separado a programação no windows da programação linux?

**Comment by iurygdeoliveira** [comment]
@Lana-Monteiro 

Com relação a programação web, o desenvolvimento do código em si, nos dois sistemas não tem tanta diferença.
Nessa disciplina estamos estudando as ferramentas de infra estrutura, por isso, as aulas são mais pegadas no linux.

Mas veja vem, estamos estudando focando na perspectiva do mercado. Ou seja, sem linux, e somente com windows, você estará fora do mercado.

Aproveita a oportunidade para conhecer um pouco mais do linux. E estarei mostrando as diferenças nos dois sistemas sempre que possível.
