### ISSUE TITLE
Qual a diferença entre Fork vs Clone no github ?

### ISSUE THREAD

**Issue by lgvnunes** [iurygdeoliveira/novos_caminhos#136]
Boas. Nas aulas o professor falou em "_forkar_" o repositório "Novos Caminhos"; eu poderia clonar? Qual é, na prática, a diferença entre as duas "técnicas" Obrigado.

**Comment by iurygdeoliveira** [comment]
@lgvnunes 

Forkar e clonar para o contexto do github, são a mesma coisa.

Quando vc forka um repositório, você está realizando um clone deste repositório, para uma cópia idêntica dentro da sua conta no github.
