### ISSUE TITLE
VSCode setup

### ISSUE THREAD

**Issue by Aiam32** [iurygdeoliveira/novos_caminhos#139]
great extensions for Visual Studio Code:
🤩👨🏻‍💻
https://gist.github.com/guilhermerodz/7c64858a74829a6d9713963f0f901190

![Captura de Tela (39)](https://user-images.githubusercontent.com/69831447/91629600-b6416680-e9a0-11ea-9c33-b944f5382228.png)

**Comment by iurygdeoliveira** [comment]
@Aiam32  Legal ! Parábens !!
