### ISSUE TITLE
Pq estamos utilizando tantos terminais diferentes ?

### ISSUE THREAD

**Issue by Andre101010** [iurygdeoliveira/novos_caminhos#140]
Professor, porque estamos utilizando 3 terminais diferente? O Bash, Cmder e o Powershell.

**Comment by iurygdeoliveira** [comment]
@Andre101010 

Eu só estou utilizando um terminal, o cmder no windows, ou então o bash no linux.

**Comment by jalexandrersilva** [comment]
Como deixar os três editores disponíveis no VScode?

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva bom dia

O vscode permite que você escolha qual terminal utilizar.

1: CTRL + ALT + P
