### ISSUE TITLE
Windows x Linux

### ISSUE THREAD

**Issue by wesleyssantos1979** [iurygdeoliveira/novos_caminhos#141]
Boa tarde, estou revendo todas as aulas, instalei uma maquina virtual no meu PC com o virtualbox pra rodar o linux, estou acompanhando as aulas e fazendo nos 2 sistemas, gostaria de saber se é possível quando for ter as linhas de comando no linux disponibilizar. E estou na dúvida pois ainda não foquei como ver as extensões do vscode, ex gifgraph como colocou ele la encima apos a instalação. Obrigado.

**Comment by iurygdeoliveira** [comment]
@wesleyssantos1979 

No repositório novos caminhos os tutoriais já estão disponibilizados.

O git graph no vscode, é possível utilizar apertando  CTRL + SHIFT + P

E digitando graph na barra de pesquisa.

Ou então você pode configurar um comando especifico para ele no vscode.
