### ISSUE TITLE
Criar projeto novos caminhos no github do aluno e unir ao projeto novos caminhos do professor

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#142]
Professor,

ainda não consegui saber exatamente como se devo criar o repositório novos caminhos ou criar o projeto novos caminhos.

Depois dessa etapa, como unir o meu repositório ao repositório do professor.

Obrigado. Verei a gravação depois da live, porque as 20 horas estarei na hemodiálise e farei isso amanhã pela manhã.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva tranquilo !
