### ISSUE TITLE
Professor, depois do comando git remote github https://github.com/iurygdeoliveira/novos_caminhos https://github.com/jalexandrersilva/novos_caminhos

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#145]
Professor, depois do comando git remote github https://github.com/iurygdeoliveira/novos_caminhos https://github.com/jalexandrersilva/novos_caminhos

qual os próximos comandos pra finalizar?

_Originally posted by @jalexandrersilva in https://github.com/iurygdeoliveira/novos_caminhos/issues/107#issuecomment-683326017_

**Comment by iurygdeoliveira** [comment]
Ver issue #151

**Comment by jalexandrersilva** [comment]
Ok professor
