### ISSUE TITLE
Integrando o Cmder ao VS Code no Windows 10

### ISSUE THREAD

**Issue by GabrielaBatistaLeao** [iurygdeoliveira/novos_caminhos#152]
Boa noite, pessoal,

Estava com dificuldade para integrar o Cmder ao VS Code e consegui, depois da live do professor Iury. Seguem os passos:

1) Vá ao diretório onde você instalou o Cmder e crie um arquivo chamado vscode.bat. Eu instalei o Cmder no diretório C:\cmder, então criei o vscode.bat neste diretório. Se você instalou em outro diretório, é lá que você criará o vscode.bat.

2) Clique com o botão direito do mouse sobre o vscode.bat e clique em Editar.
3) Copie as linhas abaixo, cole no arquivo vscode.bat, salve o arquivo e feche-o:

`@echo off`
`SET CMDER_ROOT=C:\cmder`
`"%CMDER_ROOT%\vendor\init.bat"`

**Observação: onde está escrito C:\cmder, substitua pelo diretório onde você instalou o Cmder.** 

4) Abra seu VS Code. Digit Ctrl + Shift + P e abra o arquivo Preferences: Open Settings (JSON).
5) Coloque as linhas abaixo no arquivo JSON que você acabou de abrir:

`"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",`
  `"terminal.integrated.shellArgs.windows": ["/K", "C:\\cmder\\vscode.bat"],`

**Observação 1: o cmd.exe na minha máquina está instalado em C:\\Windows\\System32\\cmd.exe. Se o cmd.exe na sua máquina estiver em outro diretório, faça a substituição adequada.**

**Observação 2: se você não instalou o Cmder no diretório C:\cmder, troque C:\\cmder pelo seu diretório de instalação.**

6) Salve as alterações do arquivo. Feche o VS Code. Abra o VS Code novamente.

O Cmder já deve estar integrado ao seu VS Code. :-)

**Comment by k-js** [comment]
Estou com dificuldades em executar esses comandos . Não consigo executar o comando 2
