### ISSUE TITLE
@aknazevedo2 se compreendi bem.

### ISSUE THREAD

**Issue by aknazevedo2** [iurygdeoliveira/novos_caminhos#154]
@aknazevedo2 se compreendi bem.

O repositório remoto, está criado, o repositório local também está criado. Agora quando você fazer, alguma alteração
no repositorio local, e fizer 

git add .
git commit -m "algum comentário"
git push

O repositorio remoto na sua conta do github, deve atualizar;

_Originally posted by @iurygdeoliveira in https://github.com/iurygdeoliveira/novos_caminhos/issues/149#issuecomment-683411639_

**Comment by aknazevedo2** [comment]
professor refiz novamente e agora segue com este erro
![image](https://user-images.githubusercontent.com/70173625/91660618-71572600-eaad-11ea-8533-91809d97c945.png)

**Comment by iurygdeoliveira** [comment]
Ana da uma olhadinha na issue #93 

Você agora está tentando enviar uma contribuição direto para o meu repositorio pessoal, você não tem autorização para fazer essa contribuição direta assim. Você deve refazer o git remote do seu repisitório, colocando a url do seu projeto forkado, e depois dar um comando git push, e depois através de um pull request, enviar para o meu repositorio pessoal.

**Comment by aknazevedo2** [comment]
será que agora eu consegui? Pelo print da foto me parece que sim, só que ficou como patch-1, não entendi?
![image](https://user-images.githubusercontent.com/70173625/91666547-053be880-ead4-11ea-90c6-3762d740aa3c.png)

**Comment by iurygdeoliveira** [comment]
É isso ai @aknazevedo2 ! Deu certo agora !
