### ISSUE TITLE
Aplicando o CDMER no Terminal do VSCODE em Windows7

### ISSUE THREAD

**Issue by LuizAlves99** [iurygdeoliveira/novos_caminhos#156]
Após a instalação do CDME na sua máquina (Como visto no curso)

- [ ] Vá até as propriedades do sistema usando o caminho:

    * **"Painel de Controle\Sistema e Segurança\Sistema"** - IMAGEM1
    * Clique em: "Configurações avançadas do Sistema" - IMAGEM2
    * Na janela que aparece, clique em: "Variáveis de Ambiente" - IMAGEM2
    * Clique em "Path" e clique em "Editar" - IMAGEM3
        **Não altere a linha do caminho**
    * Acrescente no final um ";" e digite o caminho do CDME (C:\cmder\cdmer.exe) - IMAGEM4
    * Clique em "OK" nas janelas para salvar a configuração.

- [ ] Reinicie seu computador para ativar as mudanças
Abra o VSCODE e abra um terminal (ctrl+Shift+")
    Caso não apareça "CMD" use os passos a seguir:
    * ctrl+Shift+P 
    * Select Default Shell
    * Selecione o CMD do Windows
    * Reinicie o VSCODE

Pronto a janela do Terminal agora deverá aparecer o CMD (Já modificado para CDMER)

IMAGEM1
![TELA 1](https://user-images.githubusercontent.com/69818210/91665004-192e1d00-eac9-11ea-9342-5ffc9668269b.png)

IMAGEM2
![TELA 2](https://user-images.githubusercontent.com/69818210/91665109-a2ddea80-eac9-11ea-9987-f321ee6f35f9.png)

IMAGEM3
![TELA 3](https://user-images.githubusercontent.com/69818210/91665114-aa04f880-eac9-11ea-93ab-b9c2a4c22c63.png)

IMAGEM4
![TELA 4](https://user-images.githubusercontent.com/69818210/91665119-b25d3380-eac9-11ea-8439-f25c5400d3e9.png)

**Comment by iurygdeoliveira** [comment]
@LuizAlves99 

Muito bom ! Espero que ajude vários alunos
