### ISSUE TITLE
Comandos no cmder não são reconhecidos no VSCODE, o que devo fazer ?

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#157]
fiz todo o processo de integração do cmder no vs code, porem não estar atendendo os comandos, como devo proceder?
![Captura de Tela (1)](https://user-images.githubusercontent.com/70108902/91665319-159b9580-eacb-11ea-80cb-938b6d1d0f72.png)

**Comment by iurygdeoliveira** [comment]
@josepereirakls 
Cuma ?!? Algo de errado não esta certo !

Manda um print do settings.json, deixa eu dar uma olhada ?
Utiliza qual windows ? 10 ou 8 ?

**Comment by josepereirakls** [comment]
Professor tirei a configuração do cmder do setting json, deixei apenas o shel, popis nao estva atendendo os comandos.
No explorar editor abertos do meu vs code tem muita coisa, isso ´certo?
![Captura de Tela (4)](https://user-images.githubusercontent.com/70108902/91729244-a1202f80-eb7a-11ea-9a46-f8a35463b487.png)

**Comment by iurygdeoliveira** [comment]
@josepereirakls está faltando um configuração no seu settings.json

Dá uma olhadinha na issue #113
