### ISSUE TITLE
Possível solução do problema na atualização do repositório (31:59) na LIVE de 29/08/2020

### ISSUE THREAD

**Issue by theteustav** [iurygdeoliveira/novos_caminhos#159]
Professor @iurygdeoliveira, eu tenho uma teoria sobre o erro que estava acontecendo, durante a live, na hora de subir as novas modificações locais para o repositório forkado no GitHub, onde o git dizia que o repositório local já estava atualizado ao GitHub:

No seu computador, dentro da pasta HTDOCS, percebo que existe as seguintes pastas:
...\htdocs\novos_caminhos
...\htdocs\novos_caminhos_forkado
...\htdocs\repositorio_forkado

O senhor criou a nova pasta "...\htdocs\novos_caminhos_forkado" e clonou o repositório original para dentro dela. Entretanto, os arquivos mostrados na lateral esquerda da interface do VS Code ainda é da pasta anterior.

A minha teoria é que, dentro do VS Code, quando o senhor faz alguma alteração no repositório local, na verdade, está fazendo ainda no repositório localizado na pasta "...\htdocs\novos_caminhos" que é igual ao forkado do GitHub, por isso a mensagem " Your branch is ahead of 'origin/master' ".

Nesse caso, na minha humilde opinião, deveria mudar o caminho "...\htdocs\novos_caminhos" da pasta (Folder) do VS Code para a pasta "...\htdocs\novos_caminhos_forkado", que é onde o clone do original está localizado. E assim, fazer as modificações e o git reconhecerá as diferenças do local com o repositório forkado no GitHub. 

Se eu estiver errado, me corrija.

**Comment by iurygdeoliveira** [comment]
@theteustav sim,

Era isso mesmo, eu acabei trocando as pastas. Eu fiz um vídeo novo, mostrando como realizar o procedimento.

Valeu pela contribuição
