### ISSUE TITLE
Comando git pull não funciona, o que fazer ?

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#161]
Não consigo dar um git pull

Se eu apagar a pasta forkada e criar tudo novamente vai funcionar, mas gostaria de saber porque. Alguém pode ajudar?

**Comment by josepereirakls** [comment]
Faz esse comando primeiro
git status

depois esse
git pull origin master -git push origin master


Depois faz esse
-allow-unrelated-histories

**Comment by jalexandrersilva** [comment]
Deu esse erro



Em dom, 30 de ago de 2020 17:16, JOSE PEREIRA <notifications@github.com>
escreveu:

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva 

Tudo bem, vamos devagar, para eu te ajudar, necessito entender algumas coisas antes.

1) o que aparece quando você digita o comando **git status** no seu repositório ?
2) o que aparece quando você digita o comando **git remote -v** no seu repositório ?

**Comment by jalexandrersilva** [comment]
Aí vão os prints![20200831_082008.jpg](https://user-images.githubusercontent.com/69798042/91714958-2b5c9980-eb63-11ea-9ec5-181dda894640.jpg)


![20200830_182109.jpg](https://user-images.githubusercontent.com/69798042/91715011-43341d80-eb63-11ea-8781-8ab1df3065c7.jpg)

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva ainda o git status deu para compreender

E o git remote -v ?

**Comment by jalexandrersilva** [comment]
![atv_prog_web](https://user-images.githubusercontent.com/69798042/91763669-4dc6d500-ebac-11ea-81b4-5976022851d3.png)
Prof, ai está.
Eu acredito que já esteja tudo normal, porque o meu repositorio no github está atualizado.
E parece que a atualização para o seu repositorio o senhor tem que autorizar o pull request

**Comment by iurygdeoliveira** [comment]
É isso mesmo @jalexandrersilva ! Blz então, vou marcar como resolvido.
