### ISSUE TITLE
Remover repositórios forcados do meu Github

### ISSUE THREAD

**Issue by Daslan-Mateus** [iurygdeoliveira/novos_caminhos#163]
Olá professor, fiz um fork de um repositório qualquer e agora desejo remove-lo, como faço?

**Comment by mgckaled** [comment]
@Daslan-Mateus  Veja o procedimento de remoção de repositório na documentação oficial do GitHub no [neste link](https://docs.github.com/pt/github/administering-a-repository/deleting-a-repository).

**Comment by iurygdeoliveira** [comment]
@mgckaled 

Bom dia, é isso mesmo, é como o aluno @mgckaled respondeu. E ai resolveu ? Nos dê um feedback ..
