### ISSUE TITLE
Problemas de instalação no XAMPP  

### ISSUE THREAD

**Issue by lara1000106** [iurygdeoliveira/novos_caminhos#164]
......Nao consigo instalar o xampp nesta maquina .... fala que o controle de conta de uduario esta ativa !!!! UAC impede desta forma de continuar com o wizard QUal pasta devo direcionar a instalação ou sugerir outro programa compativel que voçes acham ????? whatts 11979937803 daniel lara  ......

**Comment by mgckaled** [comment]
@lara1000106 Talvez eu consiga ajuda... Tem alguns artigos que tratam do mesmo problema que você está tendo. 

**[Link 1](https://php.docow.com/como-trabalhar-no-uac-ao-instalar-o-xampp.html)**.
**[Link 2](https://cursos.alura.com.br/forum/topico-xampp-windows-10-17601)**.

Tente instalar o *xampp* como administrador e na pasta `C:` (C:\XAMPP)

**Comment by iurygdeoliveira** [comment]
Olá @lara1000106 

Com a dica do @mgckaled , resolveu o problema ?  Nos dê um feedback ..
