### ISSUE TITLE
sou josildo mendes aluno

### ISSUE THREAD

**Issue by nego1366** [iurygdeoliveira/novos_caminhos#165]
boa tarde entrei agora no curso alguém poderia me ajudar?

**Comment by iurygdeoliveira** [comment]
@nego1366 

Do que precisa ?

**Comment by nego1366** [comment]
E que estou com muitas duvidas sobre o curso isso e novo pra mim o que vc
me diz. Sera que vc poderia me disponibilizar o intalador do windows 10?

Em seg, 31 de ago de 2020 08:05, Iury Gomes de Oliveira <
notifications@github.com> escreveu:
