### ISSUE TITLE
remote: Permission to iurygdeoliveira/novos_caminhos.git denied to jalexandrersilva.

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#169]
Olá pessoal,

eu refiz todos os comandos...
está tudo correto.

mas ao dar o git push dá essa mensagem de erro.
O que devo fazer?
![atv_prog_web](https://user-images.githubusercontent.com/69798042/91727322-eabb4b00-eb77-11ea-89f5-bb37794632fa.png)

**Comment by mgckaled** [comment]
@jalexandrersilva  Pela imagem você está tentando dar o push direto no repositório do professor....

Veja instruções na issue #93

**Comment by jalexandrersilva** [comment]
Continua dando o mesmo erro
já atualizei o usuario e o email
![atv_prog_web](https://user-images.githubusercontent.com/69798042/91737505-8d2dfb00-eb85-11ea-9368-b876196e031c.png)

**Comment by jalexandrersilva** [comment]
Continua dando problema.... o acesso está negado no repositório do prof. iury. Fico aguardando orientações

**Comment by mgckaled** [comment]
@jalexandrersilva  experimente fazer o fork primeiro, antes do clone . Veja neste [link] (https://github.com/UNIVALI-LITE/Portugol-Studio/wiki/Fazendo-um-Fork-do-reposit%C3%B3rio) os passos. Daí Daí siga as instruções do @theteustav .

**Comment by jalexandrersilva** [comment]
O fork já mostra que está ativo no github

Consegui atualizar o meu reposit remoto, mas náo consigo atualizar o reposit do professor.
Tentei dar um pull request com um titulo e uma mensagem. Mas não sei o que acontece a partir disso. Se é o professor que tem que autorizar. Aguardo orientações

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva após você dar um pull request, eu tenho que autorizar sua contribuição no projeto.

**Comment by jalexandrersilva** [comment]
Para finalizar, espero que as respostas dessa issue possam ajudar os colegas a conseguir raciocinar claramente sobre os conceitos de branch
Sempre se guiar pela figura dentro da pasta conceitos de branch (git tela 1)
Comandos que ajudou-me a entender

git status - informa se existem modificações no repositório do PC do aluno para o repositório da conta github do aluno
git remote - informa os nomes das branchs dispon[iveis
git remote rename nome nomeNovo  -  como o professor mostrou nos videos, ela renomeia os controles
git remore -v   - mostra as localizações dos controle criados
git remote add  name url   -  cria os controles necessários
git remote remove   -   fiz esse comando quando o git remote -v mostrou que os controles apontavam para os locais errados

E finalmente o pull request    -   por favor, me corrigam qualquer coisa que eu tenha errado, mas o pull request  é criado quando é dado o comando git push

Abraços colegas, espero retorno de voces.

**Comment by jalexandrersilva** [comment]
Como dar o comando pull request por VScode? São os comandos merge?

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva não se dá pull request pelo vscode, apenas via github mesmo
