### ISSUE TITLE
atualizar repositório forkado do github com o repositório master

### ISSUE THREAD

**Issue by aknazevedo2** [iurygdeoliveira/novos_caminhos#172]
percebi que meu repositório forkado no github não encontra-se atualizado com o master, como proceder? Já tentei através do vscode atualizar com o git push mais não fica atualizado, atualizei o repositório local a partir do master através de um git clone para não ficar tão discrepante na hora de trabalhar mais sei que é um método apenas provisório.

**Comment by mgckaled** [comment]
@aknazevedo2 O "master" faz referência ao repositório do professor? 
Se, sim , veja se a issue #97 ajuda.

**Comment by tsartori** [comment]
Veja a Issue [102]([https://github.com/iurygdeoliveira/novos_caminhos/issues/102)
