### ISSUE TITLE
EXTENSÃO PARA COLOCAR ARQUIVOS PDF NO VS CODE

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#175]
Boa tarde, alguém poderia me dizer na extensão utilizada no vs code, para colocar arquivos em pdf no VS CODE?

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 

Existem várias, te uma que o nome dela é vscode-pdf. Só digitar lá na visão de extensões que já aparece.
