### ISSUE TITLE
Como sincronizar a conta existente do Github no GIT?

### ISSUE THREAD

**Issue by reisweslley** [iurygdeoliveira/novos_caminhos#176]
Boa tarde, estou com dúvidas de como configurar o GIT com a minha conta existente do Github. Qual comando eu devo utilizar para fazer essa tarefa?

**Comment by mgckaled** [comment]
@reisweslley  Tem alguns comandos que vc pode utilizar. Talvez ajude. 

Para verificar se o email e o nome do usuário correspondem ao da sua sua conta do Github entre no terminal (bash, por exemplo) e digite os comandos:

´´´
git config --global user.name "<seu nome>"
git config --global user.email "<seu email>"
´´´

Seu nome e seu e-mail dever ter correspondência exata ao da sua conta no Github. Depois digite os comandos para checar as alterações

```
git config --global user.name 
git config --global user.email 
```
Exemplo:
![Screenshot_2](https://user-images.githubusercontent.com/58960702/91776849-b1f59300-ebc4-11ea-91fb-03f7ea12f682.jpg)

Espero que ajude de alguma forma.

**Comment by iurygdeoliveira** [comment]
@reisweslley e após os passos ditos por @mgckaled 

Para configurar um repositorio especifico voçê deve usar o comando git remote add <url do repositorio>
