### ISSUE TITLE
Dúvida sobre apagar forks

### ISSUE THREAD

**Issue by grazirtr** [iurygdeoliveira/novos_caminhos#177]
Olá, Como faço para apagar um fork que fiz errado?

**Comment by mgckaled** [comment]
issue #193

**Comment by tsartori** [comment]
![image](https://user-images.githubusercontent.com/21146217/91774063-5de7b000-ebbe-11ea-8852-2f4b02cc720e.png)
Entre na opção "Settings" no projeto forkado e rola até o final da pagina, lá vc tem a opção de excluir o repositório 'Delete this repository'

**Comment by mgckaled** [comment]
@grazirtr   Veja se a issue #163 ajuda.

**Comment by iurygdeoliveira** [comment]
@grazirtr ,

E ai conseguiu resolver o problema com a dica do @tsartori ?  Nos dê um feedback ...
