### ISSUE TITLE
Não consigo executar Cmder no Windows 10.

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#178]
![image](https://user-images.githubusercontent.com/70357300/91771464-6b4e6b80-ebb9-11ea-9223-1cbbe0c82225.png)

**Comment by fernandoifto** [comment]
Se você reparar o arquivo tem 0 KB provavelmente não baixou. ou corrompeu.

**Comment by jamilempc20** [comment]
obrigada.
