### ISSUE TITLE
Estou com a mesma duvida, pois ao realizar um git pull me retorna "Already up to date". E os novos arquivos que o @iurygdeoliveira deu merge no projeto principal não são acrescentados.

### ISSUE THREAD

**Issue by aknazevedo2** [iurygdeoliveira/novos_caminhos#180]
Estou com a mesma duvida, pois ao realizar um git pull me retorna "Already up to date". E os novos arquivos que o @iurygdeoliveira deu merge no projeto principal não são acrescentados.
![image](https://user-images.githubusercontent.com/21146217/91508545-2de29900-e8ae-11ea-9688-34988c572479.png)

_Originally posted by @tsartori in https://github.com/iurygdeoliveira/novos_caminhos/issues/97#issuecomment-682261342_

**Comment by aknazevedo2** [comment]
Quando fiz minha pergunta estava me referindo a este problema, acontece o mesmo comigo. Ai para que o meu  repositório local fica-se atualizado fiz um git clone do repositório de Yuri, mais o meu fork não atualiza no site do github não atualiza. No meu vscode acontece o mesmo da imagem, dando a entender que ele foi atualizado contudo não foi feita a atualização.

**Comment by iurygdeoliveira** [comment]
@aknazevedo2 

Segue o vídeo demonstrativo espero acredito que vai resolver a questão: https://youtu.be/e9VJ9kzVY20
