### ISSUE TITLE
Problemas no settings.json

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#182]
Professor, eu instalei o git, o git flow, fiz os comandos do repositório. Mas acho que tem alguma coisa errada, pois os meus comandos estão diferentes do seu. Inclusive o tutorial do Git que está no github não aparece para mim, imaginei que após baixar o Settings Sync isso aconteceria de forma automática. 
![image](https://user-images.githubusercontent.com/70357300/91783981-1110d300-ebd8-11ea-91d4-ae31d0c9f832.png)

A parece também essa mensagem de erro settings.json. 
![image](https://user-images.githubusercontent.com/70357300/91784131-84b2e000-ebd8-11ea-896e-d25eec98104c.png)

Estou usando o windows 10.

**Comment by iurygdeoliveira** [comment]
@jamilempc20 blz

Funciona assim:
1º Você faz um fork do repositorio novos caminhos da minha conta para a sua conta no github
2º Você faz um git clone <url do repositorio forkado na sua conta>

Eu já disponibilizei no github, todo o passo a passo, e as configurações do settings.json que estou utilizando, você já deu uma olhada ?  Me dê um feedback ...

**Comment by jamilempc20** [comment]
Professor, estou na parte 3  da atividade 4. Eu fiquei confusa pois você estava realizando uns comandos e ao verificar o meu percebi que os meus comandos não correspondia. Então essa explicação está mais para frente em outros vídeos?
O passo a passo que você diz é  está aqui? 
![image](https://user-images.githubusercontent.com/70357300/91878366-8f5f8a80-ec55-11ea-9384-1d4e031d8a4d.png)

Estou assistindo os videos para depois realizar. Mas fiquei perdida e preocupada se tinha algo errado e se realizei as atividades anteriores de mandeira correta.
