### ISSUE TITLE
Git no VS code terminal realizar login no git

### ISSUE THREAD

**Issue by JPeeMP** [iurygdeoliveira/novos_caminhos#183]
Tenho dúvidas sobre como fazer login no github pelo terminal e acessar o repositório por lá, fica tudo confuso, daí complica pra fazer pull ou push de arquivos.

**Comment by iurygdeoliveira** [comment]
@JPeeMP , tudo bem 

Quando você faz o git clone, ou git remote,  o git ele automaticamente vai solicitar o login de acesso para você no próprio terminal.

Se você tiver configurado a chave ssh, então ela já faz a autenticação de forma automática.

Outro coisa, não é possível acessar o repositorio remoto, pelo terminal. O repositorio remoto sempre é um espelho do repositorio local, você apenas envia os arquivos para o repositório remoto através do git.

Para acessar o repositorio remoto (GITHUB) você deve acessar o portal do github mesmo.
