### ISSUE TITLE
Para o sistema operacional linux como acessar o terminal?

### ISSUE THREAD

**Issue by santaali** [iurygdeoliveira/novos_caminhos#184]
Como nunca utilizei Linux ficou a dúvida se devo baixar um programa ou já vem instalado na máquina, seria uma curiosidade já que no momento possuo o Windows.

**Comment by DerreckMarques** [comment]
Já vem instalado. Pode usar o atalho Ctrl + Alt + T ou pesquisar nos programas por Terminal.

**Comment by iurygdeoliveira** [comment]
@santaali isso mesmo que o @DerreckMarques disse.
