### ISSUE TITLE
Como confirmar que a contribuição foi feita?

### ISSUE THREAD

**Issue by lotharbenmuyal** [iurygdeoliveira/novos_caminhos#186]
Apareceu que a contribuição foi feita, mas não sei aonde confirmar se foi enviada para o Github, onde eu vejo isso?

**Comment by danielcanoli** [comment]
Além das msgs que vc recebe nos comandos, no seu perfil tem um gráfico com vários quadradinhos indicando quando vc fez determinada contribuição. Ao clicar em cada quadradinho desse, dá pra ver mais detalhes sobre a contribuição.

**Comment by iurygdeoliveira** [comment]
Você pode acessar esse link: https://github.com/iurygdeoliveira/novos_caminhos/graphs/contributors
