### ISSUE TITLE
Problemas no settings.json

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#187]
Professor, estou na parte 3  da atividade 4. Eu fiquei confusa pois você estava realizando uns comandos e ao verificar o meu percebi que os meus comandos não correspondia. Então essa explicação está mais para frente em outros vídeos?
O passo a passo que você diz é  está aqui? 
![image](https://user-images.githubusercontent.com/70357300/91878366-8f5f8a80-ec55-11ea-9384-1d4e031d8a4d.png)

Estou assistindo os videos para depois realizar. Mas fiquei perdida e preocupada se tinha algo errado e se realizei as atividades anteriores de mandeira correta.

_Originally posted by @jamilempc20 in https://github.com/iurygdeoliveira/novos_caminhos/issues/182#issuecomment-684977550_

**Comment by iurygdeoliveira** [comment]
@jamilempc20 você está tentando atualizar seu repositorio forkado ? Certo ?

Dê uma olhada nesses vídeos:

Link: https://youtu.be/AY0hQGFgdmQ
