### ISSUE TITLE
Problema no git clone, para realizar o processo de sincronização do repositório

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#188]
LUCAS1@LUCAS MINGW64 /c/xampp/htdocs/novos_caminhos-1 (master)
$ git clone git@github.com:iurygdeoliveira/novos_caminhos.git
Cloning into 'novos_caminhos'...
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Prof. Iury, boa tarde, quando fui realizar o procedimento para sincronização do Github, apareceu o erro acima.
![erro](https://user-images.githubusercontent.com/69942630/91903953-76b59b80-ec7a-11ea-99ce-0da5cece5c4f.png)

**Comment by iareis** [comment]
O meu tem apresentado este erro também. Uma opção passageira seria utilizar o clone via HTTPS.

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 boa noite

Isso acontece porque voçê não tem permissão para alterar diretamente o meu repositorio dentro da minha conta. Para conseguir enviar uma contribuição, você deve fazer um fork do repositorio para a sua conta, e através desse repositório forkado, você deve fazer os pull requests para que suas contribuições sejam enviadas para a minha conta.

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 tudo bem,

Neste caso, não será necessário. 

Mas só ressaltando e observando o endereço do git clone, no print acima. Você está fazendo um git clone direto da minha conta, mas você necessita fazer um git clone do repositório forkado de sua conta no github.

**Comment by jalexandrersilva** [comment]
Olá professor. Será que antes de atuar o repositório forjado qual comando ele precisa fazer primeiro?

Atualizar o repositório no PC dele pra depois subir pra conta github dele?

**Comment by iurygdeoliveira** [comment]
Sim, primeiro ele atualiza o repositorio local dele, e depois faz o merge com o repositorio local e depois faz o git push para a conta dele.

Link da aula com a demonstração: https://youtu.be/e9VJ9kzVY20
