### ISSUE TITLE
Quando temos vários REPOSITÓRIOS, como direcionar um arquivo para 1 específico?

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#191]
(1) Estou enfrentando o seguinte problema. Altero um arquivo  ou mesmo crio um novo arquivo para que ele seja inserido como uma contribuição no **iurygdeoliveira/novos_caminhos** do professor. Sigo os passos e envio para a ORIGEN (GITHUB), mas tenho encaminhado para **iareis/novos_caminhos_** ao invés do desejado **iareis/novos_caminhos** onde poderia solicitar um pull request.

(2) Se o arquivo iuri.php da imagem abaixo está em outro repositório há como enviá-lo para o repositório forkado do Prof, Iury? 

![image](https://user-images.githubusercontent.com/69777395/91924911-4c7bd200-ecaa-11ea-8a86-7587f60c26f8.png)

(3) Consegui enviar arquivos normalmente para um terceiro repositório.

![image](https://user-images.githubusercontent.com/69777395/91925130-c3b16600-ecaa-11ea-8788-8c4794e19de9.png)

**Comment by iurygdeoliveira** [comment]
@iareis 

Abra a pasta onde está o seu repositório, e la dentro dá o seguinte comando: git remote -v

Depois print o resultado aqui, acredito que o git remote configurado esteja errado, mas para confirmar, eu preciso ver o endereço que está configurado.

**Comment by iareis** [comment]
Bah, professor, não vou conseguir demonstrar aqui. Eu não estava conseguindo evoluir e ficando irritado por enviar os arquivos para onde eu não queria. Resolvi apagar tudo e reiniciar.
