### ISSUE TITLE
Erro “fatal: refusing to merge unrelated histories” ao tentar usar o comando merge para sincronizar os repositórios.

### ISSUE THREAD

**Issue by joaops2001** [iurygdeoliveira/novos_caminhos#192]
Tive este erro e pesquisando, consegui solucionar acrescentando o comando --allow-unrelated-histories após o comando merge, ficando assim:
git merge upstream/master --allow-unrelated-histories

Só estou compartilhando pra caso o de mais alguém venha a dar este erro. :)

**Comment by jalexandrersilva** [comment]
Eu achei também muito útil o git remote - v

**Comment by iurygdeoliveira** [comment]
@joaops2001 , blz !
