### ISSUE TITLE
Dual boot pode danificar HD? 

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#194]
Um colega me perguntou. Eu tinha um HD de 1 tr e deu pau. Mas também talvez não tenha sido o dual boot. O mesmo notebook apresentou defeitos no teclado. 
Então venho buscar as experiências dos colegas com relação a isso

**Comment by eufelipeigor** [comment]
De acordo com meus conhecimentos não ocorre problema ao fazer o dual boot, o que vc pode ter feito é "desconfigurado" o HD, de forma que o notebook ou o sistema operacional não esteja reconhecendo ele, é muito comum acontecer com a marca lenovo, é como se a BIOS tivesse uma proteção. 

Mas geralmente, formatar o HD e reinstalar o sistema operacional resolve.

Obs: se por acaso tiver problemas com exclusão das partições, é necessário apagar tudo e criar uma novamente. 

Obs: para mais informações, e passo a passo de como fazer esses procedimentos recomendo buscar por vídeos no YouTube de pessoas que estejam com o mesmo problema, no mesmo modelo do seu notebook.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva é isso mesmo que o @eufelipeigor disse.
