### ISSUE TITLE
Erro ao iniciar Ubuntu

### ISSUE THREAD

**Issue by clelianidecdasilva** [iurygdeoliveira/novos_caminhos#196]
Atualmente estou fazendo as instalações no Windows, no entanto, quero aprender a trabalhar no Linux. Portanto, instalei o Ubuntu usando o Oracle VM VirtualBox, mas ao iniciar o Ubuntu ocorre o seguinte erro:

[10.2128431] [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send host log message”

**Comment by iurygdeoliveira** [comment]
@clelianidecdasilva tudo bem

Eu realmente não consigo te ajudar nesse erro, pois não faço ideia do que seja a causa.

Minha opinião pessoal, utilizar o ubuntu em um hd, e o windows em outro hd. E instalar nativamente os dois sistemas em modo dual boot. Utilizar o ubuntu em maquina virtual, vai exigir que sua máquina hospede tenha uma boa memoria, e processamento, pois seu hardware terá que suportar dois sistemas operacionais.

E parabéns pela iniciativa, é com essa postura que você dominará as técnicas de programação.

**Comment by clelianidecdasilva** [comment]
@iurygdeoliveira obrigada pela sugestão. Vou pesquisar como instalar nativamente os dois sistemas em modo dual boot.
