### ISSUE TITLE
O que significa a mensagem Everything up-to-date dada pelo git ?

### ISSUE THREAD

**Issue by Bruno015** [iurygdeoliveira/novos_caminhos#199]
Olá, tenho uma dúvida em relação ao comando _"git push"_, sempre que tento utilizá-lo, não consigo atualizar o repositório remoto justamente por ficar aparecendo esta frase do título. O que deveria fazer para corrigir isso?

**Comment by iurygdeoliveira** [comment]
@Bruno015 tudo bem

Essa mensagem significa que seu repositório local está sincronizado com seu repositório remoto.

Se você estiver querendo atualizar o seu repositório forkado, dá uma olhadinha nas issue #102 

Além disso postei dois vídeos gravados sobre como atualizar o repositório forkado, já viu ?

**Comment by Bruno015** [comment]
Ah, entendi, muito obrigado. Ainda não vi os vídeos, mas vou dar uma olhada depois sim
