### ISSUE TITLE
Nao consigo passar deste erro. --help!!!

### ISSUE THREAD

**Issue by LuizAlves99** [iurygdeoliveira/novos_caminhos#200]
![image](https://user-images.githubusercontent.com/69818210/92123198-bb544a80-edd2-11ea-9883-1a7a7bb2b889.png)
![image](https://user-images.githubusercontent.com/69818210/92123286-d58e2880-edd2-11ea-9817-8f6996c3664c.png)
![image](https://user-images.githubusercontent.com/69818210/92123579-2f8eee00-edd3-11ea-9c9f-2a3c3c5587d1.png)
![image](https://user-images.githubusercontent.com/69818210/92123691-4df4e980-edd3-11ea-9dd1-65423a882c1a.png)
![image](https://user-images.githubusercontent.com/69818210/92123812-649b4080-edd3-11ea-8aa7-56ebe3b22c61.png)
![image](https://user-images.githubusercontent.com/69818210/92123864-754bb680-edd3-11ea-9c0d-95da53c60020.png)

Alguem tem ideia do que tá errado?
Me ajuda ai Prof

**Comment by iurygdeoliveira** [comment]
@LuizAlves99 tudo bem

Após a última tela, o git informa que seu branch master está atrás do repositório remoto.

Dá um comando git pull para que ele baixe as atualizações do repositório remoto para o repositório local.

Depois dê um comando git status e poste o resultado aqui.

**Comment by LuizAlves99** [comment]
![image](https://user-images.githubusercontent.com/69818210/92177233-7a7e2500-ee16-11ea-8d1a-2777028c613c.png)
![image](https://user-images.githubusercontent.com/69818210/92177268-8964d780-ee16-11ea-9614-b9ea8b81906f.png)
![image](https://user-images.githubusercontent.com/69818210/92177340-b0230e00-ee16-11ea-851d-c694e63f4625.png)
![image](https://user-images.githubusercontent.com/69818210/92177379-c4670b00-ee16-11ea-8609-ba4c3b255403.png)

**Comment by LuizAlves99** [comment]
Ainda não entendo o que acontece ...

**Comment by LuizAlves99** [comment]
Bom dia professor. Passei horas revendo todos os videos e lives e ainda não encontrei onde estou errando.
estou travado nesse erro e não consigo continuar, estou ficando pra trás. Ainda nem vi os videos da etapa 5  e já estão na 6
será que devo apagar tudo e começar do zero???

**Comment by iurygdeoliveira** [comment]
@LuizAlves99 tudo bem

Se você ainda não tiver feito nada no repositório até este momento. E pela análise dos seus prints, faça o seguinte:

1) git pull origin master -> para atualizar seu repositório local na branch master com a branch master do repositório remoto
2) git add .  -> para adicionar controle de versão nas mudanças que você fez recentemente
3) git commit -m "comentário"  -> para comitar as mudanças 
4) git pull origin master -> para enviar as mudanças do seu repositório local para o repositório remoto.

Obs.: Após dar comando em 1) pode dar um git status, para verificar o status atual do repositório.

**Comment by LuizAlves99** [comment]
![image](https://user-images.githubusercontent.com/69818210/92281633-5d0e9100-eed2-11ea-9287-4feecaf5ead3.png)
![image](https://user-images.githubusercontent.com/69818210/92281715-98a95b00-eed2-11ea-802d-e563e7d3335f.png)
![image](https://user-images.githubusercontent.com/69818210/92281767-b1b20c00-eed2-11ea-87d0-47eedda6ba74.png)

**Comment by LuizAlves99** [comment]
fiz tudo outra vez com alterações. será que agora deu certo?
![image](https://user-images.githubusercontent.com/69818210/92282473-06a25200-eed4-11ea-9963-1cc47fa597e8.png)

**Comment by LuizAlves99** [comment]
Tinha faltado o Push... eu fiz e acho que funcionou ufaaa
![image](https://user-images.githubusercontent.com/69818210/92282803-c394ae80-eed4-11ea-8efb-14cf6bffd919.png)

**Comment by LuizAlves99** [comment]
depois de assistir os videos já fiz o Request e só aguardando agora o Merge

**Comment by iurygdeoliveira** [comment]
@LuizAlves99  

Merge feito !
