### ISSUE TITLE
Versão de Sistema Windows Incompatível com Docker Desktop

### ISSUE THREAD

**Issue by RicardoLMattos** [iurygdeoliveira/novos_caminhos#201]
Alguma solução pra isso?
Estou usando a versão Windows 10 Home Single Language.

![image](https://user-images.githubusercontent.com/69875676/92127548-cbbaf400-edd7-11ea-9ef4-1ebbc8f80845.png)

**Comment by iurygdeoliveira** [comment]
@RicardoLMattos vou pesquisar uma solução

**Comment by mgckaled** [comment]
No StackOverFlow há uma discussão sobre esse problema: https://stackoverflow.com/questions/60809467/cant-install-docker-docker-desktop-requires-windows-10-pro-or-enterprise-vers

Reparei que no site do Docker pede a versão 2004 do Windows 10 Home Single Language: https://docs.docker.com/docker-for-windows/install-windows-home/

No meu notebook funcionou porque tenho essa versão. 
![Screenshot_1](https://user-images.githubusercontent.com/58960702/92144029-7b01c600-edec-11ea-905a-670f65a0dc0d.jpg)

Eu faço as atualizações de forma regular. Talvez seja esse o motivo.  Tente verificar se há atualizações pendentes do Windows. https://support.microsoft.com/pt-br/help/4557956/compatibility-update-for-installing-windows-10-version-2004

Se não der certo talvez seja necessário fazer a instalação manual desta versão.

Espero que ajude.

**Comment by Lana-Monteiro** [comment]
@RicardoLMattos veja como instalar o docker no windows home, veja se o processo que você fez foi assim...

Ps: Antes de seguir esses passos, siga primeiro os passos de desinstalação e tente instalar novamente!
### Desinstale o Docker Desktop 

Para desinstalar o **Docker Desktop** de sua máquina Windows Home:

No menu **Iniciar do Windows** , selecione **Configurações > Aplicativos > Aplicativos e recursos** .
Selecione **Docker Desktop** na lista de** Aplicativos e recursos** e selecione **Desinstalar** .
Clique em **Desinstalar para confirmar sua seleção**.

### **Instale o Docker Desktop no Windows 10 Home** 

Clique duas vezes em **Docker Desktop Installer.exe** para executar o instalador.

Se você ainda não baixou o instalador (` Docker Desktop Installer.exe`), pode obtê-lo no [Docker Hub](https://hub.docker.com/editions/community/docker-ce-desktop-windows/) . Normalmente, ele é baixado para a sua ` Pasta Downloads` ou você pode executá-lo na barra de downloads recentes na parte inferior do seu navegador.

Quando solicitado, certifique-se de que a opção **Ativar recursos WSL 2** esteja selecionada na página Configuração.

Siga as instruções do assistente de instalação, autorize o instalador e prossiga com a instalação.

Quando a instalação for bem-sucedida, clique em **Fechar** para concluir o processo de instalação.

### **Inicie o Docker Desktop** 

O Docker Desktop não inicia automaticamente após a instalação. Para iniciar o Docker Desktop, procure Docker e selecione **Docker Desktop** nos resultados da pesquisa.
![docker-app-search](https://user-images.githubusercontent.com/70002874/92285783-939cd980-eedb-11ea-832f-062f62c90241.png)



Quando o ícone de baleia na barra de status permanece estável, o Docker Desktop está instalado e funcionando e pode ser acessado de qualquer janela de terminal.

![whale-icon-systray](https://user-images.githubusercontent.com/70002874/92285893-e1b1dd00-eedb-11ea-8440-eabceb9e88fb.png)

Quando a inicialização é concluída, o Docker Desktop inicia o tutorial de integração. O tutorial inclui um exercício simples para construir uma imagem Docker de exemplo, executá-la como um contêiner, enviar e salvar a imagem no Docker Hub.

![docker-tutorial-win](https://user-images.githubusercontent.com/70002874/92285948-03ab5f80-eedc-11ea-8803-4f1fe5a2f26f.png)

**Comment by Lana-Monteiro** [comment]
@RicardoLMattos Lembrando que.. verifique essas informações antes de iniciar o processo de instalação

###  O que saber antes de instalar

 
### Requisitos do sistema 

As máquinas Windows 10 Home devem atender aos seguintes requisitos para instalar o Docker Desktop:

- Instale o Windows 10, versão 2004 ou superior.
- Ative o recurso WSL 2 no Windows. Para obter instruções detalhadas, consulte a [documentação](https://docs.microsoft.com/en-us/windows/wsl/install-win10) da [Microsoft](https://docs.microsoft.com/en-us/windows/wsl/install-win10) 

- Os seguintes pré-requisitos de hardware são necessários para executar o WSL 2 com êxito no Windows 10 Home:

 1. Processador de 64 bits com [Tradução de Endereço de Segundo Nível SLAT](https://en.wikipedia.org/wiki/Second_Level_Address_Translation).
 2. RAM de sistema de 4 GB
 3. O suporte à virtualização de hardware no nível do BIOS deve ser habilitado nas configurações do BIOS. Para obter mais informações, consulte [Virtualização](https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled) .

- Baixe e instale o pacote de atualização do kernel [Linux](https://docs.microsoft.com/pt-br/windows/wsl/wsl2-kernel) .

### Sobre os contêineres do Windows 
Procurando informações sobre o uso de contêineres do Windows?

- [Alternar entre contêineres do Windows e do Linux](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers) descreve como você pode alternar entre contêineres do Linux e do Windows no Docker Desktop e aponta para o tutorial mencionado acima.

- [Introdução aos contêineres do Windows (Lab)](https://github.com/docker/labs/blob/master/windows/windows-containers/README.md) fornece um tutorial sobre como configurar e executar contêineres do Windows no Windows 10, Windows Server 2016 e Windows Server 2019. Ele mostra como usar um aplicativo MusicStore com contêineres do Windows.

- [Artigos e postagens de blog](https://www.docker.com/partners/microsoft) do Docker Container Platform for Windows no site do Docker.

**Comment by RicardoLMattos** [comment]
> @RicardoLMattos talvez o problema seja a versão do seu Windows 10 Home Single Language.
> 
> No StackOverFlow há uma discussão sobre esse problema: https://stackoverflow.com/questions/60809467/cant-install-docker-docker-desktop-requires-windows-10-pro-or-enterprise-vers
> 
> Reparei que no site do Docker pede a versão 2004 do Windows 10 Home Single Language: https://docs.docker.com/docker-for-windows/install-windows-home/
> 
> No meu notebook funcionou porque tenho essa versão.
> ![Screenshot_2](https://user-images.githubusercontent.com/58960702/92144355-f6fc0e00-edec-11ea-8955-29b71c8302af.jpg)
> 
> Eu faço as atualizações de forma regular. Talvez seja esse o motivo. Tente verificar se há atualizações pendentes do Windows. Neste link informa que a instalação da versão 2004 é feita de forma automática https://support.microsoft.com/pt-br/help/4557956/compatibility-update-for-installing-windows-10-version-2004
> 
> Se não der certo talvez seja necessário fazer a instalação manual desta versão.
> 
> Espero que ajude.

Valeu mgckaled, realmente o problema estava relacionado a versão (estava usando a 1903), atualizei para 2004 e funcionou. Obg!

**Comment by RicardoLMattos** [comment]
Obrigado pela ajuda Lana-Monteiro, deu certo aqui!

**Comment by iurygdeoliveira** [comment]
@RicardoLMattos, blz que bom que resolveu

Parabens @Lana-Monteiro !
