### ISSUE TITLE
Erro no pré cadastro IFTO

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#202]
Professor, coloquei meu nome como José Alexandre e o sistema atribuiu JOSÃ Alexandre. Por onde eu peço pra retificar?

**Comment by iurygdeoliveira** [comment]
@danielcanoli @luciano-federal 

Como resolver ?

**Comment by jalexandrersilva** [comment]
Já foi corrigido. Eu só preciso saber se o e-mail gerado do IFTO ficou josa ou jose

**Comment by jalexandrersilva** [comment]
Bom dia. O e-mail está josa.silva@estudante.ifto.edu.br.  Tá tranquilo 

Mas o nome do cadastro no SIGA continua JOSÃ em vez de JOSÉ

**Comment by iurygdeoliveira** [comment]
@luciano-federal e @danielcanoli , depois verifiquem essa situação aqui

**Comment by luciano-federal** [comment]
Problema resolvido @jalexandrersilva e @iurygdeoliveira no SIGA.
