### ISSUE TITLE
Como criar aliases para os comandos no Windows ?

### ISSUE THREAD

**Issue by JohnnyfWSilva** [iurygdeoliveira/novos_caminhos#203]
1- Não consigo criar o bash_aliases. Fiz algumas pesquisas e testes, mas não consegui. Pelo menos não pelo cmd. Abri outra pasta e iniciei um terminal bash. Consegui com o touch ~\.bash_aliases. Agora é que vem o problema. Na pasta novos_caminhos, onde está configurado o cmder, não dá para criar um terminal bash, simplesmente não abre, pelo menos não aqui, a não ser que se apague do Json as linhas do cmder. Mas fazer isso sempre não é nada prático. Não sei onde está meu erro. Gostaria de conseguir migrar entre os terminais cmder e bash. Quando tento fazer isso na pasta novos_caminhos, sempre é criado um cmd.

2 - Cmd não lê ls. Não sei se me confundi, mas vi o professor usando ls no cmder nos vídeos. Como não consegui por aqui (meu sistema é Windows), estou usando o dir.

**Comment by jalexandrersilva** [comment]
Além de definir o cmder como padrão você precisa de outro parâmetro no settings.json. Se alguém tiver posta aí, não estou com o computador aqui

**Comment by iurygdeoliveira** [comment]
@JohnnyfWSilva o bash_aliases, é específico para sistemas operacionais linux, se estiver usando windows, é de outro jeito.

**Comment by JohnnyfWSilva** [comment]
1 - Eu li sobre isso, mas não entendi muito bem o processo. Vou tentar de novo e qualquer coisa posto aqui.
2 - Os que eu usei foram esses dois que o professor passou.
![image](https://user-images.githubusercontent.com/70163346/92240932-c28f5d00-ee93-11ea-8d87-2fdafa393610.png)

**Comment by tsartori** [comment]
> 1 - Eu li sobre isso, mas não entendi muito bem o processo. Vou tentar de novo e qualquer coisa posto aqui.
> 2 - Os que eu usei foram esses dois que o professor passou.
> ![image](https://user-images.githubusercontent.com/70163346/92240932-c28f5d00-ee93-11ea-8d87-2fdafa393610.png)

Você esta utilizando WINDOWS, o .bash_aliases é do LINUX. No seu caso não sei dizer se o windows tem algo parecido.

**Comment by JohnnyfWSilva** [comment]
Então esse .bash_aliases que eu criei em outra pasta não funciona, é isso?
![image](https://user-images.githubusercontent.com/70163346/92281764-af4fb200-eed2-11ea-89a9-d44f27155612.png)

**Comment by tsartori** [comment]
Exatamente, de nada vale. Vida que segue 😂

**Comment by iurygdeoliveira** [comment]
Como fazer aliases no windows, alguém sabe ?

**Comment by JohnnyfWSilva** [comment]
Dá para criar aliases para o próprio cmder a partir do comando "alias". Serve para quem está usando o cmder (eu estou).

alias/? para conferir os outros comandos
alias/d <nome da alias> para apagar uma alias

Segue o que eu fiz:
![image](https://user-images.githubusercontent.com/70163346/92972299-652d7a00-f458-11ea-8406-485dedc9d8b8.png)

Ps: fica salvo para as próximas seções

**Comment by afonsonrodrigues** [comment]
Abra o ~/.gitconfig e adicione os atalhos...
Exemplo: 
[alias]
  co = checkout
  cm = commit
  ac = !git add -A && git commit
  st = status -sb
  tags = tag -l
  branches = branch -a
  remotes = remote -v

ou ir adicionando na linha de comando um a um.
Exemplo:
$ git config --global alias.st status
$ git config --global alias.ac '!git add -A && git commit'

Depois do ponto (alias.) é o comando que vc quer usar e logo depois o comando a ser substituído.

Achei bem fácil dos dois jeitos.
