### ISSUE TITLE
Perda da LIVE de Sábado

### ISSUE THREAD

**Issue by Rodrigobyte** [iurygdeoliveira/novos_caminhos#205]
Boa noite professor.

Perdi as duas lives que foram disponibilizadas. Por um acaso a de sábado foi gravada?
Pode ser disponibilizado o link?

Obrigado

**Comment by iurygdeoliveira** [comment]
@Rodrigobyte 

Segue o link: https://www.youtube.com/watch?v=2PG-UztEbcs&feature=emb_logo
