### ISSUE TITLE
Problemas ao instalar o docker desktop 

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#206]
BOA NOITE, PROFESSOR, NÃO ESTOU CONSEGUINDO INSTALAR O DOCKER HUB, ESTAR DANDO ERRO
![Captura de Tela (5)](https://user-images.githubusercontent.com/70108902/92193264-43236e80-ee3e-11ea-8c43-ffc1efd873a2.png)

**Comment by iurygdeoliveira** [comment]
@josepereirakls , tudo bem ?

Já deu uma olhadinha na issue #201 ?

**Comment by josepereirakls** [comment]
bom dia professor, fiz toda a atualização do windows 2004, e agora estar dando outro erro.
![Captura de Tela (6)](https://user-images.githubusercontent.com/70108902/92304484-b9b29000-ef54-11ea-8fa4-1a2ea5fedac5.png)

**Comment by iurygdeoliveira** [comment]
@luciano-federal ou @danielcanoli ou @fernandoArantes

Verifiquem este caso por gentileza, acredito que na issue #201 isso já tenha resolvido.

**Comment by fernandoifto** [comment]
No meu Windows deu o mesmo erro abre esse link acredito que eu tive que baixar um programa que fez funcionar, contudo antes de funcionar o Windows atualizou mais uma vez.

**Comment by BastleH** [comment]
Instala o Docker Toolbox https://github.com/docker/toolbox/releases/download/v19.03.1/DockerToolbox-19.03.1.exe

**Comment by iurygdeoliveira** [comment]
@josepereirakls com a dica do @BastleH resolveu ?

**Comment by josepereirakls** [comment]
Professor conseguir instalar depois que fiz as atualizações do windows.
so que quando vou abrir o docker desktop, ele não abre, nao sei se isso é certo.

**Comment by BastleH** [comment]
@josepereirakls Estava pesquisando e achei passo a passo de como instalar o docker pelo toolbox, segue o link: https://www.youtube.com/watch?v=1PoU2hBLaRs

**Comment by iurygdeoliveira** [comment]
@josepereirakls qual o erro está mostrando ?

**Comment by josepereirakls** [comment]
BOM DIA PROFESSOR, EU TENTO ABRIR ELE DAI ELE SIMPLISMENTE NAO, APARECE ESSA MENSAGEM BEM NO CANTINHO ESQUERDO.
![Captura de Tela (6)](https://user-images.githubusercontent.com/70108902/92993589-2be12280-f4c9-11ea-8a38-5e0232d28213.png)
![Captura de Tela (7)](https://user-images.githubusercontent.com/70108902/92993591-2edc1300-f4c9-11ea-8554-3f3977d21e8e.png)

**Comment by fernandoifto** [comment]
Essa é a mensagem que ele dar quando o Docker esta execultando tudo certo.
![Capturar](https://user-images.githubusercontent.com/8673558/92997743-c4889a00-f4eb-11ea-963f-402b8da801ea.PNG)

**Comment by fernandoifto** [comment]
Clica com o botão direito do mouse na icone do docker na area de notificação vc pode abrir o dashboard.
![Capturar](https://user-images.githubusercontent.com/8673558/92997800-5b555680-f4ec-11ea-9111-48ae5e96ea62.PNG)

**Comment by fernandoifto** [comment]
Se vc já tiver baixado a imagem do NGINX e do PHP vai mostrar como minha imagem.

![Capturar](https://user-images.githubusercontent.com/8673558/92997824-8d66b880-f4ec-11ea-996d-db0c31d87e26.PNG)

**Comment by iurygdeoliveira** [comment]
@josepereirakls resolvido o problema ?

**Comment by k-js** [comment]
![Captura de tela 2020-09-13 122653](https://user-images.githubusercontent.com/70825783/93022001-b48cbb00-f5bc-11ea-88cb-fb1805006efb.png)
Nao consigo fazer as atualizações  e instalar o docker toolbox!

**Comment by k-js** [comment]
@iurygdeoliveira

**Comment by iurygdeoliveira** [comment]
@k-js tudo bem

Não faço ideia do que possa ser, a unica coisa que posso te indicar e tentar atualizar o seu sistema, pelos meios tradicionais. 

Quero preparar um tutorial do toolbox para o pessoal

**Comment by iurygdeoliveira** [comment]
@fernandoifto , @luciano-federal ou @danielcanoli sabem a solução ?

**Comment by fernandoifto** [comment]
@iurygdeoliveira eu estava ajudando até esse ponto não conseguimos atualizar o Windows de forma alguma procurei uns videos que tratavam de correção de erro da atualização sem sucesso.
