### ISSUE TITLE
ERRO - DOCKER-COMPOSE UP

### ISSUE THREAD

**Issue by Jacksonmelo43** [iurygdeoliveira/novos_caminhos#210]
![image](https://user-images.githubusercontent.com/69887919/92249973-3b48e600-eea1-11ea-92db-91a6063649f7.png)

**Comment by Jacksonmelo43** [comment]
Falan que tá dando seguinte erro : Starting novos_caminhos_nginx_1 ... error
ERROR: Encountered errors while bringing up the project.

**Comment by iurygdeoliveira** [comment]
@Jacksonmelo43 tudo bem. 

Existe outro service ocupando a porta 80, provavelmente deve ser o apache.

Faça o seguinte:

1) $ sudo /etc/init.d/apache2 status

Caso seja exibido o apache com o status running, você deverá dar um stop no serviço.

2) $ sudo /etc/init.d/apache2 stop

Por default a distruibuição pode ter instalado o webserver apache em sua máquina. Após dar o comando acima, tente subir o docker-compose novamente.  Se subir, esse deve ser o motivo.

Agora a parte chata, e ter que ficar fazendo isso toda vez que resolver subir o docker-compose. Voçê pode resolver isso desinstalando o apache de sua distribuição com o comando **sudo apt-get remove --purge apache**. É o que eu faria, para o nosso curso, não iremos utilizar o apache, apenas a estrutura do docker mesmo.

Outra alternativa é mudar a porta no docker-compose, em vez de 80, utilizar a porta 81 por exemplo, mas isso descaracteriza um pouco a utilização dos webservers, que já utilizam a porta 80 por padrão.

**Comment by Jacksonmelo43** [comment]
depois que eu dei stop no apache apareceu isso : 

![image](https://user-images.githubusercontent.com/69887919/92297576-0f684780-ef17-11ea-8963-c4a002d6651f.png)

**Comment by iurygdeoliveira** [comment]
@Jacksonmelo43 serviço funcionando ! É isso !
