### ISSUE TITLE
Comando Git Push

### ISSUE THREAD

**Issue by DiegoVmg** [iurygdeoliveira/novos_caminhos#211]
![comando git push](https://user-images.githubusercontent.com/69961712/92226698-83551200-ee7b-11ea-892b-6ff900d75a0e.png)

Bom dia Professor Iury, estou com esse problema relacionado ao comando git push.

**Comment by iurygdeoliveira** [comment]
Olá @DiegoVmg 

Isso já aconteceu comigo, mas depois que dei a permissão, não apareceu mais, precisei autorizar apenas uma vez.

Sempre que você dá permissão, e concede as autorizações que github exige, esse pedidos de permissão se repetem ?

**Comment by DiegoVmg** [comment]
Obrigado professor, realmente depois que dei a permissão não apareceu mais.

grato!
