### ISSUE TITLE
Quantas vezes posso fazer forked do repositório novos caminhos

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#212]
Prof. Iury, Boa tarde;

Quantas vezes posso fazer forked do repositório novos caminhos?

**Comment by tsartori** [comment]
Apenas 1 vez.
Caso vc precise atualizar o repositório forcado veja a issue #102 

Se por ventura vc excluir o fork que foi feito, ai sim vc pode realizar um novo fork.

**Comment by iurygdeoliveira** [comment]
Exatamente @tsartori !
