### ISSUE TITLE
STOP NO APACHE

### ISSUE THREAD

**Issue by Jacksonmelo43** [iurygdeoliveira/novos_caminhos#217]
depois que eu dei stop no apache apareceu isso:

![image](https://user-images.githubusercontent.com/69887919/92298030-50faf180-ef1b-11ea-8636-49c5749e94c5.png)

**Comment by DerreckMarques** [comment]
@Jacksonmelo43 assim já está funcionando, só não está em background. Tentar executar desse jeito: sudo docker-compose up -d.

E depois ver os contêineres que estão rodando com: docker ps ou docker-compose ps.

**Comment by iurygdeoliveira** [comment]
@Jacksonmelo43 está funcionando ! Se quiser deixar em backgroun, é só fazer como o @DerreckMarques disse.

Parabéns !
