### ISSUE TITLE
critica construtitiva:  Por favor professor seja objetivo nos videos. 

### ISSUE THREAD

**Issue by silvoneizaghini** [iurygdeoliveira/novos_caminhos#219]
Peço desculpa professor. O senhor é uma grande mestre. Mas esta dificil de assistir os videos. Se para o Senhor falar de um assunto fala daquele assunto objetivamente. Qdo o senhor fica falando de outros assuntos confunde e perde o foco. Digo se para falar de um arquivo forcado, fale do arquivo forcado. Esqueça tecla de atalho. Se a letra mais bonita desta cor ou daquela cor.  Os videos são cansativos. A fuga do assunto torna mais dificil o entendimento e a compreensão do assunto.  O tempo dos estudante e curto. E a fuga do assunto vai desestimulado. Novamente. reitero meu pedido. Mas esta ficando dificil e cansativo de acompanhar.

**Comment by jalexandrersilva** [comment]
Silvo e você precisa ser mais específica e objetiva.... No que o prof. Iury está errando? Porque sou iniciante mas os vídeos dele são didáticos e bem objetivos. Qual é o problema? Não tô puxando saco não, mas acontece que não vejo nada repreensível nos conteudos

**Comment by iurygdeoliveira** [comment]
@silvoneizaghini olá tudo bem, 

Te entendendo, e acredite, estou procurando ser objetivo. Mas poderia ser mais específica em algum vídeo por exemplo ?
