### ISSUE TITLE
Acessar git graph

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#220]
Professor, percebi agora que a extensão git graph não estava instalada. Então instalei, mas não consigo visualizar o gráfico.

Como configuro o git graph?

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva eu fiz da seguinte forma

CTRL + SHITF + P -> para acessar a paleta de comandos

Digitei graph -> para acessar as opções do graph

Depois configurei o comando CTRL + ALT + G nas opções de shortcuts, para sempre que eu digitar o comando, ele abrir novamente o graph

**Comment by jalexandrersilva** [comment]
ok professor. Complementando... ao digitar graph no ctrl shift p a gente clica em graph (in log)

e a configuração do atalho é em shotcut settings... valeu mais uma vez.
