### ISSUE TITLE
Comando git branch só mostra o master depois da instalação do docker

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#221]
Galera, fiquei meia hora esquentando a cabeça mas resolvei.

o comando para mostrar a branch develop é git flow init

e depois segue os passos do vídeo 6.8

**Comment by jalexandrersilva** [comment]
Prof. Iury, por favor estou com esse print de tela.

quais os comandos que devo dar pra ficar tudo certinho?
![atv_prog_web](https://user-images.githubusercontent.com/69798042/92309658-cc8d8a80-ef7d-11ea-9724-3bfca9634891.png)

**Comment by iurygdeoliveira** [comment]
da um comando git remote -v, e posta o resultado, só para eu ter certeza de algo.

Você precisa instalar as bibliotecas do PHP para parar com este erro no canto.

**Comment by jalexandrersilva** [comment]
Estou na hemodiálise. Amanhã pela manhã eu mando a tela.

Como instalo as bibliotecas do PHP?

**Comment by jalexandrersilva** [comment]
Segue a tela pedida do git remote -v. Professor, como instalar as bilbiotecas do php?

![atv_prog_web](https://user-images.githubusercontent.com/69798042/92328881-4420ef80-f03a-11ea-93ad-677e6fd93812.png)

**Comment by jalexandrersilva** [comment]
prof, depois dessa tela executei esses comandos aqui embaixo.

E agora? o que devo fazer?
![atv_prog_web](https://user-images.githubusercontent.com/69798042/92329779-3bcbb300-f040-11ea-9645-8f412a1fce58.png)

**Comment by jalexandrersilva** [comment]
professor, tô parado aguardando suas soluções. a atual tela tá assim... deu erro no finish

![atv_prog_web](https://user-images.githubusercontent.com/69798042/92330945-3aeb4f00-f049-11ea-9761-b9ea3ce275ef.png)

**Comment by iurygdeoliveira** [comment]
> Segue a tela pedida do git remote -v. Professor, como instalar as bilbiotecas do php?
> 
> ![atv_prog_web](https://user-images.githubusercontent.com/69798042/92328881-4420ef80-f03a-11ea-93ad-677e6fd93812.png)

Baseado por este print, e para deixar seu repositorio local organizado.

Vamos deletar o repositorio remoto de nome master do seu computador. Você precisará apenas do origin e do upstream.

Para isso, dentro do repositorio dê o seguinte comando:  **git remote remove master**

**Comment by jalexandrersilva** [comment]
Só isso prof?

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva 

Agora para atualizar o repositório siga os passos descritos nas issue #102 

Além disso, você pode ver a demonstração dos passos, nas aulas:

-  5.1: [Sincronizando repositorio forkado no windows e linux](https://youtu.be/e9VJ9kzVY20l)
-  6.7: [Construindo Infraestrutura de desenvolvimento no windows](https://youtu.be/AY0hQGFgdmQ)
- 7.6: [Sincronizando Infraestrutura no Windows](https://youtu.be/tII12e67TFU)

**Comment by iurygdeoliveira** [comment]
> Só isso prof?
> 
> Toda vez que liga o PC tem que chamar o compõe-se up no cmder não é?
> 
> É as bibliotecas do PHP? Como instalar?

Para instalar as bibliotecas do PHP, basta instalar o xammp no windows.

**Comment by jalexandrersilva** [comment]
Já está instalado professor. Onde devo configurar pra o VScode achar o path?

**Comment by jalexandrersilva** [comment]
olá prof.

dei o git remote remove master
depois segui a issue #102 
git fetch upstream
git merge upstream/master
git push --set-upstream origin develop

E agora prof? tá tudo certo?

![atv_prog_web](https://user-images.githubusercontent.com/69798042/92335195-43548180-f06b-11ea-83f4-d3745f50472d.png)

**Comment by jalexandrersilva** [comment]
bom dia galera. Professor, continuando a assistir o video 6.8 eu consegui executar os comandos de merge e atualizar as branchs. O senhor pode confirmar se está tudo certo agora?

![atv_prog_web](https://user-images.githubusercontent.com/69798042/92392087-1dbf8a80-f0f4-11ea-9297-3319dbd53f03.png)

**Comment by iurygdeoliveira** [comment]
git checkout upstream não vai funcionar mesmo não, ele é apenas um espelho do meu repositório oficial.

E sim, você conclui o processo. Parabens.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva não se faz git checkout para repositorios remotos, apenas entre repositorio locais mesmo
