### ISSUE TITLE
Cmder, bash e Power shell no terminal. Como ficar com as três opções? 

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#224]
Boa noite galera. Eu tô usando o cmder com os argumentos configurados. Como eu coloco uma opção de bash e outra opção de Powershell?

**Comment by ramonoliveiranascimento** [comment]
Estava com problemas em colocar o cmder no  vscode e andei pesquisando sobre o ocorrido.. cheguei em um tutoria ao qual falava a respeito só do cmder. 

lá continha as seguinte instruções: 

**A configuração a seguir produz um terminal Cmder padrão usando o Cmd.exe shell como se você o tivesse iniciado Cmder.exe. Eles terminal.integrated.env.windows são válidos apenas com Cmd.exeshells baseados e não terão efeito se usar Powershell ou Bash.** 

conclusão: os 3 terminais, são emulador do "cmd.exe" e utilizarão da mesma linha de raciocínio "shell" (forma de emular), como entrada para inicialização. E também o script (código ou comando), na inicialização do vscode, dentro do "settings json", tanto no powershell como no cmder são as mesmas (terminal.integrated.shell.windows) e não pode haver 2 script (código ou comando) repetidos.

sou iniciante em questão de php e vscode, não sei se tem uma solução concreta. Tentei procurar no site da Microsoft, cmder e fóruns outra linha de script (código ou comando) mas por falta de tempo não achei.

A solução que eu encontrei foi a seguinte:

Colocar como comentário o script (código ou comando), do terminal que não for utilizar e tirar do comentário o qual vai usar. Como na imagem abaixo.

![Captura de Tela 2020-09-07 às 01 11 00](https://user-images.githubusercontent.com/69820142/92507113-da8d1680-f1dc-11ea-8cb2-bed7f740fc1e.png)

Espero ter ajudado seja na solução (gambiarra) ou ter dado um norte a ser pesquisado.

site original da pesquisa: https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration

**Comment by iurygdeoliveira** [comment]
Perfeito @ramonoliveiranascimento ! Também nunca tinha vista usar três terminais ao mesmo tempo. 
Sempre utilizei apenas um mesmo, e nunca precisei de outro. No caso, usar um que atenda a todas as especificações que precisa.
