### ISSUE TITLE
Problemas no Localhost

### ISSUE THREAD

**Issue by theteustav** [iurygdeoliveira/novos_caminhos#229]
Eu fiz todo o processo de criação dos dois container através do comando `docker-composer up`, e no Localhost aparece da seguinte forma:

![ERRO_Localhost](https://user-images.githubusercontent.com/69881673/92328661-b1cc1c00-f038-11ea-8f74-e7046d2919a9.png)

**Comment by iurygdeoliveira** [comment]
@theteustav tudo bem

Coloca aqui, script do docker-compose.yml, e o arquivo default.conf dentro da pasta docker, dentro de nginx.

Ja assistiu a última aula: https://youtu.be/tII12e67TFU

**Comment by fernandoifto** [comment]
O dele esta correto ele provavelmente não criou o index.php com o conteúdo do phpinfo:

<?php
phpinfo();
?>

cria em www esse arquivo index.php que vai dar certo.

**Comment by iurygdeoliveira** [comment]
@theteustav nos dê um feedback.
