### ISSUE TITLE
DANDO ERRO NA INSTALAÇÃO DO VS CODE NO LINUX

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#231]
Boa tarde Professor Iury instalei o linux no meu compudador, mas ao istalar o vs code estar dando erro.
segue a foto com o errro e o comando.
![Captura de tela de 2020-09-06 13-12-32](https://user-images.githubusercontent.com/70108902/92332353-ffe61d00-f042-11ea-8c2c-02ad105c5500.png)

**Comment by iurygdeoliveira** [comment]
O seu comando está errado o certo é

sudo apt-get repository "deb.....

o repository está unido com apt-get
