### ISSUE TITLE
txt git config

### ISSUE THREAD

**Issue by Agenildo** [iurygdeoliveira/novos_caminhos#233]
Onde está disponível o arquivo de texto com os comandos para completar a tarefa com o git?

**Comment by daniellamlima** [comment]
@Agenildo , se for o arquivo que eu tô pensando, tem ele na pasta do repositório forkado do professor ( novos_caminhos).
Primeiro você abre a pasta Infraestrutura de Desenvolvimento e dentro dessa pasta tem a pasta 02-git onde está contido o arquivo 2.1- Tutorial do git.
Espero ter ajudado👍🏽

**Comment by iurygdeoliveira** [comment]
@Agenildo tudo bem 

E ai resolveu ?  Nos dê um feedback

**Comment by Agenildo** [comment]
Boa noite!
Sim era este arquivo que precisava.

Em seg., 7 de set. de 2020 às 20:02, Iury Gomes de Oliveira <
notifications@github.com> escreveu:
