### ISSUE TITLE
Container não funciona , Win 8 64 bits  POSITIVO 

### ISSUE THREAD

**Issue by lara1000106** [iurygdeoliveira/novos_caminhos#234]
Problemas  de  instalar  o  container   tambem  nao  tenho  conseguido  instalar o  docker  pois  o  meu  pc  e  wim 8  64  bits   nao  reconhece  os  arquivos  ,,   pelas  atividades  do  prof   da erro  quando   continuo com a localização  do container   poderiam pesquisar  pra  mim  o  deveria  fazer  .....
 ####################################################
#                          WARNING!!!!                        #
# This is a sandbox environment. Using personal credentials   #
# is HIGHLY! discouraged. Any consequences of doing so are    #
# completely the user's responsibilites.                      #
#                                                             #
# The PWD team.                                               #
###############################################################
[node1] (local) root@192.168.0.18 ~
$ cd/
bash: cd/: No such file or directory
[node1] (local) root@192.168.0.18 ~
$ cd/
bash: cd/: No such file or directory
[node1] (local) root@192.168.0.18 ~
$ mkdir landingpage
[node1] (local) root@192.168.0.18 ~
$ docker run hello-word
Unable to find image 'hello-word:latest' locally
docker: Error response from daemon: pull access denied for hello-word, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
[node1] (local) root@192.168.0.18 ~
$ hello-word
bash: hello-word: command not found
[node1] (local) root@192.168.0.18 ~
$ ^C
[node1] (local) root@192.168.0.18 ~
$ ^C
[node1] (local) root@192.168.0.18 ~
$

**Comment by lara1000106** [comment]
nao  consigo  baixar  no  terminal  o  item  6  do   script     do   wordpress     estou  errando  na  sintaxe  ???????    ,,,,, NO  TERMINAL  DOCKER  !!!!!!!!!!!!!!!!!!!!

EXECUTO  ESTE    COMANDO  FEITO  PELO  PROFESSOR  NO  VIDEO .....
$ docker run --name mywordpress1 -e WORDPRESS_DB_PASSWORD=12345678 -e WORDPRESS_DB_NAME=dbwordpress -e WORDPRESS_TABLE_PREFIX=wpLaboratorio --link some-mysql:mysql -v/landingpage;/var/www/html-dwordpress;latestweb 

"docker run" requires at least 1 argument.      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!       porque   ?????????
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
bash: /var/www/html-dwordpress: No such file or directory
bash: latestweb: command not found    !!!!!!!                      porque  ????????
[node2] (local) root@192.168.0.17 /

**Comment by iurygdeoliveira** [comment]
@lara1000106 

Esse comando **$ docker run hello-word** está faltando uma letra L é assim: **$ docker run hello-world**

**Comment by iurygdeoliveira** [comment]
@lara1000106 

Esse comando **$ cd/**, também está errado.  Falta um espaço o correto: **$ cd /**

**Comment by jalexandrersilva** [comment]
O docker tem uma sintaxe rigorosa com espaços e quando usar maiusculas e minusculas

**Comment by lara1000106** [comment]
Me. Avise.  Mais. Sobre. Os. Sintaxes. Do. Docker.  E. Muito. Importante.
Conhecer. Los. A. Propósito. Perdi.  Seu. Whatts.  Poderia. Informar. Seu.
 Número.  Novamente.   Tive. Q.  Formatar.   Meu.  Celular.     Por.
Gentileza......

Em seg, 7 de set de 2020 20:34, J Alexandre R Silva <
notifications@github.com> escreveu:

**Comment by lara1000106** [comment]
Quando. Aplico. O. Container. Do. WordPress.  Não. Consigo. Com o. Bloco.
De.  Notas.   Qual. Seria. A.  Sintaxes. Completa.  Que.  Você. Fez.  No.
Vídeo.  Não. Pra.  Pra. Ver.  Está.  Muito.   Pequeno.   Numa.  Única.
 Linha.   Pois. O. Docker.  No. Meu. Terminal.  Não.  Concluiu.  ......

Em seg, 7 de set de 2020 20:54, daniel patricio lara cabezas <
bugboundy@gmail.com> escreveu:

**Comment by jalexandrersilva** [comment]
Olhe o arquivo enunciado.pdf da prova de infraestrutura. Os comandos são grandes mesmo, pra ser num comando só, mas são assim mesmo, num comando só você tem que informar o nome do container, senha de acesso e outras informações. Existe vasta literatura na Internet sobre os comandos do docker.

Não usei o bloco de notas. Fui na pasta cmder e executei. 

É quando você liga o PC, observe que na barra de status (do lado da data e hora) e veja que o ícone do docker inicializa. 

No cmder é fácil, cada comando começa com o $ cifrão.... Vai digitando exatamente com minúsculas e maiusculas. Quando chegar no outro cifrão, há é outro comando.

Vixe digitei demais. Mas tentei ser claro. Por favor me digam se ficou algo obscuro.

**Comment by Vo-Ss** [comment]
o meu e o mesmo problema mas so com o wordpress.
##############################################################################################
[node1] (local) root@192.168.0.23 /
$ docker run --name mywordpress1 -e WORDPRESS_DB_PASSWORD=12345678 -e WORDPRESS_DB_NAME=dbwordpress -e WORDPRESS_TABLE_PREFIX=wpLaboratorio --link some-mysql:mysql - v /landingpage:/var/www/html -d wordpress:latest
docker: invalid reference format.
See 'docker run --help'.

**Comment by jalexandrersilva** [comment]
Companheiro, não é Word, a palavra é world.
Outro problema é que o - v não tem espaço, é -v junto. O - e também é junto, -e.
Tem que ser exatamente como esta no enunciado. De retorno se conseguiu ou poste novos problemas

**Comment by Vo-Ss** [comment]
Só e world com "L" o hello-world n o wordpress que eu falei. Mas os comandos sem espaço funcionou. Obrigado

**Comment by jalexandrersilva** [comment]
Legal

**Comment by iurygdeoliveira** [comment]
@Vo-Ss esse - v  deve ser junto  assim:

$ docker run --name mywordpress1 -e WORDPRESS_DB_PASSWORD=12345678 -e WORDPRESS_DB_NAME=dbwordpress -e WORDPRESS_TABLE_PREFIX=wpLaboratorio --link some-mysql:mysql **-v** /landingpage:/var/www/html -d wordpress:latest

Veja se é isso, e nos dê um feedback

**Comment by Vo-Ss** [comment]
eu ja fui respondido pelo jalexandrersilva
