### ISSUE TITLE
ERRO AO UTILIZAR O git merge upstream/master

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#235]
Professor, Boa noite, 

ao utilizar o Git merge, apareceu os erros em anexo.
![tela 1](https://user-images.githubusercontent.com/69942630/92338928-d1d7fb80-f089-11ea-95fd-8781c60afcde.JPG)
![tela 2](https://user-images.githubusercontent.com/69942630/92338929-d2709200-f089-11ea-84ee-c91005b5cd08.JPG)

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 dá um comando git remote -v 

E posta aqui o resultado, preciso confirmar algo

**Comment by L-WILIAN1987** [comment]
![erro 5](https://user-images.githubusercontent.com/69942630/92541077-6e7dd300-f21b-11ea-9153-6a7c0e43ec47.JPG)
Prof, Boa noite, segue a tela pedida.

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 tudo bem

É o seguinte, para atualizar o repositorio forkado, você deve fazer o seguinte

1: git fetch LUCAS (Você renomeou o repositório na minha conta pessoa do github como LUCAS)
2: git merge LUCAS/master

Então a branch master do repositorio remoto LUCAS, deve mesclar com a branch master do repositorio forkado

Para não causar confusão eu daria um comando

git remote rename LUCAS prof_iury

Assim ficará mais claro para você que o repositorio do prof_iury está linkado em sua máquina.

Veja se resolve, e nos dê um feedback, caso apresente outro erro, poste aqui os resultados.

**Comment by L-WILIAN1987** [comment]
![erro git merge](https://user-images.githubusercontent.com/69942630/92772449-1e655480-f372-11ea-836c-9114c4f1a10d.JPG)

ProF. Iury, Boa tarde;

fiz os comandos que me solicitou, e deu o seguinte erro no print.

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 tudo bem 

Seu repositório está com algum conflito de arquivos na mescla.

Faz o seguinte, dá um git clone do seu repositorio forkado novamente.

Acesse a pasta C:\Users\Lucas Willian

E faz:
1̣: git clone do seu repositorio forkado
2: acessar a pasta que foi criada e
3: git fetch prof_iury https://github.com/iurygdeoliveira/novos_caminhos.git
4: git merge prof_iury/master

**Comment by L-WILIAN1987** [comment]
Vou fazer aqui e te falo se deu certo.

**Comment by L-WILIAN1987** [comment]
![erro ao dar o git clone](https://user-images.githubusercontent.com/69942630/93112660-a60ed400-f68e-11ea-87f5-1d0b2c4b99fc.JPG)
Prof. Iury, Boa tarde, fui fazer um Git clone, e apareceu essa mensagem informando: 
"fatal: o caminho de destino 'novos_caminhos-1' já existe e não é um diretório vazio".

Como devo proceder agora?

Tem como excluir a pasta antiga do Git Clone?

**Comment by L-WILIAN1987** [comment]
Prof. Iury, tava olhando aqui, de ver eu usar a chave SSH, eu usei a chave HTTPS, no forcado, será que o problema seria isso?

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 tudo bem, dá problema sim.

Se você usar o clone SSH sem a chave configurada, dá problema sim.

Vamos do básico, faça tudo sem a opção do SSH, clonando a opção do HTTPS primeiros, e depois que tudo estiver funcionando e você ter compreendido melhor o processo, mudamos para a chave SSH. O que acha ?

**Comment by L-WILIAN1987** [comment]
na hora que fui fazer o Git clone, ao invés de usar a chave SSH, utilizei a HTTPS, por engano, por isso eu acho que não consigo, terminar o processo. Como faço para apagar o git clone, que fiz primeiramente.

Muito obrigado pelo retorno, Prof. Iury

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 é só deletar a pasta com tudo dentro.

**Comment by L-WILIAN1987** [comment]
a pasta que o senhor está falando é a pasta Novos caminhos?

**Comment by iurygdeoliveira** [comment]
Isso
