### ISSUE TITLE
Linux x Vscode

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#237]
Professor, eu estava realizando as atividades no windows, mas como quero atuar no mercado de trabalho resolvi baixar o linux no meu computador e instalei o Vscode nesse novo sistema. Como faço para  trazer todas as informações feitas no Vscode no Windows para linux pelo Settings Sync?

**Comment by iurygdeoliveira** [comment]
@jamilempc20 

Que legal sua decisão, será um prazer te guiar nesse inicio da carreira.

Vamos lá, a primeira coisa neste caso seria, te perguntar ?  Quando você fez as configurações no windows, você criou uma conta no github e após baixar o settings sync, você fez o upload das configurações para o github através dele ?

**Comment by jamilempc20** [comment]
Quando você fez as configurações no windows, você criou uma conta no github? Sim
e após baixar o settings sync, você fez o upload das configurações para o github através dele ? Eu instalei o Settings e não fiz upload das configurações? Como faz? Pensei que seria automático ao instalar o Setting, pois já tinha a conta github. 
Eu tenho os dois sistemas no notebbok. Como faço esse upload das configurações para Github no Windows?
