### ISSUE TITLE
acessando o localhost apos subir os contêiners via doc-compose up

### ISSUE THREAD

**Issue by AriociCarlosAmorim** [iurygdeoliveira/novos_caminhos#239]
Professor! tenho windows 10, fiz todos os passos do vídeo 6.7 e não apresentou nenhum erro, porém ao acessar o localhost aparece uma mensagem de erro: não é possível acessar o site., já até pausei o antivírus mas não aparece como demonstrado no seu vídeo.
![erro localhost](https://user-images.githubusercontent.com/70177857/92411190-34c6a280-f11d-11ea-812e-64484c539f35.PNG)

**Comment by iurygdeoliveira** [comment]
@AriociCarlosAmorim , calma meu jovem, vamos aprender a resolver isso.

Poste aqui os seguintes arquivos: docker-compose.yml
default.conf dentro da pasta nginx dentro da pasta docker.

**Comment by fernandoifto** [comment]
O meu estava igual coloquei localhost:9999 abriu a página index.php 
![Capturar](https://user-images.githubusercontent.com/8673558/92422896-6a877d80-f155-11ea-8728-eb078333af76.PNG)
![Capturar1](https://user-images.githubusercontent.com/8673558/92422924-8c810000-f155-11ea-8ed6-9b69f4eb7cc9.PNG)

`

**Comment by fernandoifto** [comment]
É algum erro na troca das portas do NGINX. no aquivo docker-compose.yml 

onde tinhamos 

ports:
            - "9999:80"


Troque para 

ports:
            - "80:80"

como tem no vídeo https://www.youtube.com/watch?v=ZSJVV2C-CzA

**Comment by jalexandrersilva** [comment]
professor @iurygdeoliveira  , agora é o meu localhost que tá dando o mesmo erro. 
Instalei o bloodshed e o gcc. e instalei o mingw também. Alguem pode me ajudar?

**Comment by jalexandrersilva** [comment]
Professor,
do limão eu fiz uma limonada.  Dentro do tutorial do docker, eu consegui resolver e saber quando preciso de uma determinada imagem numa deyerminada porta.
os comandos foram:
docker stop novos_caminhos_nginx_1

fiz um teste criando uma cópia do container
docker commit novos_caminhos_nginx_1 novos_caminhos_nginx_2

Parei o serviço que estava ativo
docker stop docker-tutorial

E tentei executar o container que dei stop
docker run -d novos_caminhos_nginx_1 -p 8080:80
deu erro,é claro

No enunciado.pdf observei que pra montar o docker precisa do nome da imagem pra montar o container

docker run -d nginx:1.19.1-alpine -p 8080:80
deu erro, claro

remontei o comando
docker run -d nginx:1.19.1-alpine -p 80:80

E rodou. Se quiser falar sobre esse ocorrido, por favor faça, será bem importante para n´s, alunos. Abraços

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva esse é o comportamento do dev. Parabens !
