### ISSUE TITLE
Erro ao realizar o GIT MERGE

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#240]
![1](https://user-images.githubusercontent.com/69942630/92413707-b1f71500-f127-11ea-8ffa-600609495fbe.JPG)

Prof. Iury, Boa tarde;

Poderia me explicar como faço para resolver, esse erro?

Eu estou tentando sincronizar os repositórios.

**Comment by jalexandrersilva** [comment]
Olá colega. Olha só, na issue #221 eu estava com um problema parecido.

Depois que vi o vídeo 6.8 novamente, eu percebi os erros que estava cometendo. Dando uma olhada lá e vendo como o professor orientou, consegui solução. A grande parada é quando você dá um git check-out nomebranch e mescla com outra. Na postagem final tem isso. Mas como te falei, veja primeiro o vídeo 6.8 que você consegue. Comece como o professor orientou na #221 e dê um git remote - v. Comece por aí. Qualquer coisa poste aqui

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 depois da dica do @jalexandrersilva , me dá um feedback se resolveu.

**Comment by L-WILIAN1987** [comment]
Vou fazer os comandos aqui e informo para vocês.

**Comment by L-WILIAN1987** [comment]
![erro 5](https://user-images.githubusercontent.com/69942630/92542082-34620080-f21e-11ea-964f-ba57dd4dc266.JPG)

Boa noite, Prof. Iury, fiz o git remote -v, e apareceu essa mensagem que está no print.

Vou fazer os comandos que o amigo de curso, me falou e vou ver se da certo e lhe informo.

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 ok, mas acho que te respondi isso na issue #235 

Verifique e nos dê um feedback
