### ISSUE TITLE
Dúvida sobre os repositórios

### ISSUE THREAD

**Issue by ghost** [iurygdeoliveira/novos_caminhos#241]
Boa tarde, professor. Todos os repositórios que eu tenho são sempre públicos? Qualquer pessoa pode fazer um fork deles e editá-los?

**Comment by ovatsugbp** [comment]
quando você cria o repositório vc escolhe se ele é publico ou privado

**Comment by iurygdeoliveira** [comment]
Olá @alinealine1 , é exatamenteo como o @ovatsugbp falou.
