### ISSUE TITLE
Cmder não reconhece Vscode no windows 10

### ISSUE THREAD

**Issue by k-js** [iurygdeoliveira/novos_caminhos#244]
![Anotação 2020-09-08 111308](https://user-images.githubusercontent.com/70825783/92488552-174d1380-f1c5-11ea-88ae-8d5c8db8f86f.png)

**Comment by jalexandrersilva** [comment]
olá bom dia galera.
colega, tive o mesmo problema. Digite ctrl shift P digite settings e abra o Open settings (JSON)
Abaixo dessa linha do cmd cole isso aqui...

    "terminal.integrated.shellArgs.windows": [
        "/K",
        "C:\\cmder\\vendor\\bin\\vscode_init.cmd"
    ]

Salve as configurações e faça um teste. Se não funcionar, reinicie o vscode. Lembre-se que o prof. Iury falou que a endentação é muito importante no vscode, ou seja, olhe que é dado uns espaços antes de começar o comando  que segue o padrão da linha anterior. Por favor retorne se conseguiu resolver.

Abraços.

**Comment by iurygdeoliveira** [comment]
@k-js , olá tudo bem ?

Com as explicações do @jalexandrersilva , você resolveu os problemas ?
