### ISSUE TITLE
provas 

### ISSUE THREAD

**Issue by gabrielalves-bit** [iurygdeoliveira/novos_caminhos#245]
não pode haver erros ? se errar oque eu devo fazer ?

**Comment by fernandoifto** [comment]
Pelo que o Iury deu a entender para ser aprovado tem que tirar no mínimo 6.

**Comment by jalexandrersilva** [comment]
Gente, tem que relaxar. O play docker é ia ferramenta que você pode testar quantas vezes quiser. Antes de fazer a prova, faça os comandos, pesquise materiais legais sobre comandos básicos do docker. Não tem como errar. Tente brincar com o play docker uns 3vdias refazendo o enunciado da prova. A gente consegue. Dúvidas, pista aqui, blz?

**Comment by danimendesb** [comment]
Só a uma tentativa, mas não tem limite de tempo para tentar realizar.

**Comment by iurygdeoliveira** [comment]
@danimendesb isso mesmo, na prova, você pode realizar ela apenas uma única vez. Se clicar em enviar, não pode fazer novamente.

Agora no play docker, você pode refazer os comandos quando quiser, e repetir quantas vezes quiser.
