### ISSUE TITLE
Problema na extensão docker para VSCode

### ISSUE THREAD

**Issue by FernandoNoleto** [iurygdeoliveira/novos_caminhos#246]
Quando abro a extensão do docker no meu vscode, ele não consegue ler minhas imagens e containers. Acredito que seja por que o vscode não ter permissão de acesso. Alguém sabe como resolver?

Uso elementary OS.

![Captura de tela de 2020-09-08 18-39-43](https://user-images.githubusercontent.com/22261074/92530796-703b9c80-f203-11ea-8cc6-b9f7ea843e49.png)

![Captura de tela de 2020-09-08 18-40-07](https://user-images.githubusercontent.com/22261074/92530807-76317d80-f203-11ea-9853-2d626f382ff9.png)

**Comment by DerreckMarques** [comment]
@FernandoNoleto tem essa issue que deu certo no meu pc: #223
