### ISSUE TITLE
Dificuldade no git - não consigo subir minha contribuição

### ISSUE THREAD

**Issue by joaogeraldo-dancer** [iurygdeoliveira/novos_caminhos#248]
boa noite, pessoal. No meu git eu fiz o fork via http, pois a ssh não estava entrando, depois que consegui configurar o ssh. Fiz o meu arquivo de contribuição, mas não consigo subir ele. Será que é por eu fiz o fork http e deveria faze-lo pelo ssh?

**Comment by k-js** [comment]
ESTOU CM MESMO PROBLEMA .

**Comment by DerreckMarques** [comment]
Bom dia @joaogeraldo-dancer.
Depois que fizer a contribuição, você dever subir as mudanças para o seu github.
Em seguida faça um pull request para o repositório do professor
essa issue pode ajudar: #93

**Comment by iurygdeoliveira** [comment]
@joaogeraldo-dancer tudo bem, a resposta do @DerreckMarques está na direção correta.

Lembrando que quando você faz um clone usando via http, e depois consegue configurar o ssh. Então, tudo passa a funcionar via ssh, é preciso apenas reconfigurar o endereço usando o git remote
