### ISSUE TITLE
WINDOWNS//Error ao executar Compose UP.

### ISSUE THREAD

**Issue by neto009** [iurygdeoliveira/novos_caminhos#249]
Como indicado na vídeo aula: https://www.youtube.com/watch?v=tII12e67TFU&feature=youtu.be
contudo, ao dar compose up no arquivo docker-compose.yml no visual code, apresenta o seguinte error no terminal.

![Error](https://user-images.githubusercontent.com/35355371/92546677-7b092800-f229-11ea-8454-d5ac84da1c95.jpg)

**Comment by iurygdeoliveira** [comment]
@neto009 tudo bem 

De acordo com a tela de erro apresentada

Você precisa atualizar a configuração de compartilhamento de arquivos em seu aplicativo Docker para Windows (há um novo reforço de segurança em 2.2.0.0 que tem padrões agressivos). Adicione todas as pastas necessárias e reinicie o Docker para Windows.  Esse seu erro é algo bem especifico, nunca tinha visto.

![image](https://user-images.githubusercontent.com/30157522/92662876-34253c00-f2d6-11ea-9720-a9655daad8eb.png)

Veja se resolve

**Comment by neto009** [comment]
Solução perfeita professor. Agradeço.
![Soluçao 2](https://user-images.githubusercontent.com/35355371/92665960-486d3700-f2de-11ea-9a8a-b8e7cb460dcd.jpg)

**Comment by iurygdeoliveira** [comment]
@neto009 maravilha !
