### ISSUE TITLE
Dúvida sobre pastas e arquivos (Docker)

### ISSUE THREAD

**Issue by Dfftst** [iurygdeoliveira/novos_caminhos#251]
![Screenshot_1](https://user-images.githubusercontent.com/70779511/92588857-02798a00-f270-11ea-827f-fede6b5d4abf.png)

Bom dia Professor Iury, pode me ajudar com essa dúvida?

**Comment by fernandoifto** [comment]
Você pode clonar ou pode criar as pastas e aquivos e copiar o conteudo ou pesquisar outras formas de fazer a mesma configuração. mais recomendado é clonar o projeto.

**Comment by iurygdeoliveira** [comment]
@Dfftst foram as pastas criadas por mim, e repassadas para você, através do github.

Quando você fez a atualizando do seu repositorio, o download das pastas foi feito.
