### ISSUE TITLE
Problema na instalação do Docker composer.

### ISSUE THREAD

**Issue by chan455** [iurygdeoliveira/novos_caminhos#253]
Pulling nginx (nginx:1.19.1-alpine)...
1.19.1-alpine: Pulling from library/nginx
cbdbe7a5bc2a: Pull complete
85434292d1cb: Pull complete
75fcb1e58684: Pull complete
2a8fe5451faf: Pull complete
42ceeab04dd4: Pull complete
Digest: sha256:ee8c35a6944eb3cc415cd4cbeddef13927895d4ffa50b976886e3abe48b3f35a
Status: Downloaded newer image for nginx:1.19.1-alpine
Creating novoscaminhos_php_1 ... error

ERROR: for novoscaminhos_php_1  Cannot create container for service php: invalid volume specification: '/home/laercio-lopes/Novos Caminhos/docker.php/php.ini:usr/local/etc/php/php.ini:rw': invalid mount config for type "bind": invalid mount path: 'usr/local/etc/php/php.ini' mount path must be absolute

ERROR: for php  Cannot create container for service php: invalid volume specification: '/home/laercio-lopes/Novos Caminhos/docker.php/php.ini:usr/local/etc/php/php.ini:rw': invalid mount config for type "bind": invalid mount path: 'usr/local/etc/php/php.ini' mount path must be absolute
ERROR: Encountered errors while bringing up the project.

Iury, estava tudo indo bem quando apareceu esta mensagem de erro.

**Comment by chan455** [comment]
Resolvido! O meu comando no arquivo docker composer.yml estava copiado de forma errada e estavam faltando 2 pontos e barras.
Desde já agradecido.

**Comment by iurygdeoliveira** [comment]
@chan455 Blz ! Prossigamos !
