### ISSUE TITLE
VSCode e C++

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#254]
professor @iurygdeoliveira, posso usar o vscode com o c++? ele tem como compilar também dentro do vscode?

Tem algum material que eu possa usar como referência?

**Comment by tsartori** [comment]
É possível sim, vc só precisa instalar o compilador C/C++, inclusive tem o compilador disponibilizado pela própria Microsoft.

![c++ microsoft](https://user-images.githubusercontent.com/21146217/92640903-59a14e00-f2b4-11ea-8360-f44c823c8bdb.png)

**Comment by jalexandrersilva** [comment]
Professor @iurygdeoliveira o que estou fazendo errado?

![atv_prog_web](https://user-images.githubusercontent.com/69798042/92653997-8ad64a00-f2c5-11ea-9290-ab167c75ed69.png)

**Comment by tsartori** [comment]
[Solucao encontrada no Google](https://github.com/microsoft/vscode-cpptools/issues/1863)

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva eu não sei o que acontece. Nunca programei use o VSCODE para programar em C++
