### ISSUE TITLE
VsCode x Linux

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#257]
Professor, ainda sobre as configurações do VsCode. Respondendo sua pergunta abaixo.
Quando você fez as configurações no windows, você criou uma conta no github? Sim

E após baixar o settings sync, você fez o upload das configurações para o github através dele ? 
Eu instalei o Settings e não fiz upload das configurações. Como faz? Pensei que seria automático ao instalar o Setting, pois já tinha a conta github.
Eu tenho os dois sistemas no notebbok. Como faço esse upload das configurações para Github no Windows?

**Comment by iurygdeoliveira** [comment]
@jamilempc20 vou gravar um vídeo mostrando, essa suda dúvida, pode ser a de muitos outros alunos.

**Comment by iurygdeoliveira** [comment]
Vou postar um link aqui, apenas para complementar, para que outros alunos possam ver

https://medium.com/gummaoficial/sincronizando-as-configura%C3%A7%C3%B5es-do-vscode-entre-diferentes-computadores-c543e3036cb5

**Comment by rafabritu** [comment]
Tive que formatar meu pc e na hora de instalar o vscode, tive dificuldades em fazer o settings sync funcionar. Mas eu tambem tinha usado um sincronizador do próprio vscode. Não sei bem qual deles baixou minhas configurações, mas está tudo como antes.

**Comment by iurygdeoliveira** [comment]
@rafabritu legal !
