### ISSUE TITLE
-> RESOLUÇÃO: COMO USAR O TEMINAL POWERSHELL E CMDER DENTRO DO VSCODE?

### ISSUE THREAD

**Issue by ramonoliveiranascimento** [iurygdeoliveira/novos_caminhos#258]
Olá, galera!

Segue a resolução definitiva de como usar os terminais powershell e cmd, juntos ou intercalados.

Dentro do arquivo settings.json no vscode, copie e coloque as seguintes chaves de comandos:

"terminal.external.windowsExec": " C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": [
        "/k",
        "%CMDER_ROOT%\\vendor\\init.bat"
    ],

![Captura de Tela 2020-09-09 às 23 39 36](https://user-images.githubusercontent.com/69820142/92678218-de638a80-f2fb-11ea-8b41-f3f8ce4c7272.png)

EXPLICAÇÃO: 

A chave "terminal.external.windowsExec": faz com que o terminal definido (tem que direcionar para pasta do .exe), seja executado ao chamar pelo nome dentro do vscode.

Já o resto faz o direcionamento para o cmder "Basicamente isso".
(Pois é muito complexo explicar o passo a passo, correto).

Lembrando que mesmo tendo as chaves de comando configuradas dentro do settings.json no vscode, para usar o cmder no vscode, também é preciso ter as seguintes configurações no sistema do Windows.

As mesmas podem serem vistas aqui: https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration

COMO USAR:

Ao abrir o vscode, o terminal a ser executado como principal será cmder.
(na caixinha de verificação ou escolha vai estar como "cmd", mas ignorem isso. Complexo explicar.)

![Captura de Tela 2020-09-10 às 00 37 43](https://user-images.githubusercontent.com/69820142/92679161-0bb13800-f2fe-11ea-8db3-5b05d9f99149.png)

Caso queira usar o powershell, só digitar o nome do mesmo e ele vai substituir o cmder.

![Captura de Tela 2020-09-10 às 00 43 05](https://user-images.githubusercontent.com/69820142/92679396-b1fd3d80-f2fe-11ea-95df-92e53be46fdc.png)

Agora para usar os dois juntos é só utilizar a opção "Split Terminal" do menu Terminal e após abri digite o nome, powershell.

![Captura de Tela 2020-09-10 às 01 01 37](https://user-images.githubusercontent.com/69820142/92680789-2c7b8c80-f302-11ea-9520-168f33770e81.png)

Também tem a possibilidade utilizar separados. Indo em "new terminal" no menu Terminal. Abrindo o novo terminal só digitar o nome powershell.

![Captura de Tela 2020-09-10 às 01 05 35](https://user-images.githubusercontent.com/69820142/92681121-2afe9400-f303-11ea-834c-52481a801ab7.png)

referências:

Configurações cmder: https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration

Documentação vscode: https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

**Comment by iurygdeoliveira** [comment]
@ramonoliveiranascimento parabens ! show de bola !!
