### ISSUE TITLE
erro docker

### ISSUE THREAD

**Issue by luisdalmeida** [iurygdeoliveira/novos_caminhos#259]
boa noite ao tentar instalar o docker pelo cmder estou no diretorio C:/xampp/htdocs/novos_caminhos (develop)
no meu terminal não aparece o (master forkado)  igual o seu., aparece (develope)
e quando eu dou o comando docker ele lista um monte de opsão de comando
e se eu tento dar o comando docker compose up fala que não e valido o que eu faço??
obrigado pela atenção.

**Comment by iurygdeoliveira** [comment]
@luisdalmeida pode postar os prints da tela, preciso ter uma noção mais precisa do que acontece
