### ISSUE TITLE
Sobre Branch

### ISSUE THREAD

**Issue by DiegoVmg** [iurygdeoliveira/novos_caminhos#261]
Bom dia! professor; O que se quer dizer quando se diz que foi criada uma nova branch e que essa branch que foi crianda está baseada em uma outa?

grato!

**Comment by tsartori** [comment]
Assista a essa aula no [YouTube](https://www.youtube.com/watch?v=xAOBQtSVI_k&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&index=12&ab_channel=CursoemV%C3%ADdeo), vai te ajudar bastante

**Comment by jalexandrersilva** [comment]
Olá, especificamente os vídeos 6.8 e 7.1

Olha, o professor pode explicar melhor mas com a instalação do gi Flow teremos algumas branchs importantes. 
São elas:
A develop que é onde vamos trabalhar
A master, de onde serão dados do repositório local espelho do repositório do professor 
Comando git pull

É depois você atualiza seu repositório forjado no github
Comando git push

Depois disso vem o trabalho com as branchs. Assiste vídeo 6.8 e 7.1 que está tudo claro. Se tiver dúvidas poste aqui beleza?

**Comment by jalexandrersilva** [comment]
E ai colega? conseguiu desenvolver a dúvida?
