### ISSUE TITLE
ERRO - 'flow/' does not have a commit checked out

### ISSUE THREAD

**Issue by DiegoVmg** [iurygdeoliveira/novos_caminhos#262]
![Screenshot_2](https://user-images.githubusercontent.com/69961712/92717196-3323f700-f336-11ea-849d-bdd5912beb79.png)

Professor porque está dando esse erro?

**Comment by iurygdeoliveira** [comment]
Olá @DiegoVmg 

O que acontece acontece quando você digita ls -ltr dentro do repositório. Estou achando que existe duas pastas .git em seu repositorio.

**Comment by DiegoVmg** [comment]
Bom dia Professor Iury, realmente tinha duas pastas git.

Refiz o processo e deu tudo certo.

Obrigado.

**Comment by iurygdeoliveira** [comment]
@DiegoVmg  Blz !
