### ISSUE TITLE
duvida Docker container wordpress 1

### ISSUE THREAD

**Issue by Luizedcarvalho** [iurygdeoliveira/novos_caminhos#263]
professor não estou conseguindo executar o comando para subir o container wordpress 1, sempre dá comando invalido

**Comment by jalexandrersilva** [comment]
olá colega de curso. Olha só, se diz que o comando é inválido, você deve estar digitando algum comando inválido. A sintaxe dos comandos do docker são muito específicas. Você pode postar um print de tela do comando que está executando?

Mande também um printscreen do comando docker ps -a

Beleza?

**Comment by Luizedcarvalho** [comment]
deu certo aqui, era o que tu disse, erro na digitação

**Comment by jalexandrersilva** [comment]
Valeu colega. Tmj. Ptof @iurygdeoliveira favor fechar issue #263

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva valeu !

@Luizedcarvalho que bom que resolveu !
