### ISSUE TITLE
Erro ao tentar Subir o Container LOAD BALANCER HAPROXY

### ISSUE THREAD

**Issue by joaops2001** [iurygdeoliveira/novos_caminhos#265]
$ docker run -d --name HaproxyLB -p 8080:80 -e BALANCE=source -e MODE=tcp -e OPTION=tcplog --link mywordpress1:mywordpress1 --link mywordpress2:mywordpress2 dockercloud/haproxy
Unable to find image 'dockercloud/haproxy:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/dockercloud/haproxy/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Adockercloud%2Fhaproxy%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

**Comment by joaops2001** [comment]
Tentei novamente e consegui, aparentemente foi um erro do servidor

**Comment by iurygdeoliveira** [comment]
@joaops2001 legal !
