### ISSUE TITLE
Acesso APIs externas

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#267]
Olá galera e prof @iurygdeoliveira 

Professor, uma coisa que vem me dando vontade de saber é o seguinte

O magazine Luiza é outras lojas on line têm seus APIs para acesso por outros aplicativos

Pegando como exemplo esse link [API](https://magazineluiza.docs.apiary.io/)  é outros exemplos que julgue legais pra gente aprender o senhor pode nos dar um norte para ter acesso? Pode explicar como funciona?

Eu sei que é um assunto complexo, mas podemos começar os estudos?

**Comment by jalexandrersilva** [comment]
Professor eu juro que escrevi essa dúvida sem ver o vídeo 7.2 mas agora vejo que a minha pergunta é pertinente. Espero que este curso seja muito produtivo para todos nós muito obrigado por tudo e espero seu retorno

**Comment by iurygdeoliveira** [comment]
Olá @jalexandrersilva sua pergunta é pertinente sim. Esse é principal trabalho do back-end developer, linkar aplicações diferentes por meio de APIs.  Nós vamos estudar isso de forma mais prática, mais adiante.

Linguagens como PHP, NodeJS, Java, Python, possuem forte foco, em linkagem de app diferentes por meio de apis !
Você começa a perceber que na verdade, quando requisitamos um site, o que acontece é um navegador web, requisitando de uma API, que devolve uma pagina html !

**Comment by jalexandrersilva** [comment]
Fantástico. Agradeço
