### ISSUE TITLE
Dúvida em relação a instalação do Docker, na versão do Windows

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#268]
![mensagem de erro instalação docker](https://user-images.githubusercontent.com/69942630/92801914-6abd8e00-f38c-11ea-9ac1-f18a947b32e3.JPG)
![versão do windows](https://user-images.githubusercontent.com/69942630/92802007-83c63f00-f38c-11ea-8b5b-62de2cce18ea.JPG)
Prof. Iury, Boa noite
Ao realizar a instalação do programa Docker, apareceu mensagem de erro (print). O meu Windows, é o Windows home versão 1903, no qual da certo com a instalação do programa.

Pesquisei na Web, e fiquei em dívida em qual procedimento utilizar. Poderia me dizer como devo proceder, para corrigir esse erro?

**Comment by fernandoifto** [comment]
Dar uma olhada nessa Issues https://github.com/iurygdeoliveira/novos_caminhos/issues/201

**Comment by JohnnyfWSilva** [comment]
https://www.microsoft.com/pt-br/software-download/windows10

Vai nesse link, clica em "Atualizar agora". Vai baixar um instalador. Você abre e inicia a att. Pode demorar um pouco. No meu demorou umas 3 horas. Depois que terminar a att, você reinicia e pronto. Depois é só iniciar a instalação do Docker normalmente.

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 nos dê um feedback se com a dica do @JohnnyfWSilva deu certo

**Comment by L-WILIAN1987** [comment]
Já deu certo, Prof. Iury. Muito obrigado a todos pelas dicas.
