### ISSUE TITLE
Erro ao abrir o Live Server

### ISSUE THREAD

**Issue by ovatsugbp** [iurygdeoliveira/novos_caminhos#269]
Boa noite professor, ao tentar entrar pelo live server ele me retorna esse erro 
![image](https://user-images.githubusercontent.com/68348319/92828149-1674d700-f3a9-11ea-8cc0-1e448d49b8ba.png)

**Comment by iurygdeoliveira** [comment]
Olá @ovatsugbp , este erro deve ser relativo em alguma configuração de porta.

Os containers estão ativos ?
Qual porta está configurada no docker-compose.yml ?
Qual a configuração do liveserver no settings.json ?

**Comment by ovatsugbp** [comment]
então, eu desativei os containers pra não consumir muito recurso da minha maquina porém esse erro apareceu em outro projeto que estou trabalhando. Não deveria acontecer esse tipo de comportamento, certo? ou eu tenho que deixar os containers ativados mesmo quando não estou trabalhando diretamente com eles?
a configuração do liveserver ta igual a que vc orientou 
![image](https://user-images.githubusercontent.com/68348319/93025997-05121180-f5d9-11ea-872a-2ff54694d744.png)

a porta do docker compose também está igual, acredito eu
![image](https://user-images.githubusercontent.com/68348319/93026020-3ab6fa80-f5d9-11ea-808a-e89185caa0f7.png)

**Comment by iurygdeoliveira** [comment]
@ovatsugbp tudo bem, a configuração está correta.

como você está trabalhando em outro projeto, não vai funcionar. Será necessário você criar outros containers para este projeto especifico. E pelo jeito, parece que você está usando python.

Aqui esses containers são compilados e criados especificos para rodar o PHP.
