### ISSUE TITLE
Tem como conseguir domínio gratuito?

### ISSUE THREAD

**Issue by eufelipeigor** [iurygdeoliveira/novos_caminhos#270]
Bom dia a todos!

Tem alguma forma de conseguir domínio gratuito? Ex: meudominio.com; meudominio.com.br; meudominio.net; meudominio.br;

Agradecido desde já,

**Comment by FernandoNoleto** [comment]
Não, porém o github permite você hospedar um site com o domínio "nomedeusuario.github.io/nomedorepositorio/". Eu tenho um site hospedado no git: https://fernandonoleto.github.io/janainayonadesigner/

**Comment by ovatsugbp** [comment]
pra hospedar sites estáticos no azure é de graça

**Comment by rafabritu** [comment]
Domínio só tem comprado, mas existem domínios bem baratinhos na godaddy, comprei um www.seudominio.site   por 8,90 por um ano, sai praticamente de graça

**Comment by eufelipeigor** [comment]
> Domínio só tem comprado, mas existem domínios bem baratinhos na godaddy, comprei um [www.seudominio.site](http://www.seudominio.site) por 8,90 por um ano, sai praticamente de graça.
> Depois de comprado você consegue direciona-lo pra qualquer link, como instagram, repositório, ou ip específico.

Muito obrigado por ajudar, acredito que essa foi a melhor resposta.

**Comment by iurygdeoliveira** [comment]
> Não, porém o github permite você hospedar um site com o domínio "nomedeusuario.github.io/nomedorepositorio/". Eu tenho um site hospedado no git: https://fernandonoleto.github.io/janainayonadesigner/

Gostei do seu site @FernandoNoleto !
