### ISSUE TITLE
Erro Comando compose up - Docker 

### ISSUE THREAD

**Issue by mgckaled** [iurygdeoliveira/novos_caminhos#271]
Quando executo o comando o comando compose up depois de clicar o botão direito no arquivo docker-compose.yml ocorre o seguinte erro:

![Screenshot_4](https://user-images.githubusercontent.com/58960702/92961615-eb8c9080-f445-11ea-9d41-0c78ac8148fe.jpg)

Porém, quando executo o comando `docker-compose up` pelo terminal na raiz da pasta, os containers são montados.
Poderiam me ajudar?

**Comment by iurygdeoliveira** [comment]
@mgckaled tudo bem, me parece que tem duas tarefas paralelas do docker, sendo utilizadas ao mesmo tempo.
