### ISSUE TITLE
Erro comando compose up - Docker 

### ISSUE THREAD

**Issue by mgckaled** [iurygdeoliveira/novos_caminhos#272]
Quando executei o comando o "compose up" depois de clicar com o botão direito no arquivo docker-compose.yml no VS Code ocorreu o seguinte erro:

![Screenshot_4](https://user-images.githubusercontent.com/58960702/92961615-eb8c9080-f445-11ea-9d41-0c78ac8148fe.jpg)

De toda forma, quando executei o comando `docker-compose up` pelo terminal na raiz da pasta, os containers foram montados com sucesso.

![Screenshot_5](https://user-images.githubusercontent.com/58960702/92962697-b719d400-f447-11ea-8eea-e9bf571c9662.jpg)

Logo, consegui acessar o ambiente conforme sua demonstração (imagem abaixo) , porém somente através do terminal  (imagem acima) e digitando "localhost:9999" no endereço do browser. 
Além disso, não alterei as configurações do Live Server, pois fiquei com receio de limitar as configurações desse recurso para outros projetos. Professor @iurygdeoliveira, você vê algum problema em manter os trabalhos desta forma?

![Screenshot_6](https://user-images.githubusercontent.com/58960702/92963897-92bef700-f449-11ea-931b-481b65763d04.jpg)

**Comment by fernandoifto** [comment]
Você pode mudar a porta dento do arquivo docker-compose.yml 
Esta assim 
`ports:
            - "9999:80"`
Mude e deixe assim caso não queira digita a porta depois do localhost
`ports:
            - "80:80"`

**Comment by iurygdeoliveira** [comment]
@mgckaled tudo bem, não vejo problemas em manter a configuração que você sugeriu. O mais importante é você como DEV ter o dominio da sua máquina, saber como as coias estão funcionando, alterar como quiser, quem controla a máquina é você.

A sugestão do @fernandoifto  é legal, também. Mas fique a vontade para deixar como quiser.
