### ISSUE TITLE
Git log --pretty: Invalid object error

### ISSUE THREAD

**Issue by JohnnyfWSilva** [iurygdeoliveira/novos_caminhos#273]
Sempre que tento usar o "git log --pretty=format: "%h - %an, %ar : %s" (vídeo 5.2), recebo esse belíssimo erro.

![image](https://user-images.githubusercontent.com/70163346/92971824-8e013f80-f457-11ea-9d47-e8da979fa491.png)

**Comment by iurygdeoliveira** [comment]
Olá @JohnnyfWSilva tudo bem

Retira esse espaço entre o format: "%h

deixando assim **git log --pretty=format:"%h - %an, %ar : %s"**

Acredito que esse é o erro.
