### ISSUE TITLE
Dificuldade subir contribuição #2

### ISSUE THREAD

**Issue by joaogeraldo-dancer** [iurygdeoliveira/novos_caminhos#276]
Boa noite, pessoal. Ainda na dificuldade da contribuição.... não consigo subir a primeira contribuição...

~/Projetos/Novos Caminhos Programador Web$ git push novos_caminhos master 
To novos_caminhos
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'novos_caminhos'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by iurygdeoliveira** [comment]
@joaogeraldo-dancer tudo bem.

O git está indicando que você necessita fazer um git pull, antes de realizar um git push.

Lembre-se que sua contribuição é feita para o seu repositório forkado, e de lá, você realiza um pull request para a minha conta.

Assistiu os vídeos ? Está tudo bem explicadinho

**Comment by joaogeraldo-dancer** [comment]
obd! assisti todos os vídeos várias vezes! mas ainda tem alguma coisinha que não esta indo...

**Comment by iurygdeoliveira** [comment]
O que acontece quando voçê dá o comando git pull

**Comment by joaogeraldo-dancer** [comment]
aparece essa mensagem:

remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 29 (delta 16), reused 23 (delta 12), pack-reused 0
Unpacking objects: 100% (29/29), 3.88 KiB | 137.00 KiB/s, done.
From https://github.com/iurygdeoliveira/novos_caminhos
   8cdb145..542678d  master     -> origin/master
fatal: refusing to merge unrelated histories

**Comment by iurygdeoliveira** [comment]
@joaogeraldo-dancer da um comando git remote -v em seu repositório é poste aqui o resultado.

**Comment by joaogeraldo-dancer** [comment]
Novos-Caminhos-Programador-Web  https://github.com/joaogeraldo-dancer/Novos-Caminhos-Programador-Web.git (fetch)
Novos-Caminhos-Programador-Web  https://github.com/joaogeraldo-dancer/Novos-Caminhos-Programador-Web.git (push)
master  https://github.com/joaogeraldo-dancer/Novos-Caminhos-Programador-Web.git (fetch)
master  https://github.com/joaogeraldo-dancer/Novos-Caminhos-Programador-Web.git (push)
origin  https://github.com/joaogeraldo-dancer/Novos-Caminhos-Programador-Web.git (fetch)
origin  https://github.com/joaogeraldo-dancer/Novos-Caminhos-Programador-Web.git (push)

**Comment by iurygdeoliveira** [comment]
@joaogeraldo-dancer tudo bem, existe 3 endereços linkados para o mesmo repositório.

Não precisa disso tudo, precisamos apenas linkar uma vez apenas.

Acessei sua conta, e verifiquei que vc fez o fork do repositório novos_caminhos, mas o link correto é: https://github.com/joaogeraldo-dancer/novos_caminhos.git

Você está linkando com um outro repositório que provavelmente você deve ter criado:

Para deixarmos tudo correto faça o seguinte no linux:
 1) Acesse a pasta onde está o seu repositório: cd ~/Projetos/Novos Caminhos Programador Web
2) git remote remove Novos-Caminhos-Programador-Web
3) git remote remove master
4) git remote remove origin
5) git remote add forkado https://github.com/joaogeraldo-dancer/novos_caminhos.git

Isso deve organizar seus repositórios remotos
E ao dar o git pull, ele deve solicitar o usuario e senha do github, ai basta você adicionar.
