### ISSUE TITLE
ATUALIZAÇAO DO REPOSITORIO FOKADO, DO MEU GITHUB.

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#277]
1. BOM DIA, TARDE e  NOITE, estou com uma duvida, sempre que vou baixar a nova atualização do github, antes estou apagando tudo que já tem no meu vscode, dai faço um novo clone com as atualizações, essa é a forma correta?

 2. Quando vou subir essas atualizações pro meu gitthub, não estão subindo, fiz, o "git add ." "git commit -m" "git push "com o ssh," e mesmo assim não deu certo.

**Comment by iurygdeoliveira** [comment]
Olá @josepereirakls , tudo bem 

1. Não essa não é a forma correta. Dá uma olhada na issue #187 

2. Qual o erro está aparecendo, poste aqui os resultados
