### ISSUE TITLE
como definir um executàvel PHP?

### ISSUE THREAD

**Issue by Marcelolm777** [iurygdeoliveira/novos_caminhos#278]
Estou com dificuldades em trabalhar com o git hub sigo os passo a passos mas não estou conseguindo  evoluir. ( Não é possível validar porque nenhum executável PHP está definido. Use a configuração 'php.validate.executablePath' para configurar o executável do PHP.) acredito que esse seja o problema.

**Comment by rhph003** [comment]
tive o mesmo problema pra resolvê-lo.1- vai no settings(json) 2-vai "php.validate.executablePath": "C:\xampp\php\php.exe". 4-
coloca assim: "C:\\xampp\\php\\php.exe",espero ter ajudado

**Comment by iurygdeoliveira** [comment]
@Marcelolm777 e ai, resolveu com a dica do @rhph003 

Nos dê um feedback ...

**Comment by iurygdeoliveira** [comment]
@clelianidecdasilva acho que esse é o mesmo problema que o seu.
