### ISSUE TITLE
erro na atividade 8

### ISSUE THREAD

**Issue by Luizedcarvalho** [iurygdeoliveira/novos_caminhos#279]
realizei as atividades toas até a 8°, no entanto não aparece a pasta novos caminhos no meu vs code, aparece as contribuições de alguns colegas,  já refiz o git clone e nada, o que pode ser ?

**Comment by fernandoifto** [comment]
Envie o print da tela clicando no local indicado na imagem.
![Captura de tela de 2020-09-12 11-07-52](https://user-images.githubusercontent.com/8673558/92997301-a8372e00-f4e8-11ea-928a-b036fdd9c66c.png)

**Comment by Luizedcarvalho** [comment]
![2020-09-11](https://user-images.githubusercontent.com/70111956/92998581-e33d5f80-f4f0-11ea-94c3-728cf49a6c5c.png)

**Comment by Luizedcarvalho** [comment]
criei essa pasta novos caminhos araguai........no inicio do curso, lá no htdocs igual o professor disse. depois fiz o git clone, mas estão vazias e estou apanhando legal kkkkkk

**Comment by jalexandrersilva** [comment]
Bom dia. Colega, algumas vezes eu também apaguei a pasta. Você deve ter esquecido o primeiro comando depois de criar e selecionar a pasta pelo vscode

Git ini

Você deu esse comando?
Lbre depois você precisa adicionar o upstream que é o repositório do prof. E também o comando git Flow init pra trabalhar com as branchs de desenvolvimento. 

Se der certo avise aí ok? 👍👍

**Comment by Luizedcarvalho** [comment]
não criei essa pasta pelo  vscode não

**Comment by Luizedcarvalho** [comment]
conta no github está ok
repositorio forkado  ok

**Comment by iurygdeoliveira** [comment]
@Luizedcarvalho tudo certo então ?

**Comment by Luizedcarvalho** [comment]
@iurygdeoliveira não estou conseguindo inicializar a atividade 8, fiz confusão com o conteúdo eu acho, como faço para organizar essas pastas ?

**Comment by iurygdeoliveira** [comment]
@Luizedcarvalho tudo bem, basta você atualizar o seu repositório, seguindo os passos na issue #102 

Está passo está demonstrado também nas vídeos aulas.
