### ISSUE TITLE
Como fechar terminal quando subir os containers?

### ISSUE THREAD

**Issue by eufelipeigor** [iurygdeoliveira/novos_caminhos#281]
Boa tarde! 

Pessoal estou com uma dúvida quanto ao terminal, pois subi os conatainers, mas o código não parou a execução, já faz mais de 24h.  Segue print abaixo:

![Comandos](https://user-images.githubusercontent.com/70045634/93002369-e9413980-f50c-11ea-93f6-05574e9b2666.png)

Quando clico no botão de fechar, ele me dá a pergunta se quero parar a execução do comando, vejam o print por favor: 

![Perungta](https://user-images.githubusercontent.com/70045634/93002397-27d6f400-f50d-11ea-8736-5650e6f16fd4.png)

E o que ocorre se eu fechar?

**Comment by iurygdeoliveira** [comment]
@eufelipeigor tudo bem.

Se você fechar o terminal dessa forma, os containers serão desligados também. Pois eles estão executando em 1º plano, essa forma de execução é boa, para se ter as seguintes percepções: 

- Se os containers estão ligados
- Qual erro está acontecendo em alguma requisição nos containers
- Se algum container está em estado down.

A desvantagem é que isso ocupa o terminal em que eles estão sendo executados.

Se você quiser executar os containers em 2º plano, basta acrescentar uma opção -e ao final de **sudo docker-compose up -d**

**Comment by eufelipeigor** [comment]
> @eufelipeigor tudo bem.
> 
> Se você fechar o terminal dessa forma, os containers serão desligados também. Pois eles estão executando em 1º plano, essa forma de execução é boa, para se ter as seguintes percepções:
> 
>     * Se os containers estão ligados
> 
>     * Qual erro está acontecendo em alguma requisição nos containers
> 
>     * Se algum container está em estado down.
> 
> 
> A desvantagem é que isso ocupa o terminal em que eles estão sendo executados.
> 
> Se você quiser executar os containers em 2º plano, basta acrescentar uma opção -e ao final de **sudo docker-compose up -d**

Obrigado professor!
