### ISSUE TITLE
Projetos

### ISSUE THREAD

**Issue by JPeeMP** [iurygdeoliveira/novos_caminhos#282]
Nós iremos iniciar um projeto do zero em algum momento?

**Comment by JPeeMP** [comment]
porque as coisas estão se misturando, daí acaba ficando confuso.

**Comment by iurygdeoliveira** [comment]
Olá @JPeeMP tudo bem.

A resposta é sim.  Por hora, ainda estamos evoluindo no aprendizado, estudando lógica de programação.

**Comment by JPeeMP** [comment]
Certo! Obrigado!
