### ISSUE TITLE
Problemas ao adicionar repositório do docker no linux

### ISSUE THREAD

**Issue by rafabritu** [iurygdeoliveira/novos_caminhos#283]
Estou usando linux elementary OS 5.1.7 Hera  (  Construído sobre Ubuntu 18.04.4 LTS  )
É um ubuntu modificado

Usei o seguinte comando do site    https://docs.docker.com/engine/install/ubuntu/   para adicionar o repositório do docker: 
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

Porém na hora de atualizar o repositório do docker vinha com o erro 404 not found
E então eu não consegui instalar o docker, pois o repositório não foi encontrado

**Comment by rafabritu** [comment]
Ao pesquisar um pouco descobri que o tal comando não iria funcionar na minha versão do linux ubuntu e precisava de uma modificação, então a solução foi essa:

1 - Encontre a versão do seu Ubuntu usando:

$ lsb_release -a -u

2 - Copie o Codename que apareceu

3 - Subistitua      $(lsb_release -cs) com o Codename

Ex: Se o Codename é bionic

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

E após atualizar, é só instalar o docker usando: 

$ sudo apt-get install docker-ce docker-ce-cli containerd.io

**Comment by iurygdeoliveira** [comment]
É isso ai @rafabritu  !!
