### ISSUE TITLE
Variáveis, constantes e arrays tipo imagem

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#284]
Olá prof @iurygdeoliveira é possível trabalhar imagens dentro do hmtl arrays ou variáveis tipo imagem?

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva tudo bem 

É possível, você pode transformar em dado binário. Mas não é algo muito praticado não.

A melhor maneira e manipular os arquivo de imagem, utilizando PHP + HTML + CSS + JS
