### ISSUE TITLE
Dúvida sobre a utilização do repositorio novos_caminhos do professor.

### ISSUE THREAD

**Issue by ThiagoNevesPaiva** [iurygdeoliveira/novos_caminhos#287]
Estou bem atrasado no curso, entrei a pouco tempo também. no momento estou na atividade 5 e nesse momento surgiu duvidas ao realizar a atividade 4, eu devo utilizar apenas o repositorio novos_caminhos oficial na minha maquina local? ou devo utilizar um repositorio meu mesmo?

**Comment by iurygdeoliveira** [comment]
Olá @ThiagoNevesPaiva, o repositório novos caminho está em minha conta pessoal, e através dele irei repassar os conteúdos aos alunos. Você deverá forka-lo, para poder alterar como quiser, e enviar pull requests (contribuições) ao repositório oficial.

Att.

**Comment by jalexandrersilva** [comment]
Prof. @iurygdeoliveira vejo o pessoal reclamar muito no WhatsApp, mas venho publicamente dizer que o curso é muito bom, bem planejado. Não sou puxa-saco não. Mas ser aluno a distância requer esforço redobrado. É atenção redobrada. Parabéns a toda equipe e colegas de curso.
