### ISSUE TITLE
Live Server atualiza como explorer de arquivos

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#289]
Prof @iurygdeoliveira , estou com dúvidas no live server.

As vezes funciona, as vezes não funciona. Não entendo. Ele fica entrando nesse sistema de arquivos... e geralmente quando vou entrar na pasta que copiei para a www ele faz download do index.php.

Segue a tela... alguém pode me ajudar?
![atv_prog_web](https://user-images.githubusercontent.com/69798042/93025248-b95c6980-f5d2-11ea-8d69-fd19a0763491.png)

**Comment by jalexandrersilva** [comment]
Resolvido. 
0 - subi dos containers - docker-compose up
1 - Procurei no vídeo 7.6 para instalar e configurar o live server
2 - Modifiquei a opção folder compact dentro do User Settings Workspace (no do professor foi o user) e a desmarquei a opção folder compact.
2.5 - Copiei a pasta para dentro de www
3 - Atualizei a página web.... e habilitei o live server....

Funcionou belezinha..... a duas horas atrás eu não sabia resolver. Coloquei o note para carregar, fui ficar com minha família e quando restabeleci a paciência (rssss) fui buscar a solução. Aí está

**Comment by jalexandrersilva** [comment]
Prof.... a tela abaixo mostra que inclui uma imagem à tela.... mas não consigo deixar ao lado da logo novos caminhos.

Fui buscando de onde vinha a logo e inclui uma logo2. O que preciso fazer pra minha imagem ficar ao lado e não embaixo da outra?

![atv_prog_web](https://user-images.githubusercontent.com/69798042/93028578-2845bc80-f5eb-11ea-9065-53e259f671b0.png)

**Comment by iurygdeoliveira** [comment]
> Prof.... a tela abaixo mostra que inclui uma imagem à tela.... mas não consigo deixar ao lado da logo novos caminhos.
> 
> Fui buscando de onde vinha a logo e inclui uma logo2. O que preciso fazer pra minha imagem ficar ao lado e não embaixo da outra?
> 
> ![atv_prog_web](https://user-images.githubusercontent.com/69798042/93028578-2845bc80-f5eb-11ea-9065-53e259f671b0.png)

Você precisará alterar o CSS dentro da pasta framework. Ou então apenas criar uma outra imagem e colocar ela do lado, e substituir a imagem original. Lembrando eu a tela está com largura reduzida a imagem precisa ter a largura da tela.
