### ISSUE TITLE
DOCKER NO VSCODE

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#291]
Professor Iury estou com problema no meu vs code?
fiz a instalação da extensão dorcker, ,mais olha ai os erros que aparece
![Captura de Tela (8)](https://user-images.githubusercontent.com/70108902/93027475-7656c200-f5e3-11ea-855d-d7a2eea2df7a.png)

**Comment by iurygdeoliveira** [comment]
@josepereirakls seu docker está rodando ? Me parece que o docker em sua máquina ou não foi instalado, ou se foi instalado, ele não parece estar ativo.

o que acontece quando você abre o terminal é digita docker ps -a ?
