### ISSUE TITLE
Erro ao executar o docker compose

### ISSUE THREAD

**Issue by eunayaraoliveira** [iurygdeoliveira/novos_caminhos#293]
Fiz a instalação do Docker no Windows 8, através do Docker Toolbox. Ao fazer a execução do arquivo `docker-compose up` apareceu o seguinte erro:

![Sem títughjghjlo](https://user-images.githubusercontent.com/69840817/93168156-9b892480-f6f8-11ea-819e-6f5f65453c6a.jpg)

Pelo que entendi, a imagem php foi intalada, porém a nginx não. Como devo proceder?!

**Comment by rafabritu** [comment]
A pasta do nginx não pode ser criada, talvez falte permissões

abre o cmder como administrador e tenta de novo

**Comment by eufelipeigor** [comment]
> A pasta do nginx não pode ser criada, talvez falte permissões
> 
> abre o cmder como administrador e tenta de novo

O meu deu mesmo erro, já tentei como administrador mas não funcionou.

**Comment by eufelipeigor** [comment]
![Erro Administrador](https://user-images.githubusercontent.com/70045634/93288229-cbe0c980-f7b1-11ea-8ed7-9a87643c1d6c.png)

Sempre vem esse erro

**Comment by LuizAlves99** [comment]
bom dia
também tive o mesmo erro

aguardo uma solução
meu sistema é WIN7 Ultimate

**Comment by rhph003** [comment]
![Captura de Tela (5)](https://user-images.githubusercontent.com/69976296/93400192-9beb0200-f855-11ea-85dd-7d41d4898354.png)

**Comment by iurygdeoliveira** [comment]
@rhph003 , @LuizAlves99 , @eufelipeigor , @eunayaraoliveira 

O serviço nginx não consegue iniciar, provavelmente a porta que ele está tentando utilizar, esteja sendo ocupada por outro serviço instalado na maquina de vcs.

Façam o seguinte teste, alterem a porta o no arquivo docker-compose.yml, coloquem a posta 80:80 no parâmetro ports, no serviço do nginx, se o serviço subir, é pq existe um outro serviço utilizando a porta do nginx.

**Comment by iurygdeoliveira** [comment]
Me dê um feedback

**Comment by LuizAlves99** [comment]
Sim já tinha feito isso e mesmo assim deu o erro. Alguma forma de ver qual processo está usando a porta (WIN7)

**Comment by iurygdeoliveira** [comment]
@LuizAlves99 eu configurei para usar a porta 9999, no meu docker-compose.yml.  No caso você poderia fazer esse teste trocando a porta 8080, por 9999. Não precisa da um kill para matar o processo, apenas para descobrir se a porta 9999 está sendo ocupada.

**Comment by LuizAlves99** [comment]
Vou tentar novamente, mas essa mudança eu já tentei, fiz na 9999:80 e depois na 80:80 e deu o mesmo erro

**Comment by LuizAlves99** [comment]
tentativa com 80:80
![image](https://user-images.githubusercontent.com/69818210/93467286-ed31da80-f8c3-11ea-95d6-962e2e890fbf.png)

tentativa com 9999:80
![image](https://user-images.githubusercontent.com/69818210/93467497-2d915880-f8c4-11ea-8a4a-94340d82af4c.png)

**Comment by eunayaraoliveira** [comment]
> @LuizAlves99 eu configurei para usar a porta 9999, no meu docker-compose.yml. No caso você poderia fazer esse teste trocando a porta 8080, por 9999. Não precisa da um kill para matar o processo, apenas o netstat para descobrir se a porta 9999 está sendo ocupada.

A primeira instalação que realizei, foi através da porta 80:80, presente no arquivo `docker-compose.yml`. Tentei realizar a instalação novamente, trocando para a porta 9999, conforme foi sugerido. No entanto, persiste o mesmo erro na instalação do nginx.

**Comment by LuizAlves99** [comment]
Depois de pesquisar até em site em chines, cheguei a esta soluçao
mudar o caminho dentro do arquivo docker-compose.yml que ficou assim

![image](https://user-images.githubusercontent.com/69818210/93489934-3e4ec800-f8de-11ea-8fbf-b5a670a8312d.png)


e o resultado

![image](https://user-images.githubusercontent.com/69818210/93490069-64746800-f8de-11ea-9f6f-32bd8ec3d151.png)

**Comment by eufelipeigor** [comment]
![image](https://user-images.githubusercontent.com/70045634/93492350-144ad500-f8e1-11ea-87bc-923f614ef22c.png)

Aqui deu certo removendo o /conf.d, que está no caminho da linha 13. Deixei marcado de verde na figura acima. E ficou como na figura abaixo, e deu certo:

![image](https://user-images.githubusercontent.com/70045634/93492548-4eb47200-f8e1-11ea-80d1-7c3304ec847e.png)

**Comment by LuizAlves99** [comment]
Sim, eu fiz e deu certo. Agora gostaria que o Prof Iury nos desse retorno se vai funcionar corretamente. Pelo menos o container subiu 🙏🏼

**Comment by iurygdeoliveira** [comment]
@LuizAlves99 seus prints mostram que o container, subiu! É para tudo funcionar igual está nos vídeos
