### ISSUE TITLE
O meu localhost, não aparece

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#297]
![erro PHP](https://user-images.githubusercontent.com/69942630/93246286-f48da280-f762-11ea-99cb-f3a04488d2c5.JPG)
Prof. Iury, 
Boa tarde;

Consegui fazer a instalação do docker composer. Mais quando fui utilizar o localhost, não apareceu a tela.

Olhando a instalação do meu Dock composer, parece que deu erro a instalação do meu PHP, como resolvo isso?

Muito obrigado

**Comment by L-WILIAN1987** [comment]
![localhost 9999](https://user-images.githubusercontent.com/69942630/93279125-d47ad500-f79c-11ea-91fa-0301f8777177.JPG)

Tá certo dessa forma, Prof. Iury?

Obrigado

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 sim, os containers em seu docker, estão funcionando. Está tudo ok !

O que você precisa fazer agora é criar os arquivos dentro da pasta www. E tudo tem que funcionar, igual está nos vídeos.

**Comment by L-WILIAN1987** [comment]
Vou tentar fazer isso e lhe dou um retorno.
