### ISSUE TITLE
GIT FLOW INIT NÃO INICIALIZA

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#299]
BOA TARDE PROFESSOR, FIQUEI PARADO NO PRIMEIRO VÍDEO 7.1.
NÃO CONSIGO INICIALIZAR O GIT FLOW. E SE VOCEW OBSERVAR AO LADO ESQUERDO DO VSCODE, ATE A COR ESTAR DIFERENTE
![Captura de Tela (9)](https://user-images.githubusercontent.com/70108902/93265874-a044eb80-f77f-11ea-99b7-7f19207d014a.png)
![Captura de Tela (10)](https://user-images.githubusercontent.com/70108902/93265879-a1761880-f77f-11ea-8175-c29bc02aec4b.png)

**Comment by iurygdeoliveira** [comment]
@josepereirakls alterar a linha de comando para o git bash ou para cmder. É importante seguir a recomendação dada nas aulas, para evitar erros desncessários. 

Vose está usando o windows power shell.

**Comment by josepereirakls** [comment]
Sim professor, estou nesse momento fazendo no bash

Em qua, 16 de set de 2020 23:12, Iury Gomes de Oliveira <
notifications@github.com> escreveu:

**Comment by iurygdeoliveira** [comment]
@josepereirakls e ai resolveu ? O que acontece agora, executando no git bash

**Comment by josepereirakls** [comment]
Continuou com o mesmo erro, não consigo fazer os ajustes iniciais, pra me
aparece apenas master e uma chave, depois pede pra inicializar o git.

git flow init, mas dar erro.
for flow init -f , tbm Ester dando erros

Em qui, 17 de set de 2020 00:01, Iury Gomes de Oliveira <
notifications@github.com> escreveu:

**Comment by iurygdeoliveira** [comment]
@josepereirakls , manda um print da tela, para eu ver o que acontece

**Comment by josepereirakls** [comment]
Dentro do vs code?

Em qui, 17 de set de 2020 00:11, Iury Gomes de Oliveira <
notifications@github.com> escreveu:

**Comment by josepereirakls** [comment]
Desistalei o git e estou baixando novamente

Em qui, 17 de set de 2020 00:12, Jose Pereira da Silva Filho <
josepereirakls2015@gmail.com> escreveu:

**Comment by josepereirakls** [comment]
também fiz a inicialização do cmder e mesmo assim dar erro.
Sempre que vou criar aqueles ajustes-niniciais aparece esse erro abaixo.
gostaria que você também olhasse a brach, so aparece a master, a develop não aparece abaixo dela.
o erro estar no canto inferior direito
![Captura de Tela (11)](https://user-images.githubusercontent.com/70108902/93416996-4aef0400-f87d-11ea-9631-8cff66d24879.png)

**Comment by iurygdeoliveira** [comment]
@josepereirakls você está usando o powershell como terminal.

Faz alteração para o git bash ou para o cmder

**Comment by josepereirakls** [comment]
Professor o cmder não deu certo

Em qui, 17 de set de 2020 00:44, Iury Gomes de Oliveira <
notifications@github.com> escreveu:

**Comment by iurygdeoliveira** [comment]
Manda o print, mostre-me o que acontece.

**Comment by josepereirakls** [comment]
git flow resolvido Professor, agora estou com outro problema, no index.php,
só consigo o início, daí na sequência ela não atualiza, igual o 2.2, 2.3 e
daí pra frente, não sei o que tem de errado.


Em sáb, 26 de set de 2020 20:57, Iury Gomes de Oliveira <
notifications@github.com> escreveu:
