### ISSUE TITLE
configuração Settings json

### ISSUE THREAD

**Issue by Luizedcarvalho** [iurygdeoliveira/novos_caminhos#300]
tentei configurar o settings no Windows, mas apareceu um erro e não abriu o git flow, mesmo eu instalando a extensão 

![2020-09-15 (3)](https://user-images.githubusercontent.com/70111956/93278387-e22f5b00-f79a-11ea-9e39-3ea5ec165720.png)

**Comment by L-WILIAN1987** [comment]
Tenta usar as configurações que o Prof. Iury, disponibilizou, talvez resolva o seu problema.

**Comment by fernandoifto** [comment]
Sim pode usar as configuraçõs do Iury ele deixou disponiveis no gitHub as minhas são essas 
`{
    "todo-tree.tree.showScanModeButton": false,
    "auto-rename-tag.activationOnLanguage": ["*"],
    "workbench.colorTheme": "Monokai",
    "workbench.iconTheme": "vscode-icons",
    "php.validate.run": "onType",
    "window.zoomLevel": 0,
    "php-suggest.basic": false,
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "prettier.tabWidth": 4,
    "prettier.braceStyle": "psr-2",
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "php.validate.executablePath": "C:\\xampp\\php\\php.exe",
    "files.autoSave": "onFocusChange",
    "explorer.compactFolders": false,
    "liveServer.settings.port": 5500,
    "liveServer.settings.proxy": {
        "enable": true,
        "baseUri": "/",
        "proxyUri": "http://127.0.0.1:9999"
    },
    "git.autofetch": true
}
`

**Comment by iurygdeoliveira** [comment]
@Luizedcarvalho as configurações do seu settings.json, estão erradas, da uma olhadinha no modelo que deixei, e faça as correções.

**Comment by iurygdeoliveira** [comment]
@clelianidecdasilva aqui também vc encontra resposta para aquele seu problema de validate php
