### ISSUE TITLE
Constatação

### ISSUE THREAD

**Issue by chan455** [iurygdeoliveira/novos_caminhos#301]
Yuri, na orientação sobre operadores de atribuição e comparação no comando "a += 5" => ($operatorA += 5), vc utiliza este ==> entre os valores, no entanto no meu comando não estava aceitando e observando seu espelho verifiquei que o resultado esta de forma simple então fiz apenas este "=>" e funcionou poderia me indicar algum material sobe estes códigos.

**Comment by tsartori** [comment]
Video Aula no [YouTube](https://www.youtube.com/watch?v=F7KzJ7e6EAc&list=PLHz_AreHm4dm4beCCCmW4xwpmLf6EHY9k&ab_channel=CursoemV%C3%ADdeo)

**Comment by jalexandrersilva** [comment]
Olá. Colega, tente modificar os códigos e ver no que resulta. Eu fiz isso e consegui entender tudo, principalmente mudando valores. Tente fazer isso.
