### ISSUE TITLE
Problemas no Git Flow

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#304]
![git flow](https://user-images.githubusercontent.com/69942630/93385714-004d9780-f83d-11ea-8457-b34fa45559c7.JPG)
![git flow 1](https://user-images.githubusercontent.com/69942630/93385719-017ec480-f83d-11ea-95d7-38601ea3ebd6.JPG)
![git flow 2](https://user-images.githubusercontent.com/69942630/93385723-017ec480-f83d-11ea-97f0-7f63fbac0d1d.JPG)
Prof. Iury,  Boa tarde;

Apareceu esses seguinte erros, ao instalar o git flow, como resolvo isso?

Muito Obrigado

**Comment by fernandoifto** [comment]
Se você reparar na imagem o proprio git esta falando o que você tem que fazer você digitou:
 git init flow sendo que é o contrario 
git flow init 

leia a dica do git 

![Capturar](https://user-images.githubusercontent.com/8673558/93407635-02c5e680-f869-11ea-91be-a63020c3354e.PNG)

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 tudo bem, e ai deu certo ?

**Comment by L-WILIAN1987** [comment]
Prof. Iury, vou tentar aqui, e lhe informo.

**Comment by L-WILIAN1987** [comment]
![erro git flow init](https://user-images.githubusercontent.com/69942630/93678661-86f3b600-fa83-11ea-83ad-4a4f2764b844.JPG)

Prof. Iury, tentei utilizar o comando GIT FLOW INIT, mais não deu certo. 

Tem alguma outra forma de instalar o GIT FLOW?

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 tudo bem

Seu terminal está com a fonte desconfigurada.
Por isso está com as letras estão complicadas para ler.

Instala a fonte fira-code, e configura essa fonte, que deve melhorar a visualização das letra

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 seu repositorio git init flow já está inicializado, e acontece que existem mudanças, que foram feitas em seu repositório, mas não foram comitadas ainda, provavelmente é isso.

Faz um:
 git add .
git commit -m "comentario"

Deve resolver essa último erro ai apresentado

**Comment by L-WILIAN1987** [comment]
![tela do git 1](https://user-images.githubusercontent.com/69942630/93809966-56974d80-fc24-11ea-8aae-f3f9d52c99fb.JPG)
![tela git 2](https://user-images.githubusercontent.com/69942630/93809972-57c87a80-fc24-11ea-8aa4-8fab0d03d4de.JPG)
Prof. Iury, tentei fazer o que o senhor me disse, mais deu errado. Eu acho que não está dando certo por causa de alguma dessas telas.

Obrigado

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 da um comando git status no seu repositorio e poste aqui o resultado.

Depois um git remote -v e poste aqui o resultado

**Comment by L-WILIAN1987** [comment]
![tela 1](https://user-images.githubusercontent.com/69942630/93828569-05965200-fc42-11ea-8fc8-4e984dc8c9ff.JPG)

Segue o print Prof. Iury

**Comment by L-WILIAN1987** [comment]
Prof. Iury, fiz o seguinte procedimento, na minha pasta novos caminhos, deletei tudo o que tinha dentro e cópia da sua pasta que está atualizada. Nisso criei um novo repositório no Git, com o nome novos_caminhos (não é pasta forcada), fui em Remote Configuration, e coloquei a chave HTTPS, dessa pasta, consegui fazer a sincronização normal. Mas quando fui fazer o mesmo com a pasta forcada não consegui, não sincronizou.


![nova pasta novos caminhos](https://user-images.githubusercontent.com/69942630/93829139-55c1e400-fc43-11ea-822e-9e0abb19a0c9.JPG)
![pasta forkada atualizada](https://user-images.githubusercontent.com/69942630/93829145-56f31100-fc43-11ea-91de-cf632b813340.JPG)
![tela 2](https://user-images.githubusercontent.com/69942630/93829146-56f31100-fc43-11ea-97fa-3dda8d75c1f4.JPG)

**Comment by L-WILIAN1987** [comment]
Gostaria de perguntar se o erro não está no nomes das pastas novos caminhos, na minha pasta forcada está com o nome novos_caminhos-1 e a sua está novos_caminhos?

Sobre a instalação do git flow, aparece esse erro abaixo:

![erro git flow](https://user-images.githubusercontent.com/69942630/93829690-8ce4c500-fc44-11ea-9d4a-c71c8c2f819e.JPG)

Obs: me desculpe ter trazido duas dúvidas nessa issues. Mas eu tinha ficado com duvida na issues 235, e não consegui realizar a sincronização.

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 depois da live, os problemas foram resolvidos ?

**Comment by L-WILIAN1987** [comment]
Prof. Iury, sobre o git flow, já resolvi. o que não consigo ainda é sincronizar, está dando erro.

**Comment by fernandoifto** [comment]
Mande o print do erro e da pagina do git grafic para ter uma noção de como esta sua arvore, dar um git remote -v e me mande o print.

**Comment by L-WILIAN1987** [comment]
@fernandoifto , eu respondi essa questão na issues 353, acho que deu certo.
