### ISSUE TITLE
Comentários nos códigos de exemplo

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#305]
Prof. @iurygdeoliveira, uma coisa que percebi é que eu gostaria de fazer minha contribuição. Os códigos de programação são claros e seguem uma complexidade progressiva. Eu quero fazer os comentários no código pra ficar bem claro para leigos. Se o senhor achar melhor não faço nada. Foi só uma idéia. Aguardo retorno.

**Comment by fernandoifto** [comment]
Pode ficar a vontade o é na verdade uma boa pratica documentar o código com comentarios.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva olha, fica a vontade, pode colocar os comentários e enviar como contribuição aqui.

**Comment by jalexandrersilva** [comment]
Profs. @iurygdeoliveira e @fernandoifto , por favor verifiquem os dois commits que dei com os nomes comentários video 10.2 e comentários video 10.3 e observei se o padrão que utilizei está aceitável ou devo modificar alguma coisa. Pra mim é interessante porque vou fazendo e aprendendo. Parece que guardo melhor na memória quando falo sobre a lógica dos códigos. Valeu

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva você fez algum pull request ?  Aqui não chegou nenhum contribuição sua

**Comment by jalexandrersilva** [comment]
prof. já fiz o pull request. Favor verificar

**Comment by iurygdeoliveira** [comment]
Ok
