### ISSUE TITLE
GIT no Linux

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#306]
Professor na parte 4 você excluiu a subpasta novos_caminhos (ficou 02 pastas com nome iguais) para deixar apenas as pastas 01 - vscode e a pasta 02 - git. Se eu excluir essa subpasta novos_caminhos do meu computador  e realizar o clone novamente fora dessa pasta também não estarei excluindo a pasta .git/? Quando criei o .git/ ficou nessa pasta novos-caminhos.

Como o curso avançou um pouco existe outras pastas ai para eu executar o meu está assim ~/Novos-Caminhos/novos_caminhos$ e daqui não sei para onde vou para entrar na pasta Infraestrutura de Desenvolvimento e na pasta 02-git.

Estou usando o sistema linux ubutu 20.04.

**Comment by fernandoifto** [comment]
Para mim sua duvida ficou bem confusa. mande prints para esclarecer melhor sempre mandem printes quanto mais visiveis melhor.

**Comment by iurygdeoliveira** [comment]
@jamilempc20 olá denovo tudo bem.

_"Se eu excluir essa subpasta novos_caminhos do meu computador e realizar o clone novamente fora dessa pasta também não estarei excluindo a pasta .git/?"_  R: Sim, você estará, mas ao realizar o git clone novamente, a pasta .git, será recriada automaticamente.

_"Como o curso avançou um pouco existe outras pastas ai para eu executar o meu está assim ~/Novos-Caminhos/novos_caminhos$"_ R: Isso acontece pq vc criou uma pasta novos_caminhos, acessou ela e deu um git clone dentro dela.  Mas não precisa criar uma pasta, o git clone, já realiza a criação de uma pasta novos_caminhos durante o processo. então você, só precisa acessar o diretório ~/  por exemplo e dentro dele dar um git clone.
