### ISSUE TITLE
Aula 10 - Functions

### ISSUE THREAD

**Issue by tsartori** [iurygdeoliveira/novos_caminhos#308]
Estou com um problema no seguinte código

```
function myTeam(){
    $teamName = func_get_args();
    $teamCount = func_num_args();

    return ["members"->$teamName, "count"->$teamCount];
}
```

Estou recebendo a seguinte msg de erro na linha do
`return ["members"->$teamName, "count"->$teamCount];`

-> Expected type 'object'. Found 'String'
-> Expected type 'object'. Found 'String'
E então fica marcado a string `"menbers"` e `"count"`.

Alguém com problema parecido? como resolveu?

**Comment by iurygdeoliveira** [comment]
Olá @tsartori , tem um erro no sinal de atribuição do vetor, o correto é como está abaixo.

```
function myTeam()
{
    $teamNames = func_get_args();
    $teamCount = func_num_args();
    return ["members" => $teamNames, "count" => $teamCount];
}
```
