### ISSUE TITLE
o container flow_php não foi criado no docker

### ISSUE THREAD

**Issue by AndreMarthins** [iurygdeoliveira/novos_caminhos#314]
Professor, usei o arquivo de configuração do docker composy, mas o container flow_php não foi criado no docker.

![Captura de tela de 2020-09-17 14-54-06](https://user-images.githubusercontent.com/70108419/93510573-c8eff100-f8f7-11ea-8d0b-47e366d0c491.jpg)

**Comment by iurygdeoliveira** [comment]
@AndreMarthins mas o seu print está mostrando que o seu container está criado e rodando. 

O container php_flow é algo especifico da minha máquina, mas o container que deve mesmo estar rodando em sua máquina, é este ai mesmo, que está sendo mostrado no print.

Inclusive, existe tres containers rodando em sua máquina, é necessário apenas dois. novos_caminhos_php para rodar as bibliotecas do php e o novos_caminhos_ngnix para rodar as requisições http
