### ISSUE TITLE
LIVE TIRA DÚVIDAS 21.09.2020

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/novos_caminhos#317]
Alunos, tudo bem

Favor, postar aqui as dúvidas que gostariam de verem solucionadas na live. Estarei fazendo uma apanhado das principais dúvidas feitas nas issues tambem.

Até mais.

**Comment by tsartori** [comment]
Para criar uma constante foi mostrado 2 modos.

define("NomeConstante", "ValorConstante") // É interpretado durante a execução
ou...
const AUTHOR = "valorConstante" // É interpretado antes da execução

Tem um momento certo para usar uma ou outra? Qual a diferença da que vai ser interpretada durante a execução e da que vai ser interpretada antes?

**Comment by jalexandrersilva** [comment]
Professor, consegui fazer tudo tranquilo. O Git Graph mostra que a árvore está atualizada, mas não consigo dar um pull request. O grande colega @tsartori analisou e falou que é porque tenho um outro pull request pendente #333 . Pode nos esclarecer?

**Comment by jalexandrersilva** [comment]
Outra coisa prof., é que o senhor sugeriu alguns sites sobre git e sobre desenvolvimento. Estou baixando o tower do git mas o senhor poderia fazer uma lista dos sites importantes para gente estudar?

**Comment by jalexandrersilva** [comment]
O que o github cli é importante? O que ele melhora?

O tower num ambiente de desenvolvimento vale a pena?

Pode dar exemplos de sua utilização?

**Comment by iurygdeoliveira** [comment]
> Professor, consegui fazer tudo tranquilo. O Git Graph mostra que a árvore está atualizada, mas não consigo dar um pull request. O grande colega @tsartori analisou e falou que é porque tenho um outro pull request pendente #333 . Pode nos esclarecer?

Ja respondido, é isso mesmo

**Comment by iurygdeoliveira** [comment]
> Outra coisa prof., é que o senhor sugeriu alguns sites sobre git e sobre desenvolvimento.
> 
> Baixei o tower do git mas vi que era versão pra teste e desinstalei.
> 
> O senhor sugeriu nas video aulas mas não lembro qual são os videos. Mas eu não lembro quais foram os videos. O senhor poderia fazer uma lista dos sites importantes para gente estudar?

Posso sim, para desenvolvimento web com php são esses:
https://www.php.net/manual/pt_BR/index.php
https://phptherightway.com/
https://www.php-fig.org/

**Comment by marcelosena-nat** [comment]
Olá professor, estou um pouco em atraso no acompanhamento das atividades. mais já retornei aos estudos e prosseguindo aos estudos.

**Comment by iurygdeoliveira** [comment]
> Olá professor, estou um pouco em atraso no acompanhamento das atividades. mais já retornei aos estudos e prosseguindo aos estudos.

Ok, prossigamos nos estudos ! Precisando, poste uma issue  @marcelosena-nat

**Comment by anacarolina00** [comment]
Boa noite professor, estava assistindo a aula 6.8 (12minutos) quando o senhor da o comando git flow  release finish 'v0.0.0'
na sua maquina abre uma arquivo separo e editável, no minha maquina(Windows) abre as mesmas coisas mas quando chega na tag não sei como salvar e continuar, então paro nesse ponto já que não consigo dar andamento já pesquisei mas não encontro solução. Se eu fechar a cmd e abrir novamente e dar um git branch a branch realese/v0.0.0 continua aparecendo. Poderia me ajudar? Obrigada

**Comment by ericbky** [comment]
Boa noite professor, estou com o seguinte problema: a extensão do git flow não aparece de forma alguma, já fiz pesquisas e também não tem nada sobre...

**Comment by LCSS06** [comment]
Boa noite. Entao professor minha duvida é sobre o vscode, estou tentando instalar ele no Windows 2010, com 32 bits, e esta sempre dando muitos erros.

**Comment by k-js** [comment]
![Captura de tela 2020-09-21 202025](https://user-images.githubusercontent.com/70825783/93830999-18ac2080-fc48-11ea-815f-554b85773cf4.png)

**Comment by k-js** [comment]
usei https , pois nao conseguia usar cm a chave !

**Comment by k-js** [comment]
![Captura de tela 2020-09-21 203651](https://user-images.githubusercontent.com/70825783/93831863-4eea9f80-fc4a-11ea-80ec-fcc046d3d702.png)
 
Esse erro e normal?

**Comment by k-js** [comment]
![Captura de tela 2020-09-21 204641](https://user-images.githubusercontent.com/70825783/93832270-99205080-fc4b-11ea-8797-3cdd27535906.png)
