### ISSUE TITLE
(HEAD detached from XXXXXXX)

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#322]
Cheguei nesta branch ao retornar alguns commits que estavam impedindo comandos, para voltar em um ponto específico identifiquei os commits que queria desfazer com o **git log** e dei um checkout nele, eis que aconteceu o **detached head**.

Após algum pesquisa cheguei a esta situação:
A HEAD no git representa a versão que estamos trabalhando e com o checkout de uma branch normal, o git automaticamente coloca o ponteiro da HEAD no local certo com a ultima versão daquela branch.

Neste caso de um detached head o git não vai posicionar a HEAD no local certo e qualquer commit feito depois disso ficará sem pertencer a uma branch específica e poderemos perder tudo que foi feito pois não conseguiremos fazer um merge desse código alterado na master ou em qualquer outra branch.

Para manter as alterações, devemos criar uma nova branch a partir desse ponto e continuar o trabalho para depois fazer o merge normal.

**git branch acerto**

Pronto, agora você tem seu trabalho salvo e pode continuar a trabalhar sem risco de perder suas alterações.

![image](https://user-images.githubusercontent.com/69777395/93553125-97ebdc80-f948-11ea-8c89-82050cb97cd0.png)

**Comment by iurygdeoliveira** [comment]
@iareis é isso ai !

**Comment by iareis** [comment]
Show!
