### ISSUE TITLE
Comando git push

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#323]
https://photos.app.goo.gl/GJMLM2S91wkwqVYD9

Dá erro ao realizar o git push. Como posso resolver?

jamile@jamile-Aspire-F5-573:~/Projetos/novos_caminhos$ git push
remote: Permission to iurygdeoliveira/novos_caminhos.git denied to jamilempc20.
fatal: não foi possível acessar 'https://github.com/iurygdeoliveira/novos_caminhos.git/': The requested URL returned error: 403

jamile@jamile-Aspire-F5-573:~/Projetos/novos_caminhos$ git remote add origin https://github.com/jamilempc20/Novos_Caminhos.git
fatal: remote origin already exists.

jamile@jamile-Aspire-F5-573:~/Projetos/novos_caminhos$ git push -u origin master
remote: Permission to iurygdeoliveira/novos_caminhos.git denied to jamilempc20.
fatal: não foi possível acessar 'https://github.com/iurygdeoliveira/novos_caminhos.git/': The requested URL returned error: 403

**Comment by tsartori** [comment]
Boa tarde, vc esta dando push no repositório do professor.

Vc deve dar o push no seu repositorio.
Tente o comando
`git push origin master`

**Comment by tsartori** [comment]
Para instalar a chave SSH no linux

`sudo apt-get instal openssh`

Veja o video disponibilizado pelo professor no (YouTube)[https://www.youtube.com/watch?v=I82rmTCif-k&ab_channel=Prof.IuryGomes]

**Comment by tsartori** [comment]
Conseguiu resolver seu problema @jamilempc20 ?

**Comment by iurygdeoliveira** [comment]
E ai @jamilempc20 ??

**Comment by jamilempc20** [comment]
Infelizmente não. Eu até abrir outro chamado #329 e #326.
Não quero desistir do curso, não acho difícil, mas tem certas etapas que muito complicado aprender à distância. 
Eu estou assistindo todos os videos primeiro e revejo toda hora, passo o dia todo em uma única etapa, pesquisando o problema no youtube. Não sei se vou conseguir entregar atividade de 20/09, além do zero o que mais pode acontecer? rs

**Comment by iurygdeoliveira** [comment]
@jamilempc20 , a prova do dia 20 não precisa instalar nada no computador para fazer, é tudo web, dentro do play with docker

**Comment by iurygdeoliveira** [comment]
Dá uma olhadinha no vídeo de recomendações da prova

**Comment by iurygdeoliveira** [comment]
@jamilempc20 no inicio deste chamado, você está tentando dar um git push direto para a minha conta, isso não pode, mas se você seguir a recomendação do @tsartori , vai dar certo.

**Comment by iurygdeoliveira** [comment]
Por padrão o ubuntu, já instala o software das chaves SSH, logo, acredito que se você abrir o terminal, e executar o ssh-keygen, ele já deve gerar o par de chaves ssh, depois é só adicionar no github

**Comment by jamilempc20** [comment]
https://photos.app.goo.gl/jstCQcmTeboZX2tJ9
não gerou professor

**Comment by jamilempc20** [comment]
Quanto a prova, se eu pular essa parte e depois voltar só para realizar a prova consigo? achei que docker era uma continuação do git. Eu já olhei as recomendações da prova, mas não compreendi pois ainda não vi atividade do docker.

Quanto as recomendações de @tsartori, eu segui e já realizei o fork do seu Git e fiz git clone da minha conta.

Resumindo professor estou com dificuldade de gerar a chave SSH, de realizar o comando para entrar nas subpastas e consequentemente não consigo fazer git add. de um arquivo especifico.

**Comment by jamilempc20** [comment]
https://photos.app.goo.gl/kzdjopwaM8ph797P8
https://photos.app.goo.gl/hW45pnmuGxp1jEW56

**Comment by iareis** [comment]
@jamilempc20 pode e deve fazer a prova... assista o vídeo explicativo, abra a prova veja as perguntas, entre play with docker faça os testes necessários conforme as recomendações das instruções...

**Comment by tsartori** [comment]
> https://photos.app.goo.gl/kzdjopwaM8ph797P8
> https://photos.app.goo.gl/hW45pnmuGxp1jEW56

Vc conseguiu gerar a chave
acesse o arquivo da chave com 
`gedit id_rsa.pub`

Copie a chave para poder cadastrar ela no gitHub

![cadastrar chave ssh](https://user-images.githubusercontent.com/21146217/93668640-10938b80-fa64-11ea-9996-7ab5242e8a98.png)

1 Vá em settings
2 SSH and GPT keys
3 New SSH keys

**Comment by jamilempc20** [comment]
Eu não sei o que estou fazendo de errado, eu realizo todos os comandos do vídeo e das recomendações de vocês, mas a chave não gera, eu tirei print do terminal e da tela quando abre fica em branco, não aparece a chave.
https://photos.app.goo.gl/aGUEb1LcVfsLuCQV6

**Comment by jamilempc20** [comment]
> @jamilempc20 pode e deve fazer a prova... assista o vídeo explicativo, abra a prova veja as perguntas, entre play with docker faça os testes necessários conforme as recomendações das instruções... as dúvidas que surgirem, podem ser sanadas com algumas pesquisas na web... é tranquilo... quando li a primeira achei que havia perdido alguma aula, mas preste bem atenção nas instruções...

Obrigada pela dica, vou tentar resolver.

**Comment by tsartori** [comment]
> Eu não sei o que estou fazendo de errado, eu realizo todos os comandos do vídeo e das recomendações de vocês, mas a chave não gera, eu tirei print do terminal e da tela quando abre fica em branco, não aparece a chave.
> https://photos.app.goo.gl/aGUEb1LcVfsLuCQV6

Sua chave foi salva com o nome openssh.pub pelo que foi mostrado no log na sua img
use o comando
`gedit openssh.pub`

Poste aqui se deu certo

**Comment by jamilempc20** [comment]
Muito obrigada deu certo sim.

Poderia me ajudar nisso também... https://photos.app.goo.gl/ZDiJPV16Y35tMteX6
https://photos.app.goo.gl/6Cyx77h16tVHUL486

O que está errado?

**Comment by tsartori** [comment]
Agora é só vc fazer suas alterações e dar os comandos como vc fez
`git add *`
`git commit -m "First commit"`
`git push`

**Comment by jamilempc20** [comment]
passo 1 https://photos.app.goo.gl/cpXnvfytpAU8D8N27
passo 2 https://photos.app.goo.gl/VpmHkt7LdTfYkHAo7

Fiz a minha contribuição, realizei o comando mas acho que deu erro. Pode me ajudar?

jamile@jamile-Aspire-F5-573:~/Projetos/novos_caminhos-1/01 - Infraestrutura/02 - git$ git add *
jamile@jamile-Aspire-F5-573:~/Projetos/novos_caminhos-1/01 - Infraestrutura/02 - git$ git commit -m "primeira contribuicao"
jamile@jamile-Aspire-F5-573:~/Projetos/novos_caminhos-1/01 - Infraestrutura/02 - git$ git push
To https://github.com/jamilempc20/novos_caminhos-1.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/jamilempc20/novos_caminhos-1.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
jamile@jamile-Aspire-F5-573:~/Projetos/novos_caminhos-1/01 - Infraestrutura/02 - git$

**Comment by tsartori** [comment]
Executa primeiro o comando git pull pq os repositórios n estão sincronizados
E depois torna a executar os comandos que mandei acima

**Comment by jamilempc20** [comment]
https://photos.app.goo.gl/9YgBxCDt8fF72Y687
https://photos.app.goo.gl/r3yu1keYoPMWME839  
Acho que não deu certo.

**Comment by tsartori** [comment]
`git pull origin master`

**Comment by tsartori** [comment]
`git remote add prof_iury https://github.com/iurygdeolivera/novos_caminhos.git`
`git fetch prof_iury`

`git merge prof_iury`

`git add *`
`git commit -m "Seu comentario"`
`git push`

**Comment by jamilempc20** [comment]
https://photos.app.goo.gl/1D1f8sFLt2dqtfxC7
https://photos.app.goo.gl/t99QEcUTLSiKgFw67

Acho que não deu certo.

**Comment by tsartori** [comment]
Está com divergência nas branchs, use:

`git pull`
`git merge origin`

e depois os comandos que postei acima

**Comment by iurygdeoliveira** [comment]
> https://photos.app.goo.gl/jstCQcmTeboZX2tJ9
> não gerou professor

@jamilempc20 gerou sim !  As chaves estão salvas na pasta /home/jamile/.ssh/id_rsa

**Comment by iurygdeoliveira** [comment]
@jamilempc20 vc aceita eu acessar remotamente seu computador para poder te ajudar ?

**Comment by jamilempc20** [comment]
Sim professor.
