### ISSUE TITLE
Chave SSH - não consigo gerar

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#326]
Eu coloco comando sudo apt-get install opens

jamile@jamile-Aspire-F5-573:~$ sudo apt-get install opens
[sudo] senha para jamile: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
E: Impossível encontrar o pacote opens

https://photos.app.goo.gl/cgGE7pzJwKQuWnZx7

**Comment by tsartori** [comment]
Vamos manter sua duvida apenas na issue #323 
Te respondi como prosseguir com a chave SSH lá

**Comment by jamilempc20** [comment]
Eu assistir o video do professor e coloquei o comando indicado por ele e por vc aqui, mas não consigo instalar o SSH. Ai a imagem.
https://photos.app.goo.gl/vCUJif8z2EW92a4q8

**Comment by fernandoifto** [comment]
jamilempc20 me diga em que parte vc esta o que quer fazer?

**Comment by tsartori** [comment]
Bom dia, ela já resolveu o problema da chave SSH, auxiliei ela na issue #323
