### ISSUE TITLE
contribuição

### ISSUE THREAD

**Issue by Jean-Sawano** [iurygdeoliveira/novos_caminhos#327]
não estou conseguindo inserir minha contribuição no git (pontos positivo e negativos)

**Comment by tsartori** [comment]
Vc conseguiu fazer o `git push` para o seu repositório?

**Comment by Jean-Sawano** [comment]
estou tendo problemas com essa sincronização de git com vscode..e ate para
fazer uma contribuição... no estou conseguindo acessar o garfo...


Em sex., 18 de set. de 2020 às 19:09, Thiago Sartori <
notifications@github.com> escreveu:

**Comment by iurygdeoliveira** [comment]
@Jean-Sawano coloque aqui os prints dos erros que estão acontecendo.

**Comment by albertovasconcelos** [comment]
1º Lá no repositório novos caminhos da conta professor do professor faça um fork para a sua conta;
2º Em seguida na sua conta faça um clone para sua máquina (repositório local) dentro de uma pasta que pode ser por exemplo "Projetos";
3º Na sua máquina local procure por /novos_caminhos/01 - INFRAESTRUTURA DO DESENVOLVIMENTO/02 - git/contribuicao ;
4º Nessa pasta crie um arquivo de texto com a atividade informada para contribuição, pode criar no VScode ou mesmo diretamente;
5º Comando git add para adicionar o arquivo na área de stage em seguida faça um commit;
6º Copie o endereço do seu repositório do github, voltando no terminal digite o comando: git remote add origin "https.endereço copiado.git";
7º Digite o comando git remote -v;
8º Digite o comando git push -u origin master
caso não tenha configurado vai pedir pra fazer login no GitHub
ou digitar git push (enviar ou "empurra" as alterações locais para remoto (github);
9º na sua conta, lá no repositório forkado tem que fazer um pull request, onde o professor irá aceiar a sua contribuição

Tentei explicar mais ou menos, tentando ajudar, pois não tenho muito tempo e também tive dificuldades assim como você. Para melhor compreensão assista as aulas novamente e procure também outros vídeos no youtube : 
https://www.youtube.com/watch?v=q-QTbNu8Ybc
https://www.youtube.com/watch?v=IOEtQEm_MAY
https://www.youtube.com/watch?v=dSUT0Y7suPI
https://www.youtube.com/watch?v=iGD2Pgt2DBg

O que garante a qualidade do curso é o seu esforço. Mesmo que tenha que acordar de madrugada para estudar ou estudar em horários alternados como hora do almoço, ônibus, etc.

**Comment by danielcanoli** [comment]
@Jean-Sawano acho q os passos que o @albertovasconcelos postou vão te ajudar, mas se ainda não conseguir, post os prints pra ficar mais fácil entender os erros que podem estar acontecendo.

**Comment by Jean-Sawano** [comment]
então, vou tentar novamente, seguindo os passos sugeridos... mas se eu não
conseguir, vou pedir mais ajuda...

Em sáb., 26 de set. de 2020 às 21:07, Iury Gomes de Oliveira <
notifications@github.com> escreveu:
