### ISSUE TITLE
Subpastas - Vscode

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#329]
https://photos.app.goo.gl/vCUJif8z2EW92a4q8

Quero entrar na subpasta 02- git, o comando está correto? Não estou conseguindo.

**Comment by iurygdeoliveira** [comment]
O comando seria: $ cd 02 - ....

**Comment by iurygdeoliveira** [comment]
Essa fonte no seu VSCODE, está configurada errada, por isso as letras estão tão dificeis de ler.

**Comment by iurygdeoliveira** [comment]
Instala a fira-code com a seguinte sequencia:

sudo add-apt-repository universe
sudo apt update
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
sudo apt update
sudo apt install fonts-firacode

Depois configurar o fira-code no vscode, no item fonts

**Comment by jamilempc20** [comment]
https://photos.app.goo.gl/K6Z1Ms3tawJa8KwW8

Acho que consegui mudar a fonte. está melhor?
Na imagem eu tentei colocar (cd 02 - ...) e não deu certo. :(

**Comment by iurygdeoliveira** [comment]
@jamilempc20 bem melhor agora !

**Comment by iurygdeoliveira** [comment]
@jamilempc20 o terminal bash do linux, autocompleta o nome das pastas.

Voce pode digitar:

$ cd 02 [apertar a tecla tab]

**Comment by jamilempc20** [comment]
pronto um problema resolvido, consegui entrar na subpasta :)

**Comment by jamilempc20** [comment]
https://photos.app.goo.gl/ZDiJPV16Y35tMteX6
https://photos.app.goo.gl/6Cyx77h16tVHUL486

O que está errado professor?

**Comment by iurygdeoliveira** [comment]
![image](https://user-images.githubusercontent.com/30157522/93801844-0666be00-fc19-11ea-9aae-824036d07d6f.png)

Nessa imagem, o git está indicando que seu repositório atual, está atrasado em relação os repositório no github.

Dá um comando git pull para ele atualizar, e fazer o donwload das novas atualizações
