### ISSUE TITLE
-> RESOLUÇÃO: CHAVE "SSH" NO WINDOWS - PARA PODER CLONAR E COMITAR NO GITHUB 

### ISSUE THREAD

**Issue by ramonoliveiranascimento** [iurygdeoliveira/novos_caminhos#330]
Vá em https://github.com/ e clique em "Sign in" para logar em sua conta ou “Sign Up” para criar sua conta gratuita.

Estando logado em sua conta, agora você precisa abrir o vscode ir até o terminal e digite:

ssh-keygen -t rsa -C "seu_email@email.com"

No comando dentro das aspas, informe seu e-mail cadastrado no GitHub.

![Captura de Tela 2020-09-18 às 23 30 20](https://user-images.githubusercontent.com/69820142/93657224-30489680-fa07-11ea-87f2-3aa4a0cdf07e.png)

Dê Enter na próxima pergunta (sobre o arquivo a ser criado — vamos deixar o padrão) só aperte enter.

![Captura de Tela 2020-09-18 às 23 34 52](https://user-images.githubusercontent.com/69820142/93657261-c4b2f900-fa07-11ea-8222-4433d4c747ce.png)

A próxima pergunta vai te pedir uma senha (passphrase). Você pode digitar a mesma do GitHub ou criar uma nova senha ( a senha nova não altera a senha criada no cadastro do GitHub ). Ele vai pedir uma confirmação. Digite a senha novamente e Enter. 

![Captura de Tela 2020-09-18 às 23 42 38](https://user-images.githubusercontent.com/69820142/93657394-e82a7380-fa08-11ea-8507-755f833f45d7.png)

Os comandos vão ser executados, processados e ao final vai ser criado um arquivo da chave ssh do seu computador.
 
![Captura de Tela 2020-09-18 às 23 47 46](https://user-images.githubusercontent.com/69820142/93657501-d85f5f00-fa09-11ea-8e38-2ae1d3e7422e.png)

A GORA PRECISAMOS COLOCAR ESSA CHAVE DENTRO DO GITHUB. PARA ISSO PRECISAMOS COPIAR A MESMA DO ARQUIVO QUE FOI CRIADO. SEGUINDO ESTE COMANDO:

notepad c:\Users\NOMEDEUSUÁRIO/.ssh/id_rsa.pub

![Captura de Tela 2020-09-18 às 23 59 38](https://user-images.githubusercontent.com/69820142/93657710-1f9a1f80-fa0b-11ea-8b3e-91464d8cb147.png)

Em (NOMEDEUSUÁRIO) digite o usuário de seu computador. APERTE ENTER e se tudo der certo vai abri o bloco de notas com a chave ssh criada, como mostra a imagem de abaixo.

![Captura de Tela 2020-09-19 às 00 03 23](https://user-images.githubusercontent.com/69820142/93657785-b666dc00-fa0b-11ea-9549-bf22397d03e7.png)

Agora no GitHub, vá em “Settings” e depois “SSH and GPG Keys”. Clique “New SSH key”. Informe um título para identificar o computador onde a a chave foi gerada e no campo “Key” cole todo o conteúdo do arquivo id_rsa.pub (que você abriu no Bloco de Notas)

Tome cuidado de copiar e colar todo o conteúdo do arquivo, começando por “ssh-rsa …” até o seu e-mail (incluindo ele, como na imagem). Clique em “Add Key”.

Vamos testar pra ver se essa bagaça deu certo. Digite:

ssh -T git@github.com

Ele vai perguntar se você tem certeza que quer conectar bla bla bla (yes/no). Digite yes e Enter. 
Na próxima pergunta (passphrase…) informe sua senha (a que você escolheu ao criar a chave SSH).

OBS.: NO MEU CASO JÁ PEDIU PARA DIGITAR A SENHA DIRETO. SEM A PERGUNTA (YES/NO): 
COMO A IMAGEM ABAIXO..

![Captura de Tela 2020-09-19 às 00 07 03](https://user-images.githubusercontent.com/69820142/93657869-8bc95300-fa0c-11ea-850d-ee29c6ae6695.png)

Se você receber uma mensagem do tipo:

Hi FULANODETAL! You’ve successfully authenticated, but GitHub does not provide shell access.

![Captura de Tela 2020-09-19 às 00 12 09](https://user-images.githubusercontent.com/69820142/93657902-eb276300-fa0c-11ea-85e8-0c1f5fabbc89.png)

Então tudo deu certo!

FONTE DE PESQUISA: 

https://www.webdevdrops.com/git-no-windows-github/

**Comment by iurygdeoliveira** [comment]
Excelente @ramonoliveiranascimento !
