### ISSUE TITLE
Fiz o add, o commit e o push, mas não consigo criar o pull request. Porque?

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#333]
Segue as telas
![atv_prog_web](https://user-images.githubusercontent.com/69798042/93669386-33c13980-fa6a-11ea-86b6-54a4b8085bfb.png)
![atv_prog_web2](https://user-images.githubusercontent.com/69798042/93669388-37ed5700-fa6a-11ea-9b63-42e0ec36a52c.png)

**Comment by tsartori** [comment]
Provável que seu código não esteja na ultima versão da postado pelo professor. Faça um `fetch` do repositório do professor e depois o `merge`, na hora que for fazer o `merge` é provável que de conflitos por conta de qualquer alteração que vc tenha feito no seu código para testar, se vc estiver no vscode fica facil visualizar as diferenças entre cada código, e ele te fornece a opção para manter a sua versão ou a versão do repositório.

**Comment by jalexandrersilva** [comment]
Aí está a tela. Colega @tsartori pode me ajudar em algo?

Dei um git remote -v também
![atv_prog_web](https://user-images.githubusercontent.com/69798042/93686673-2a49c880-fa8e-11ea-82eb-75e79438b432.png)


![atv_prog_web](https://user-images.githubusercontent.com/69798042/93686644-f8d0fd00-fa8d-11ea-8f86-e5c1c8f1e1fe.png)

**Comment by tsartori** [comment]
Agora ja vc deve conseguir fazer o pull request. Tente ai

**Comment by jalexandrersilva** [comment]
Colega, o pull request é dado pelo site do github. Entro no meu repositório forkado e tento criar o pull request. Aí ele mostra duas caixas de texto. Ela mostra o nome do meu repositório apitando para o repositório base do professor. Diz que pode ser dado o merge mas não mostra mais nada. Só um pull request antigo que já tava solicitado. Obrigado. Aguardo orientações

**Comment by tsartori** [comment]
Sim, o pull request é realizado no site. Então é provável que vc tenha q aguardar seu primeiro pull request se aceito ou recusado para dar um novo pull request.

**Comment by jalexandrersilva** [comment]
Valeu Sartori pela resposta professor @iurygdeoliveira o senhor confirma que o Sartori falou+

**Comment by tsartori** [comment]
Parece que é isso mesmo, vc tera de aguardar ele aceitar ou recusar seu commit
[Stackoverflow](https://stackoverflow.com/questions/8450036/how-to-open-multiple-pull-requests-on-github)

**Comment by iurygdeoliveira** [comment]
É isso ai @tsartori ! Parabéns pelas explicações
