### ISSUE TITLE
Erro docker compose up

### ISSUE THREAD

**Issue by osnijr96** [iurygdeoliveira/novos_caminhos#334]
Professor, durante a tentativa de instalar o docker meu computador dizia que ele não era permitido para Windows 10 home, apenas Enterprise

![image](https://user-images.githubusercontent.com/69945883/93689052-3f7c2280-faa1-11ea-8033-79b2218ddd9f.png)

Consegui arrumar baixando ao invés da versão stable, a versão edge.

Após instalar o docke o mesmo não conseguia se conectar por eu não possuir o WSL 2 Linux,

Instalei o WSL 2, e quando fui seguir com as aulas outr erro apareceu. quando dou o comando docker-compose up aparece este erro.

![image](https://user-images.githubusercontent.com/69945883/93689232-db5a5e00-faa2-11ea-8c52-0aeb196a9007.png)

os container aparecem como falha de conexão também

![image](https://user-images.githubusercontent.com/69945883/93689250-0349c180-faa3-11ea-8e0a-578527ed9d21.png)

Estou com esse problema desde o dia 6, infelizmente com a correria apenas agora consegui criar essa issues, estou com mais 4 cursos em andamento.

Desculpe pela demora.

**Comment by mgckaled** [comment]
@osnijr96 também enfrentei os mesmos erros. Experimente iniciar o docker através do terminal fora do Vs Code, dentro da pasta raiz. Veja issue #272.

**Comment by osnijr96** [comment]
Fiz por outro terminal agora este erro me aparece

![image](https://user-images.githubusercontent.com/69945883/93833343-b86cad00-fc4e-11ea-90ae-2b1bfdf8a992.png)

mas os containers foram criado

![image](https://user-images.githubusercontent.com/69945883/93833565-55c7e100-fc4f-11ea-8d6e-75161010604d.png)

**Comment by mgckaled** [comment]
@osnijr96 parece que existe um terceiro containers .. era para existir apenas 2.
Experimente entrar no Dashboard e fazer a exclusão dos containers de forma manual. Depois inicie o Docker no terminal novamente. 
Se não resolver, não sei qual pode ser o problema....

![Screenshot_2](https://user-images.githubusercontent.com/58960702/93903435-05906380-fccf-11ea-966b-03bd6818a38d.jpg)

**Comment by iurygdeoliveira** [comment]
@osnijr96 me parece que existe um conflito entre os dois container nginx, exclua os dois containers, e faça tente criar novamente apenas um container nginx.

**Comment by osnijr96** [comment]
Creio que consegui agora professor!

![image](https://user-images.githubusercontent.com/69945883/94084475-0105a100-fddc-11ea-9aa6-ac7340bd66fc.png)
