### ISSUE TITLE
Video 1 do Tópico 2, Introdução aos algorítimos

### ISSUE THREAD

**Issue by andersousa86** [iurygdeoliveira/novos_caminhos#335]
Quando abri o vídeo 1 do tópico 2, tem pastas do vscode do vídeo que não tenho no meu vscode como a pasta INFRAESTRUTURA DO DESENVOLVIMENTO, instalei o git flow mas não aparece na área de trabalho do vscode, estou usando Windows.

**Comment by jalexandrersilva** [comment]
Olá colega, você forjou seu repositório? Se não, vá no repositório do professor e clique em fork.
Na issue #198  tem como você atualizar seu repositório local e o seu repositório forkado no github. Provavelmente é esse o problema. Tente seguir as instruções dessa issue. Se não conseguir avise. 

Pra criar a branch develop você precisa do comando git Flow init.

Tente ver também suas branchs e a localização delas pelo git remote - v

**Comment by fernandoifto** [comment]
Precisamos de mais informações para ajuda-lo.
