### ISSUE TITLE
Index não é acessada diretamente no navegador

### ISSUE THREAD

**Issue by theteustav** [iurygdeoliveira/novos_caminhos#336]
Olá,

Quando eu acesso o `Localhost:9999` via navegador, a `Index` não é acessada diretamente.
No vídeo, o professor esteve na mesma situação e resolveu criando uma pasta antes da pasta `framework`. Eu fiz o mesmo, entretanto, mesmo assim, quando eu acesso o `Localhost:9999` continuo sendo direcionado ao diretório da pasta `www`, e somente clicando na pasta que se localiza a `Index` consigo acessá-la, conforme imagens abaixo:
![01_Index](https://user-images.githubusercontent.com/69881673/93714117-f4145380-fb36-11ea-91d4-4827a8047bf4.png)
![02_AutoIndex](https://user-images.githubusercontent.com/69881673/93714121-ff677f00-fb36-11ea-9d70-a2b172684c86.png)
![03_Localhost](https://user-images.githubusercontent.com/69881673/93714124-068e8d00-fb37-11ea-9848-e7cb29b92b50.png)
![04_Acesso Manual Index](https://user-images.githubusercontent.com/69881673/93714128-0d1d0480-fb37-11ea-9583-2a4c511df6e7.png)
Portanto, como procedo para acessar a `Index` diretamente?

**Comment by jalexandrersilva** [comment]
Tem uma opção no user settings de compacr folders. Você desmarcou?

Outra coisa, vi no seu Live Server que a porta do WWW é 5500
Entao você digita localhost:5500

Um outro detalhe é que toda vez que ligo ou religp o PC, tenho que subir a imagem novos caminhos
Quando a gente executa ele monta os container nginx e PHP. Pra isso você abre dashboardnno ícone da barra de navegação onde fica o ícone do docker, ou então abra um cmd e digite docker-compõe-se uo dentro da pasta novos caminhos. Então você tem que entrar na pasta primeiro. Se não conseguir avise......

**Comment by iurygdeoliveira** [comment]
@theteustav tudo bem ?

Você está correto no seu raciocínio, na verdade, a index.php é quem deve ser acessada diretamente ao requisitarmos o conteúdo da pasta www.

Essa pasta 2.2 .... foi criada para que possa ir criando os conteúdos de cada aula, e possibilitar a separação de cada conteúdo por aula.

Se você quiser acessar a index.php diretamente, você deve coloca-la na pasta www, e alterar o caminho do **require** dentro do index.php para acessar a pasta framework corretamente.

Provavelmente será:
`require __DIR__ . '/framework/config.php';`

Faça os testes e veja se dá certo, caso contrário, poste o resultados aqui.
