### ISSUE TITLE
terminal no Vs code

### ISSUE THREAD

**Issue by Luizedcarvalho** [iurygdeoliveira/novos_caminhos#342]
fiz a configuração da porta 9090 e fui fazer as configurações do www, no entanto entrei no terminal bash, e não consigo ter acesso mais a nenhum terminal. aparece sempre o codigo de erro 127.
como sair daqui 
![2020-09-19](https://user-images.githubusercontent.com/70111956/93794666-c00c6180-fc0e-11ea-85ec-66ab032a8099.png)

**Comment by iurygdeoliveira** [comment]
Como está seu arquivo settings.json ?

**Comment by albertovasconcelos** [comment]
Usa skype? Favor dar mais detalhes.

Veja também esse link pra ter uma ideia: [https://www.ajudanet.com.br/como-resolver-conflito-entre-xampp-e-skype.html](url)

**Comment by iurygdeoliveira** [comment]
@Luizedcarvalho acho que resolver isso na live, certo ? Fechando a issue aqui, qualquer problema, abrir outra issue
