### ISSUE TITLE
Problemas com git flow

### ISSUE THREAD

**Issue by chan455** [iurygdeoliveira/novos_caminhos#346]
Estou com problema no git flow na feature.
Aparece este seguinte erro:
Command failed: git flow feature start novo conteudo 2.3
Fatal: Base 'conteudo' needs to be a branch. It does not exist and is required.
no entanto o ramo já existe segui alguns videos mas nada deu certo. 
Até agora desde já agradeço.

**Comment by chan455** [comment]
Resolvido após a reinstalação da extensão do git flow.

**Comment by danielcanoli** [comment]
ok
