### ISSUE TITLE
não estou conseguindo sair desse terminal 

### ISSUE THREAD

**Issue by Luizedcarvalho** [iurygdeoliveira/novos_caminhos#350]
![2020-09-19 (1)](https://user-images.githubusercontent.com/70111956/93831935-7fcad480-fc4a-11ea-9bc6-15dd734eadca.png)

**Comment by Luizedcarvalho** [comment]
![2020-09-21 (3)](https://user-images.githubusercontent.com/70111956/93834045-e2bf6a00-fc50-11ea-8606-3f4d3f1b8ee5.png)

**Comment by iurygdeoliveira** [comment]
@Luizedcarvalho
