### ISSUE TITLE
POSSO USAR DUAS CHAVES SSH ?

### ISSUE THREAD

**Issue by albertovasconcelos** [iurygdeoliveira/novos_caminhos#351]
Tem problema usar duas chaves SSH? Como o GitHub defini qual esta usando?

A situação é o seguinte. Uso uma máquina virtual Linux Ubuntu onde instalei o Visual Studio e todas as configurações e extensões conforme as aulas, porém também resolvi usar o Windows que também esta com o Visual Studio e mesmas configurações. Uso uma única conta do GitHub, dai criei duas chaves SSH.

O GitHub faz distinção da plataforma que você usa?

@iurygdeoliveira

**Comment by iurygdeoliveira** [comment]
Olá @albertovasconcelos 

Usar apenas uma chave SSH por sistema operacional. Mas no Github podem existir várias chaves SSH configuradas. O github fará a distinção sim.

**Comment by albertovasconcelos** [comment]
Ok. Obrigado.
