### ISSUE TITLE
Apos Docler-compose up o Localhost:9999 não abre

### ISSUE THREAD

**Issue by LuizAlves99** [iurygdeoliveira/novos_caminhos#352]
Mesmo após subir os conteiners e confirmar que estão online, o localhost:9999 não abre

![image](https://user-images.githubusercontent.com/69818210/93912829-a0db0600-fcda-11ea-897d-d8ffedac93cf.png)

![image](https://user-images.githubusercontent.com/69818210/93912892-bea86b00-fcda-11ea-8cd1-351bfe8c6b50.png)

estou travado aqui e ficando muito atrasado no curso. Podem me ajudar? Tenho Windows7 ultimate

**Comment by chan455** [comment]
Verifica se seu arquivo do docker-compose está igual ao repositório do Yuri pois no primeiro video no qual ele explica sobre as portas ele utiliza um ip diferente e a correção esta no repositório dele. copie o aquivo e cole no seu arquivo docker-compose comigo funcionou.

**Comment by danielcanoli** [comment]
olha o arquivo docker-compose.yml tem um parametro "ports" no serviço "nginx", você pode ver mais detalhes em dos seguintes vídeos, conforme seu SO:
#ProgramdorWEB - 6.6 - Construindo Infraestrutura do desenvolvimento no linux
ou
#ProgramadorWEB - 6.7 - Construindo Infraestrutura de desenvolvimento no windows

**Comment by iurygdeoliveira** [comment]
@LuizAlves99 resolveu os problemas ?

**Comment by LuizAlves99** [comment]
depois de refazer os passos do video 6.6 meu docker-compose está assim
![image](https://user-images.githubusercontent.com/69818210/94069261-a6ae1580-fdc6-11ea-9d05-f6e484aed77e.png)

**Comment by LuizAlves99** [comment]
startei o Docker na minha máquina (uso o WIN7)
![image](https://user-images.githubusercontent.com/69818210/94069552-29cf6b80-fdc7-11ea-82e1-af731143db89.png)

e subi os conteiners 
![image](https://user-images.githubusercontent.com/69818210/94069681-600ceb00-fdc7-11ea-8371-067cb4875222.png)

e testei o localhost:9999
![image](https://user-images.githubusercontent.com/69818210/94069852-a6fae080-fdc7-11ea-80dd-7e48f4dcbde7.png)

infelizmente nada

**Comment by LuizAlves99** [comment]
Depois de usar o endereço do Docker que aparece na inicialização, agora aparece assim:

![image](https://user-images.githubusercontent.com/69818210/94293011-1857a200-ff34-11ea-8aa0-25baefbcde1d.png)

**Comment by LuizAlves99** [comment]
será minha ultima tentativa pelo WIN7 se não acharmos uma solução,  até a prox quarta feira já devo estar com o WIN10 e Linux

peço que entendam meu atraso no curso e me dê uma chance de me recuperar. Obrigado

**Comment by fernandoifto** [comment]
Mostra a pasta do seu projeto.

**Comment by iurygdeoliveira** [comment]
@LuizAlves99 como está a pasta do seu projeto ?
