### ISSUE TITLE
Erro ao finalizar o release/v0.0.0 e finalizada a parte 6.8 ( git flow)

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#353]
![erro release](https://user-images.githubusercontent.com/69942630/93922694-accdc480-fce8-11ea-8c03-39710dba0e6e.JPG)
![finalizada atividade 6 8](https://user-images.githubusercontent.com/69942630/93922698-adfef180-fce8-11ea-9cf7-12a38e8011e1.JPG)

Boa tarde, Prof. Iury,

Ao finalizar a branch release/v0.0.0, deu erro, em anexo segue a imagem.

Mesmo assim continuei a finalizar a atividade 6.8, conforme o print.

Vendo essas imagens que encaminhei, mesmo não tendo finalizado a branch release/v.0.0.0, está certo andamento do gráfico?

Muito Obrigado

**Comment by L-WILIAN1987** [comment]
![erro git flow release finish](https://user-images.githubusercontent.com/69942630/94049260-2201ce00-fdab-11ea-8dbf-6396b049933b.JPG)

Prof. Iury, tudo bem, tentei usar o comando git flow release finish v0.0.0, mas deu esse erro na imagem, não consigo finalizar essa branch.

Outra dúvida, no seu Git graph, aparece a branch github/head e o github/master, na minha não aparece, como está na imagem também.

A minha não aparece esses dois, porque será que eu não estou sincronizado com o meu GitHub?

Obrigado

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 quando vc fizer o git push para o seu repositório forkado, o github/head github/master deve aparecer

**Comment by iurygdeoliveira** [comment]
to achando que sua branch feature ainda tem mudanças não comitadas

**Comment by L-WILIAN1987** [comment]
vou fazer os testes aqui e te falo Professor Iury.

**Comment by L-WILIAN1987** [comment]
![parte 1 fork](https://user-images.githubusercontent.com/69942630/94083062-b898b400-fdd8-11ea-9618-515a15905535.JPG)
![parte 2](https://user-images.githubusercontent.com/69942630/94083063-b9c9e100-fdd8-11ea-827e-0ec99857272c.JPG)
![erro git push](https://user-images.githubusercontent.com/69942630/94083064-ba627780-fdd8-11ea-931f-5cb4a2e8afdc.JPG)
![erro git push 2](https://user-images.githubusercontent.com/69942630/94083702-33ae9a00-fdda-11ea-86fc-4803d9f6e164.JPG)


Prof. Iury, nessas imagens que eu estou te mandando, gostaria de saber se deu certo o processo de atualização do repositório.

Mais ao realizar o git push para mandar as atualizações pra o repositório forkado, apareceu essas mensagens de erro.  Como devo proceder para resolver isso?

**Comment by L-WILIAN1987** [comment]
![git grafic](https://user-images.githubusercontent.com/69942630/94302852-485a7180-ff43-11ea-8f4c-0808cabc1f67.JPG)

Git Grafic, atualizado.

**Comment by L-WILIAN1987** [comment]
ainda não consegui finalizar a release/v0.0.0, como faço para finalizar ela?

**Comment by L-WILIAN1987** [comment]
@fernandoifto , viu o seu vídeo, sobre como finalizar a release, fui fazer o procedimento e deu o seguinte erro (print), como resolvo esse problema?
![erro](https://user-images.githubusercontent.com/69942630/94309359-55309280-ff4e-11ea-9070-7d25d256bf04.JPG)

**Comment by L-WILIAN1987** [comment]
Prof, @fernandoifto, @danielcanoli , já deu certo consegui, finalizar a release, como o senhor demostrou no vídeo do You tube.  

Mais acima, coloquei um print informando que consegui eu acho atualizar o meu repositório forkado com o do Prof. @iurygdeoliveira.

Mais apareceu um erro ao utilizar o git push, mais acima eu coloquei o print do erro.

Ao analisar o meu Git Graph, preciso fazer mais alguma coisa?

Segue os prints do meu Git graph e o meu git remote.
 
Muito Obrigado

**Comment by L-WILIAN1987** [comment]
![git graf](https://user-images.githubusercontent.com/69942630/94311821-4350ee80-ff52-11ea-9e7d-cf061a9eea3e.JPG)
![git remote](https://user-images.githubusercontent.com/69942630/94311824-44821b80-ff52-11ea-9486-2b6a8b598ccc.JPG)

segue os prints

**Comment by fernandoifto** [comment]
Isso ai sua develop deve esta sempre a frente das outras branchs quando vc terminar de programar o que tinha para fazer na develop tem que mesclar a master 

para isso:
git checkout master //para setar a sua master
git merger develop //para trazer as mudanças da develop para a master
