### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by clelianidecdasilva** [iurygdeoliveira/novos_caminhos#354]
Prof. Iury, na live de ontem vi que no seu Docker aparece 4 containers e 4 imagens. No meu aparece apenas 2 containers e 3 imagens. Na minha pasta novos_caminhos não tinha a pasta www, seguindo a sua orientação incluí a pasta www e dentro dela incluí um arquivo php, no entanto, não deu certo. Além disso, aparece essa notificação. Ao abrir settings.json o cursor aponta para digitar alguma coisa no “php.validate.executablePath”: “ ”. O que devo digitar? Grata
![Containers](https://user-images.githubusercontent.com/70174839/93937955-ef9a9700-fcfe-11ea-8992-5ff40ed2b210.jpg)
![Pasta novos_caminhos no VSCode](https://user-images.githubusercontent.com/70174839/93937982-fa552c00-fcfe-11ea-9479-076a18d212a9.jpg)
![php validate executablePath](https://user-images.githubusercontent.com/70174839/93938006-004b0d00-fcff-11ea-8b2d-7c60bb93f82b.jpg)

**Comment by ericbky** [comment]
Olá, sobre a questão dos container o meu está do mesmo jeito, porém, para resolver sobre a notificação do php digite: "C:\\xampp\\php\\php.exe"

**Comment by ericbky** [comment]
Olá, sobre a questão dos containers o meu está do mesmo jeito e para resolver sobre a notificação do php digite: "C:\xampp\php\php.exe" (< coloque 2 barras, caso o direcionamento não funcione)

**Comment by fernandoifto** [comment]
Na questão do Containers não tem problema o meu esta igual ao seu 3 imagens e 2 containers, talvez o Iury estava fazendo testes com outros container e imagens.

Sobre o index.php mande uma imagem quando vc digitou localhost:9999 no navegador.

Sobre o “php.validate.executablePath”: vc pode setar um php como o ericbky disse ou apagar essa linha o meu não tem essa configuração

**Comment by danielcanoli** [comment]
@clelianidecdasilva você conseguiu progredir com as dicas do @ericbky  e do @fernandoifto ?
