### ISSUE TITLE
O QUE SIGNIFICA QUANDO Um token de acesso pessoal é adicionado à nossa conta?

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#356]
Eu até li, mas não entendi muito bem a dimensão destes tokens!!!

If you’ve lost or forgotten this token, you can regenerate it, but be aware that any scripts or applications using this token will need to be updated.

[**Se você perdeu ou esqueceu este token, pode regenerá-lo, mas esteja ciente de que todos os scripts ou aplicativos que usam esse token precisarão ser atualizados.**]

![image](https://user-images.githubusercontent.com/69777395/93959370-e6292300-fd2e-11ea-973e-b83ab4ade60e.png)

**Comment by iurygdeoliveira** [comment]
@iareis em que contexto esse erro acontece ?

**Comment by iareis** [comment]
Não é um erro. Recebi por e-mail do Git Hub. E acessando este **Personal Acess Tokens** tem estes registros...

**Comment by iurygdeoliveira** [comment]
@iareis não sei te responder
