### ISSUE TITLE
Porque o JS carregou no localhost:9999 e ao atualizar o Live Server ele não carregou?

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#357]
![image](https://user-images.githubusercontent.com/69777395/93965295-2a6cf100-fd38-11ea-859f-845b960e08d5.png)

**Comment by iurygdeoliveira** [comment]
@iareis a diferença está na configuração do proxy do live server.

no seu arquivo settings.json deve existe essa parte configurada do liveserver

```
"liveServer.settings.port": 5500,
    "liveServer.settings.proxy": {
        "enable": true,
        "baseUri": "/",
        "proxyUri": "http://127.0.0.1:9999"
```

**Comment by iareis** [comment]
Sim, tenho esta parte configurada do liveserver no arquivo settings.json.

Mas devia ter alguma falha pois estava alterando dentro dos arquivos para ver o que cada parâmetro representava. Agora recuperei os arquivos originais e está funcionando. Inclusive as alterações no index.php já são atualizados no **http://127.0.0.1:5500/** ...

![image](https://user-images.githubusercontent.com/69777395/94066623-1c17e700-fdc3-11ea-8606-0500114dd207.png)

**Comment by iurygdeoliveira** [comment]
@iareis blz então
