### ISSUE TITLE
Kubernetes e Docker são a mesma coisa?

### ISSUE THREAD

**Issue by albertovasconcelos** [iurygdeoliveira/novos_caminhos#358]
Talvez eu esteja fugindo um pouco do assunto, mas Kubernetes é a mesma coisa que Docker?

Não pratiquei só assistir os vídeos, mas ainda não entendi a aplicação ou como funciona o Docker.

@iurygdeoliveira

**Comment by albertovasconcelos** [comment]
Anteriormente no Windows vi que foi instalado o Xampp, porém com o Docker é realmente necessário? Já que é um ambiente virtualizado? Isso é que esta confuso, estou tentando entender.

**Comment by albertovasconcelos** [comment]
O Docker é um sistema virtualizado completo ou só com as ferramentas? Como funciona ou roda sem sistema operacional exatamente?

**Comment by iurygdeoliveira** [comment]
> Talvez eu esteja fugindo um pouco do assunto, mas Kubernetes é a mesma coisa que Docker?
> 
> Não pratiquei só assistir os vídeos, mas ainda não entendi a aplicação ou como funciona o Docker.
> 
> @iurygdeoliveira

Kubernetes é um gerenciador de containers. Similar ao docker-compose.

Com o kubernetes você irá gerenciar seus containers

**Comment by iurygdeoliveira** [comment]
> Anteriormente no Windows vi que foi instalado o Xampp, porém com o Docker é realmente necessário? Já que é um ambiente virtualizado? Isso é que esta confuso, estou tentando entender.

De fata, após a instalação do docker, o xampp se torna desnecessário, no ínicio do curso a instalação do xampp foi indicada pois, poderia ser que houvesse alguma necessidade de ter o php instalado por conta de alguma extensão.

Além disso, é legal para que os alunos aprendessem a instalar o xampp

**Comment by iurygdeoliveira** [comment]
> O Docker é um sistema virtualizado completo ou só com as ferramentas? Como funciona ou roda sem sistema operacional exatamente?

@albertovasconcelos assiste esse vídeo, acredito que vai responde suas perguntas: https://youtu.be/rvQ2GtSAhPI

Depois assiste a o bloco de vídeo 6, disponível la no classrroom,

**Comment by albertovasconcelos** [comment]
Ok. Obrigado!
