### ISSUE TITLE
Não estou conseguindo fazer a conexão do GitHub com as pastas do professor para o meu PC... Como faço para corrigir?

### ISSUE THREAD

**Issue by GlaucileneAssem** [iurygdeoliveira/novos_caminhos#360]

**Comment by iurygdeoliveira** [comment]
@GlaucileneAssem você encontrará as respostas na issue #343 

Na parte de atualizar repositório forkado

**Comment by L-WILIAN1987** [comment]
Assisti a aula 7.6, pode te ajudar, também to tendo dificuldades nisso.
