### ISSUE TITLE
Live Server não atualiza de forma automática a página da Web

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#361]
Prof. Iury, Boa noite;

Minha dúvida é referente ao Live Server, fiz todos os passos da aula 7.6, mas minha página da Web, não atualiza de forma automática, quando faz as alterações no index.php, pode me dar um norte, o que mais eu tenho que analisar?

**Comment by fernandoifto** [comment]
Manda o print de como esta a extensão do Navegador e extensão no VsCode.

**Comment by jalexandrersilva** [comment]
Tente observar as issue #357 e #289 tem todos os detalhes. Senão conseguir resolver avise

**Comment by danielcanoli** [comment]
@L-WILIAN1987 manda o print, como o @fernandoifto  falou pra ficar mais fácil entender o que pode está acontecendo... não deixe de ver também a sugestão do @jalexandrersilva

**Comment by L-WILIAN1987** [comment]
![print live server](https://user-images.githubusercontent.com/69942630/94301823-9ec6b080-ff41-11ea-8c42-04f027eef83e.png)
![print live server  2](https://user-images.githubusercontent.com/69942630/94301828-a0907400-ff41-11ea-8404-4d2f34e8c443.png)

@fernandoifto , @danielcanoli  , seguem os prints, conforme pedido.

**Comment by fernandoifto** [comment]
O meu só funcionou assim.

![Captura de tela de 2020-09-25 15-25-21](https://user-images.githubusercontent.com/8673558/94302938-6fb13e80-ff43-11ea-93c0-3496345c05c7.png)

**Comment by L-WILIAN1987** [comment]
@fernandoifto , acabei de fazer isso e testei novamente não deu certo.

**Comment by fernandoifto** [comment]
Manda o print do código que vc esta atualizando.

**Comment by L-WILIAN1987** [comment]
![print do codigo](https://user-images.githubusercontent.com/69942630/94303989-295cdf00-ff45-11ea-9b23-4d5d2fbfeda3.JPG)
![print navegador](https://user-images.githubusercontent.com/69942630/94303992-29f57580-ff45-11ea-8d70-7fe9311bd98c.JPG)

@fernandoifto , segue os prints.

**Comment by fernandoifto** [comment]
No linha 20 troque onde tem
 "course => "Programador Web"; por 
 "course => "Novos Caminhos";

mande o print do código salvo e do navegador

**Comment by L-WILIAN1987** [comment]
![cod 2](https://user-images.githubusercontent.com/69942630/94305871-4c3cc280-ff48-11ea-95b4-fc0854c9dc84.JPG)
![tela 2](https://user-images.githubusercontent.com/69942630/94305874-4cd55900-ff48-11ea-80f2-ffd42adf780d.JPG)
 
segue as tela @fernandoifto

**Comment by fernandoifto** [comment]
Atualizou esta normal.

**Comment by L-WILIAN1987** [comment]
Infelizmente não atualizou sozinho Prof @fernandoifto .

**Comment by fernandoifto** [comment]
Sugiro não perder tempo com isso se ficar parado em algo que basta vc apertar F5 vai se atrasar nos próximos conteúdos. Essa configuração é aquilo que chamaria de perfumaria.

**Comment by L-WILIAN1987** [comment]
Tranquilo, vou pesquisar aqui o que eu devo fazer então.

Já estou dando andamento as próximas aulas.

Vou fazer todos os testes e ver o que está dando de errado.

**Comment by L-WILIAN1987** [comment]
Prof. @iurygdeoliveira  e Prof. @fernandoifto , tem alguma coisa no código que eu possa resolver para acertar esse problema?

**Comment by fernandoifto** [comment]
vendo novamente entendi o seu problema se vc ver o vídeo quando o Iury clica Go Live no VsCode o próprio VsCode que abre o navegador usando a porta 5500 diferente da sua imagem que esta usando a porta 9999 ou seja vc não esta usando a extensão.

![Captura de tela de 2020-09-25 17-25-58](https://user-images.githubusercontent.com/8673558/94313361-f6bae280-ff54-11ea-9628-96f70ce45ea7.png)
![Captura de tela de 2020-09-25 17-29-03](https://user-images.githubusercontent.com/8673558/94313374-fc182d00-ff54-11ea-845e-b9905a577e00.png)

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 complementando a informação do fernando, no vscode dentro do arquivo settings.json, a seguinte configuração deve estar realizada

```
"liveServer.settings.port": 5500,
 "liveServer.settings.proxy": {
        "enable": true,
        "baseUri": "/",
        "proxyUri": "http://127.0.0.1:9999"
  },
  "extensions.ignoreRecommendations": true
```

O live-server vai redirecionar a requisição da porta 5500 automaticamente para a 9999 que é a porta mapeada no docker
