### ISSUE TITLE
PROBLEMAS COM LOCALHOST

### ISSUE THREAD

**Issue by Jacksonmelo43** [iurygdeoliveira/novos_caminhos#362]
meu localhost não aparece a logo do IFTO, qualquer coisa que eu digite antes dele aparece, mas ele não lê e no caso não aprecem as variáveis. acho que o problema é no global.code-snippets , vou mandar os prints da tela. na última tela só aparece o olá, o resto do código não aparece.
![Captura de tela de 2020-09-23 19-17-13](https://user-images.githubusercontent.com/69887919/94076230-001c4180-fdd3-11ea-997e-67cd6156364b.png)
![Captura de tela de 2020-09-23 19-17-49](https://user-images.githubusercontent.com/69887919/94076235-01e60500-fdd3-11ea-9cf5-d03a36690874.png)
![Captura de tela de 2020-09-23 19-18-01](https://user-images.githubusercontent.com/69887919/94076236-027e9b80-fdd3-11ea-8f68-ee8c810b5e3d.png)
![Captura de tela de 2020-09-23 19-18-05](https://user-images.githubusercontent.com/69887919/94076238-03afc880-fdd3-11ea-9962-8dab74370f07.png)
![Captura de tela de 2020-09-23 19-19-48](https://user-images.githubusercontent.com/69887919/94076240-04485f00-fdd3-11ea-8c8c-f0313cc1ccc1.png)
![Captura de tela de 2020-09-23 19-30-03](https://user-images.githubusercontent.com/69887919/94076366-4a9dbe00-fdd3-11ea-9165-a2e1786082b0.png)

**Comment by iurygdeoliveira** [comment]
@Jacksonmelo43 vamos por partes, você colocou dentro da pasta framework conteúdos para serem executados fora dela.

Primeiro deixa sua estrutura de diretórios desta forma.

![image](https://user-images.githubusercontent.com/30157522/94353044-f6991080-0042-11eb-8c4b-ceab80253d1d.png)

Note os arquivos dentro da pasta framework. E retire a pasta jackson de dentro da pasta framework.

Após isso, execute novamente, e vamos ver quais os erros estão acontecendo
