### ISSUE TITLE
DOCKER

### ISSUE THREAD

**Issue by AnaLaura07** [iurygdeoliveira/novos_caminhos#363]
Estava quase desistindo do curso mas resolvi continuar. Atualizei o windows 7 para o 10 para poder mexer com o docker, mas quando estou na parte do cmd ele fala:" O sistema não pode encontrar o caminho especificado". N estou achando a pasta, alguem pode me ajudar com uma forma de encontrar a pasta?

**Comment by iurygdeoliveira** [comment]
@AnaLaura07 preciso ver um print do erro para poder te ajudar

**Comment by AnaLaura07** [comment]
![image](https://user-images.githubusercontent.com/70103990/94151195-7f9c2600-fe50-11ea-9923-712a3637dbca.png)

**Comment by fernandoifto** [comment]
Vamos tentar utilizar Git Bash integra-lo com o VsCode.

**Comment by fernandoifto** [comment]
Resolvemos hoje também via acesso remoto.
