### ISSUE TITLE
variáveis BOLEANAS: uso de parênteses no valor de comparação lógica

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#364]
No código da aula foi utilizado parênteses para delimitar a expressão de comparação do tipo **(A > 50)**, porém no meu VSCODE ele não permite o uso deles e remove ao salvar o arquivo **index.php**, no entanto a resposta do DOCKER ao espelhar no browser ocorreu conforme o esperado.

A pergunta é: existe variação no código conforme o programa utilizado e, este código será interpretado corretamente em outros locais (browser e servidores)?

![image](https://user-images.githubusercontent.com/69777395/94100286-9ff1c380-fe03-11ea-8001-232d47ddb88f.png)

**Comment by tsartori** [comment]
O retorno no navegador esta correto. 
52 é maior que 50 -> retorna true

**Comment by fernandoifto** [comment]
As duas formas estão corretas, contudo o VsCode tem uma extensão que retira os parenteses porque não são necessários, para fazer esse teste tive que desabilitar essa extensão.
![Captura de tela de 2020-09-24 10-33-05](https://user-images.githubusercontent.com/8673558/94151964-68116d00-fe51-11ea-939c-310afff6fe31.png)

**Comment by iurygdeoliveira** [comment]
@iareis resolvido ?

**Comment by iareis** [comment]
Na realidade não @iurygdeoliveira .  O fato de uma extensão retirar os parênteses não modificou a resposta. Minha refere-se a ausência dos parênteses. O @fernandoifto disse que desabilitou a extensão para fazer o teste, porém com ou sem os parênteses a resposta foi a mesma. 

1. Posso continuar a programação sem os parênteses?
2. No caso de uma equação, onde parênteses podem ser necessários, como ficaria?
3. Qual a extensão que retira os parênteses?

**Comment by fernandoifto** [comment]
Sim pode continuar sem os parenteses eles foram retirados nesse caso porque a extensão entendeu que não eram necessários em outros caso ele manterá. faça os testes e tire suas conclusões.

**Comment by iareis** [comment]
OK, valeu @fernandoifto.
Agora tudo blz @iurygdeoliveira ...
