### ISSUE TITLE
Windows 7 ou WIndows 10 - Dica

### ISSUE THREAD

**Issue by anildogomes** [iurygdeoliveira/novos_caminhos#365]
Quem tem WIndows 7 ou 10 recomendo fazer DUAL BOOT no seu pc ou notebook para que vc tenha dois sistemas.
Fiz isso. E utilizando o sistema linux juntamente com o curso, me facilitou muito.
Fica a dica.

**Comment by fernandoifto** [comment]
Concordo plenamente, não sabia que o Docker dava tanto problema no Windows.
