### ISSUE TITLE
Como desfazer o último commit e o último push feito no GitHub?

### ISSUE THREAD

**Issue by clelianidecdasilva** [iurygdeoliveira/novos_caminhos#366]
Deletei um pasta e acabei fazendo o commit e o push e gostaria de desfazer ambos. No vídeo 5.3 - Retornando pelo fluxo do git, o professor @iurygdeoliveira citou o **git reset HEAD~1** e o **git reset HEAD~1 --soft**.  Quando ao último **git push**, pesquisei o google e encontrei duas orientações:

1) Site https://pt.stackoverflow.com/questions/359838/como-desfazer-o-%C3%BAltimo-push-feito-no-github:
•	Faça o pull das alterações que estão no repositório remoto com **git pull**.
•	Em seguida crie um commit revertendo as alterações. Caso seja somente o último commit, pode utilizar **git revert HEAD^**.
•	Após isso faça o push normalmente.

2) Site https://gist.github.com/davidalves1/f437586fa63665024f18f82dc97a83a1#file-desfazendo-push-md

Estou com dúvidas de qual comando usar **git reset HEAD~1** ou **git reset HEAD~1 --soft** ou **git revert HEAD^**, e de qual orientações seguir.
![Como desfazer o último commit e o último push](https://user-images.githubusercontent.com/70174839/94216411-a771a500-feb5-11ea-8553-e2a67e5f19e2.jpg)

**Comment by iurygdeoliveira** [comment]
Olá @clelianidecdasilva 

O orientação em 1  é a mais adequada para o seu caso. Como vc já fez o git push (enviou as alterações ao github).

Além disso, tem que observar se realmente vai ser preciso fazer o git pull (download de novas alterações no github)
Se o seu repositório local estiver sincronizado com o github, então vc só precisará dar o git reset HEAD~1 e depois o git push novamente.

**Comment by clelianidecdasilva** [comment]
Professor @iurygdeoliveira fiz o git pull, git reset HEAD~1 e depois o git push novamente, mas o git push foi rejeitado.
![git reset HEAD_1](https://user-images.githubusercontent.com/70174839/94275049-dec76c80-ff1c-11ea-9e71-927bea6f4b90.jpg)

**Comment by iurygdeoliveira** [comment]
@clelianidecdasilva depois do git reset.

Faz uma alteração qualquer em algum arquivo, depois um 
git add .
git commit -m "seu comentario"
git push

**Comment by clelianidecdasilva** [comment]
Professor @iurygdeoliveira para retornar na linha do tempo e deixar o meu repositório local e repositório remoto sincronizado com o seu qual seria p procedimento?

![Repositório](https://user-images.githubusercontent.com/70174839/94300352-3d054700-ff3f-11ea-8b27-e44f7359662a.jpg)

**Comment by iurygdeoliveira** [comment]
Da forma que está no print acima os comandos seriam:

git add . 
git commit -m "Seu comentario"
git push (para enviar para o repositorio forkado no github)

A branch prof_iury, sempre ficará atrás mesmo, pois ela é utilizada apenas para puxar novas atualizações do meu repositório. essa branch prof_iury, não ficará a frente da branch master local, e nem da branch master do repositório github

**Comment by clelianidecdasilva** [comment]
@iurygdeoliveira consegui resolver a questão da pasta deletada e fazer o teste do localhost:9999.
