### ISSUE TITLE
PÁGINA LOCALHOST NÃO FUNCIONA (SOLUÇÃO)-WINDOWS

### ISSUE THREAD

**Issue by Lana-Monteiro** [iurygdeoliveira/novos_caminhos#367]
### COMO RESOLVER ERRO PARA ABRIR PÁGINA DO LOCALHOST

Abra seu docker e verifique qual o IP dele
![POSTAR DOCKER1](https://user-images.githubusercontent.com/70002874/94214866-2dd7b800-feb1-11ea-886f-482032739246.jpg)

Acesse seu navegador usando o número do endereço IP que apareceu no seu docker juntamente com ":9090" ou a porta que você tiver configurado no docker-compose.yml no seu vscode. _No caso o Professor configurou a porta em "9999"_
![POSTAR DOCKER2](https://user-images.githubusercontent.com/70002874/94215047-b7878580-feb1-11ea-97f5-6065554e570d.jpg)

**Comment by iurygdeoliveira** [comment]
@Lana-Monteiro qual o seu windows ?  É o docker toolbox que está utilizando ?

**Comment by Lana-Monteiro** [comment]
@iurygdeoliveira Windows 7, docker toolbox.

**Comment by fernandoifto** [comment]
Resolvemos esse questão ontem.

**Comment by Lana-Monteiro** [comment]
@fernandoifto me ajudou na resolução desta questão e vim aqui compartilhar! Mais uma vez agradecida ao Fernando pela grande ajuda

**Comment by fernandoifto** [comment]
https://www.youtube.com/watch?v=Igx2HzCsds8&t=23s
