### ISSUE TITLE
Usuário root e comum

### ISSUE THREAD

**Issue by AdennyFernandes** [iurygdeoliveira/novos_caminhos#369]
Prezados professor. Estou refazendo tudo novamente.
Tinha apresentado alguns problemas, agora preciso de ajuda de como proceder.

Quais são os comandos para eu autorizar o root a dar poderes de administrador ao usuário comum, que sou eu, nome adennyfernandes, usando o sudo, vide imagem. Para que tudo dê certo, na hora que inserir os comandos da sua vídeo aula.
![Ubunto 20 04 no Windows 10](https://user-images.githubusercontent.com/70215330/94293187-4f2db800-ff34-11ea-801b-502d9a0d47dc.png)

**Comment by fernandoifto** [comment]
Esse ubuntu que vc instalou ai é virtualizado não vai ter servir para nada no curso pois ele o máximo que vc vai conseguir é treinar comandos do Linux que não precisam de ambiente grafico.

**Comment by AdennyFernandes** [comment]
Qual sua sugestão? Seguir com windows até o final do curso e depois
praticar tudo novamente já com o sistema operacional linux? Procede? Então
vou desinstalar o Ubuntu e ficar no Windows 10 até o final do curso. Depois
eu me viro no Linux, revendo tudo novamente.

Em sex., 25 de set. de 2020 às 15:38, fernandoifto <notifications@github.com>
escreveu:

**Comment by fernandoifto** [comment]
Não sei o que sugerir não sei em quantas horas ou dias vc configuraria o Linux ou o Windows eu fiz isso a configuração na maquina do meu trabalho com Linux em uma tarde.

**Comment by AdennyFernandes** [comment]
Eu me viro depois no Linux, quero ter a certeza que irão disponibilizar
vídeo aulas, realizando esses procedimentos no Windows até o final do curso.

Em sex., 25 de set. de 2020 às 17:05, fernandoifto <notifications@github.com>
escreveu:

**Comment by fernandoifto** [comment]
A parte de configuração acabou no bloco de aula 6 agora é só código PHP, HTML, CSS e Java Script não tem mais questão de problema de SO depois que configurar o Docker.

**Comment by AdennyFernandes** [comment]
Muito obrigado pela atenção. Estou um pouco atrasado, mas estou correndo
atrás, tentando acompanhar. Recentemente fui assaltado, levaram meu celular
e alguns trocados, isso acabou me atrapalhando, atrasando um pouco. Estou
no passo a passo aqui do Windows, já estou me aproximando aos poucos.

Em sex., 25 de set. de 2020 às 17:18, fernandoifto <notifications@github.com>
escreveu:

**Comment by AdennyFernandes** [comment]
Professor estou com este problema aqui, não aparece o terminal, fiz todo o
passo a passo conforme a vídeo aula.
[image: image.png]

Em sex., 25 de set. de 2020 às 17:22, Adenny Fernandes <adennyfer@gmail.com>
escreveu:
