### ISSUE TITLE
Problema com o gedit no Ubunto 20.04, instalado no Windows 10.

### ISSUE THREAD

**Issue by AdennyFernandes** [iurygdeoliveira/novos_caminhos#370]
Boa tarde Professor. Alguém por gentileza sabe como instala o gedit no Ubunto 20.04? Já tentei Vários comandos: sudo apt-get install gedit. Ele apresenta este problema quando dou comando  sudo gedit /etc/php/7.
Unable to init server: Could not connect: Connection refused
(gedit:21890): Gtk-WARNING **: 15:40:27.923: cannot open display:

**Comment by fernandoifto** [comment]
Esse ubuntu que vc esta usando no WSL2 não vai funcionar o Gedit, ele é um programa que usa interface gráfica esse ubuntu do e esse SO do WSL2 é apenas um SO do tipo terminal, só linha de comando não server para o curso.

**Comment by AdennyFernandes** [comment]
Já desinstalei o Ubuntu do Windows 10. Vou praticar então somente no
Windows. Depois eu revejo tudo novamente no Linux. Sou iniciante nesta
área, porém sou inteligente para aprender rápido e me virar, pesquisando e
estudando. Acho que pelo Linux até mais fácil, linhas de comando é muito
melhor. Windows dá muito trabalho.

Em sex., 25 de set. de 2020 às 16:51, fernandoifto <notifications@github.com>
escreveu:

**Comment by fernandoifto** [comment]
Muito bem.

**Comment by iurygdeoliveira** [comment]
@AdennyFernandes é isso ai ! Parabéns !
