### ISSUE TITLE
PROBLEMA NO DOCKER

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#371]

**Comment by josepereirakls** [comment]
Boa tarde, estou com problema no docker depois que atualizei, os comandos estar dando erros, e os conteiner e as imagens  não apareceu, como resolver, não consigo continuar com as aulas enquanto não resolver esse problema.
![Captura de Tela (13)](https://user-images.githubusercontent.com/70108902/94311142-1fd97400-ff51-11ea-8853-1f703860e3e2.png)

**Comment by fernandoifto** [comment]
Manda o print do docker-compose.yml, essas imagens que estão ai não parece as que o Iury sugeriu a instalação.

**Comment by Andre101010** [comment]
Iae Jose, blz!?
Existe duas opções para você resolver.

PRIMEIRA OPÇÃO: Remova os contêiners e image. 
![PRIMEIRA O PCAO -Remocao de conteiners e images vscode](https://user-images.githubusercontent.com/69916187/94325926-532ef980-ff77-11ea-8a1f-c48d57016257.jpg)

Depois execute o comando, no terminal shell do vscode, docker-compose up
para poder construir os contêiner novamente. (obs: o software docker, tem que está aberto)
![comando docker](https://user-images.githubusercontent.com/69916187/94326061-20d1cc00-ff78-11ea-916a-d65060ddd025.jpg)

Caso não resolva, faça a SEGUNDA ALTERNATIVA.

SEGUNDA ALTERNATIVA:
Entra no seu GITHUB e baixa todos os seus arquivos NOVOS CAMINHOS
![git](https://user-images.githubusercontent.com/69916187/94326042-026bd080-ff78-11ea-9ca2-413c70bb9a12.jpg)
Após o download, você vai extrair os arquivos com winrar, ou caso já venha extraído as pastas e arquivos, você vai colar nesse caminho C:\xampp\htdocs (obs: antes de realizar a substituição da pasta nova, você vai apagar a pasta NOVOS CAMINHOS atual que está no seu PC. Seu vscode tem que está fechado). Apos ter feito esse procedimento, você vai entrar no vscode, abrir a nova pasta (NOVOS CAMINHOS) e vai realizar o seguinte comando, docker-compose up ,no terminal shell.

**Comment by josepereirakls** [comment]
ANDRE 101010, MUITO OBRIGADO, CONSEGUIR RESOLVER O PROBLEMA COM SUA, SEGUIR O SEU PASSO E DEU CERTO.
![Uploading Captura de Tela (14).png…]()

**Comment by josepereirakls** [comment]
ANDRE 101010, MUITO OBRIGADO, CONSEGUIR RESOLVER O PROBLEMA COM SUA, SEGUIR O SEU PASSO E DEU CERTO.
![Captura de Tela (14)](https://user-images.githubusercontent.com/70108902/94326589-49a79080-ff7b-11ea-92c1-d4fb1d3c1afd.png)

**Comment by iurygdeoliveira** [comment]
@Andre101010 excelente ! Parabens !
