### ISSUE TITLE
PROBLEMA NO INDEX.PHP

### ISSUE THREAD

**Issue by josepereirakls** [iurygdeoliveira/novos_caminhos#374]
Os index.PHP que estão dentro das pasta, 2.1, 2.2, ... não estão funcionando quando digito no navegador, "localhost:9999, mas quando criou um index, fora, funciona apenas o 2.1 e 2.2, os demais não estão dando certo, coo resolver?
e estar aparecendo mensagen de erro do php, no canto direito inferior, quando apago os comando dentro do index, e digito <?PHP, não aprece nada.
![Captura de Tela (15)](https://user-images.githubusercontent.com/70108902/94354887-db83cc00-0055-11eb-817f-2836a76794dd.png)
![Captura de Tela (16)](https://user-images.githubusercontent.com/70108902/94354889-dcb4f900-0055-11eb-99d3-d4ba0e3858b8.png)
![Captura de Tela (17)](https://user-images.githubusercontent.com/70108902/94354891-dd4d8f80-0055-11eb-8860-5cb4023430b4.png)
![Captura de Tela (18)](https://user-images.githubusercontent.com/70108902/94354892-dd4d8f80-0055-11eb-8d8e-9e6a7d761cbe.png)
![Captura de Tela (19)](https://user-images.githubusercontent.com/70108902/94354893-dde62600-0055-11eb-823f-9b3215172541.png)
![Captura de Tela (20)](https://user-images.githubusercontent.com/70108902/94354894-de7ebc80-0055-11eb-94f0-8199684e947e.png)

**Comment by iurygdeoliveira** [comment]
Olá @josepereirakls vamos por partes nessa imagem

![image](https://user-images.githubusercontent.com/30157522/94372502-8aff8380-00d4-11eb-8731-2125142b5f0e.png)

Você adicionou o index.php dentro da pasta vendor. Isso não é necessário, a pasta vendor ela é controlada pelo composer.json.
Não mexemos nela.  O arquivo index.php deve ficar na pasta www por default.

**Comment by iurygdeoliveira** [comment]
![image](https://user-images.githubusercontent.com/30157522/94372554-17aa4180-00d5-11eb-9abc-5c782df07951.png)

Nesta imagem, recomendo desinstalar a extensão phpcs do seu vscode. Iremos utilizar ela mais a frente, por hora ela não é necessária.

**Comment by iurygdeoliveira** [comment]
![image](https://user-images.githubusercontent.com/30157522/94372582-593aec80-00d5-11eb-8294-b1856ffbed74.png)

Nessa imagem, o caminho para arquivo config.php está errado. Nos exemplos que coloquei o caminho é:

`require __DIR__ . '/../framework/config.php';`

Como está essa linha nesse arquivo index.php, referente a essa imagem ?

**Comment by osnijr96** [comment]
Estou com o mesmo problema professor.
![image](https://user-images.githubusercontent.com/69945883/94375752-4b449600-00ec-11eb-983a-7030ed32ac20.png)

**Comment by josepereirakls** [comment]
osnijr96 , resolvi da seguinte maneira,  nesse comando dentro do index.php,  _**require __DIR__ . '/../framework/config.php';**_
você tira os dois pontos e um travessão, deixando ela assim, **require __DIR__ . '/framework/config.php';**_ fazendo isso vai dar certo, pois no meu deu.

**Comment by osnijr96** [comment]
@josepereirakls Muito obrigado! Agora deu certo!

**Comment by josepereirakls** [comment]
Estamos junto nessa.

Em seg, 28 de set de 2020 19:26, Osni Silva Junior <notifications@github.com>
escreveu:

**Comment by iurygdeoliveira** [comment]
É isso ai alunos, parabens

**Comment by josepereirakls** [comment]
Obg professor, mas estou muito preocupado comnl a prova, pois não sei não
por onde começar.



Em seg, 28 de set de 2020 20:29, Iury Gomes de Oliveira <
notifications@github.com> escreveu:

**Comment by josepereirakls** [comment]
Ganho 1 ponto ? kk
