### ISSUE TITLE
Failed ao carregar wwww / estrutura confusa

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#375]
Olá pessoal e prof. @iurygdeoliveira e @fernandoifto estou perdido nesse erro. Peço também que observem a árvore de pastas e me digam o que tá acontecendo de errado. estou sem saber o que fazer
![atv_prog_web2](https://user-images.githubusercontent.com/69798042/94371053-f09a4280-00c9-11eb-9c7f-b479064f9e2c.png)
![atv_prog_web](https://user-images.githubusercontent.com/69798042/94371054-f1cb6f80-00c9-11eb-82a9-6327aeab6bce.png)

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva tudo bem.

O navegador está tentando requisitar um arquivo dentro da pasta 2.13_Classes_propriedades_objetos/

Mas pelo print da tela, essa pasta não existe dentro da pasta www. Acredito que o erro seja esse.

Observe a URL no navegador, e observe a estrutura de pastas dentro do www. Precisam estar sincronizados.

**Comment by jalexandrersilva** [comment]
Consegui, obrigado.
