### ISSUE TITLE
Problemas nas questões 9 e 10

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#376]
Prof. @iurygdeoliveira e @fernandoifto, e colegas de curso. Preciso de vossa ajuda.

Passei o dia inteiro e não consegui resolver a questão 9 e a 10. Todas as oito anteriores eu consegui desenvolver o código necessário.

Problemas são:
como retornar o valor da posição 0 da $array em formato inteiro? Toda vez que retorno só dá tipo texto. Não consigo pegar no formato de número apesar do var_dump($array[posiçao]) me retornar numero inteiro.

Consegui começar o if pra percorrer toda a array mas sempre dá erro porque só vem como string e não vomo valor.

Como comparar o valor de uma posição da array com o valor da outra posição do array? eu conseguiria mas só vem como texto, não consigo que o php enxergue a comparação como número.

E que forma de laço eu utilizo? pensei em criar uma nova array só comparando valores da $array, mas não consigo pegar em formato inteiro. Vou aguardar respostas e vou continuar a estudar o curso, pra nao atrasar.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva me mostra o print do erro que está retornando

_Como comparar o valor de uma posição da array com o valor da outra posição do array? eu conseguiria mas só vem como texto, não consigo que o php enxergue a comparação como número._
R.: Você pode usar o códigos nativos do PHP (https://www.php.net/manual/pt_BR/function.array-intersect-assoc.php)

_E que forma de laço eu utilizo? pensei em criar uma nova array só comparando valores da $array, mas não consigo pegar em formato inteiro. Vou aguardar respostas e vou continuar a estudar o curso, pra nao atrasar._
R:  `foreach` ou `for`

**Comment by mgckaled** [comment]
@jalexandrersilva 
Exemplo de laço `for` para manipulação de arrays:

```
// Armazenar todos os valores não negativos dentro de uma nova array
// $pos ira apresentar apenas valores não negativos.

$a = [-1, 1, -1, 1];
$pos = [];
for ($i = 0; $i < count($a); $i++) {
    if ($a[$i] >= 0) {
        array_push($pos, $a[$i]);
    }
}
var_dump($pos);

```

**Comment by jalexandrersilva** [comment]
Obrigado pela ajuda.... consegui fazer com algumas adaptações.
