### ISSUE TITLE
Mensagem de erro Git Push

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#377]
Prof. Iury, Boa tarde;
Fui realizar um Git push, e apareceu o seguinte erro:

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.      

Please make sure you have the correct access rights
and the repository exists.

o que faço para consertar isso?

![git push](https://user-images.githubusercontent.com/69942630/94487352-3e40a900-01b7-11eb-814c-7ae004c3cbdd.JPG)

**Comment by fernandoifto** [comment]
Acredito que vc esta querendo mandar para o repositório do professor Iury dar um git remote -v,
vc tem que adicionar o seu repositório forkado.

**Comment by danielcanoli** [comment]
@L-WILIAN1987 acho que é bem o que o @fernandoifto  falou, dá um confere também na issue #176 que você vai ter referências sobre com a sua conta

**Comment by L-WILIAN1987** [comment]
Prof. @iurygdeoliveira , @fernandoifto , @danielcanoli , fiz o que me disseram, mais não deu certo.

Segue o print da tela:

![erro git](https://user-images.githubusercontent.com/69942630/94599002-31c75980-0266-11eb-8fca-e954ae412f6a.JPG)

**Comment by JPeeMP** [comment]
Cara certifica em qual branch você está, verifica o estado do teu repositório com "git status", verifica seus repositórios remotos com "git remote", dá um "git add", verifica tudo novamente, dá um "git commit" coloca a descrição, e depois disso verifica se o link do teu repositório tá associado, depois disso tenta fazer o "git push" pra ver se as coisas vão pro repositório.

**Comment by fernandoifto** [comment]
Pode ser que sua chave ssh não esteja configurada.

**Comment by L-WILIAN1987** [comment]
Prof. @fernandoifto e @JPeeMP, fiz os passos que o amigo de sala me orientou, mais mesmo assim ainda deu erro.

A chave SSH, está adicionada no GitHub. Como faço para verificar se ela está no VSCODE?



![erro git push](https://user-images.githubusercontent.com/69942630/94601178-786a8300-0269-11eb-84c5-68081b041bb6.JPG)
![chave ssh](https://user-images.githubusercontent.com/69942630/94601179-799bb000-0269-11eb-8ff6-1c3f185c069d.JPG)

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 não conseguiu instalar nem o git bash,  e nem o cmder ?  Estou notando em vários posts, que vc utiliza o powershell

**Comment by L-WILIAN1987** [comment]
@iurygdeoliveira, consegui instalar simm. Achei melhor usar esse. Vou voltar a usar eles. Eu to usando a configuração que o senhor, passou.

**Comment by L-WILIAN1987** [comment]
Prof. @iurygdeoliveira , troquei a linguagem no terminal e coloquei a do CMD, mesmo assim o processo não deu certo.

**Comment by iurygdeoliveira** [comment]
Qual o resultado do git remote -v ?

Me parece que o repositorio para o qual o git push tenta enviar as mudanças, não é o seu original.

**Comment by L-WILIAN1987** [comment]
![erro git](https://user-images.githubusercontent.com/69942630/94751957-41c36400-0360-11eb-8c0b-c2b74f5e35f6.JPG)

Segue o erro. 

Somente o git push que não está funcionando. O resto tá indo bem.

**Comment by L-WILIAN1987** [comment]
Prof. @iurygdeoliveira , @fernandoifto , @danielcanoli , deu certo o meu Git push. Minha dúvida é a seguinte, olhando o git grafic, não apareceu o Git Hub e nem o Git Hub Head, achei que eles iriam aparecer assim que eu desse um git push. Eu substitui a chave SSH pela chave HTTPS.

Segue a imagem dos passos que eu fiz.
![git push](https://user-images.githubusercontent.com/69942630/94965692-5162ba00-04d2-11eb-8bb0-5cb26db17f6f.JPG)

**Comment by fernandoifto** [comment]
Tira o print de mais de baixo acho que tem dois ramos mais a baixo.

**Comment by L-WILIAN1987** [comment]
Prof. @fernandoifto , segue as prints das telas:

![git grafic 2](https://user-images.githubusercontent.com/69942630/94998401-ed9ac880-0587-11eb-935c-d383c34601b8.JPG)
![git remote -v](https://user-images.githubusercontent.com/69942630/94998404-eecbf580-0587-11eb-8ec0-e61d39e2a2da.JPG)

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 pq o seu origin aponta para dois remotes diferentes ?  O certo era tando o remote com (fetch) quanto o remote com (push) apontarem para o mesmo link, olhá como é no meu 

![image](https://user-images.githubusercontent.com/30157522/95025652-bc8ec680-0661-11eb-821f-909017c6b300.png)

**Comment by iurygdeoliveira** [comment]
Para resolver acredito que os seguintes passos devem resolver

1) git remote remove origin
2) git remote add origin https://github.com/L-WILIAN1987/novos_caminhos-1.git

**Comment by L-WILIAN1987** [comment]
Prof. @iurygdeoliveira , eu acabei de fazer uma atualização no meu repositório forkado e deu certo. Por favor, dá uma olhada nessa tela que estou te encaminhando.

O nome origin, foi no nome que eu coloquei no Edit the remote origin, por isso tá esse nome.

A minha única dúvida, é porque não aparece no meu Git graph, o git hub e o git head?

![foto 1](https://user-images.githubusercontent.com/69942630/95143343-30a59900-074c-11eb-8ba8-90ff8c84fc70.JPG)

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 fique tranquilo quanto a esses apontamentos, quado vc faz o git push se refere ao commit que o github está apontando, o git head se refere a commit/branch no qual o git está apontando no momento. Se não estiver aparecendo no git graph, pode ser algum erro da extensão. Mas você pode usar o comando git log para confirmar. Por isso é importante não depender tanto de ferramentas gráficas.

**Comment by L-WILIAN1987** [comment]
ok! Prof. @iurygdeoliveira , irei dar uma olhada nisso.
