### ISSUE TITLE
Problema com Composer.php e Extensão "Bracket Pair Colorizer 2", e php-errors.log

### ISSUE THREAD

**Issue by clelianidecdasilva** [iurygdeoliveira/novos_caminhos#380]
Professor @iurygdeoliveira consegui resolver o problema relatado na Issues #366 e fazer o teste da localhost:9999, a página foi gerada igual foi demonstrada na vídeo aula. No entanto, agora ocorreram alguns problemas conforme as imagens abaixo. 

![Composer php](https://user-images.githubusercontent.com/70174839/94509526-d73ce780-01ea-11eb-8d50-f3438d18e9d5.jpg)

![Notificação](https://user-images.githubusercontent.com/70174839/94509556-e0c64f80-01ea-11eb-8b6c-f6311f8b767c.jpg)

![php errors log](https://user-images.githubusercontent.com/70174839/94509570-e6bc3080-01ea-11eb-87ef-b252f327e381.jpg)

**Comment by iurygdeoliveira** [comment]
Olá @clelianidecdasilva vamos por partes

![image](https://user-images.githubusercontent.com/30157522/94743802-5a2a8300-034e-11eb-9b4b-6b3f83aa473b.png)

Essa imagem, exibe o código do composer.phar, não há erro nenhum aqui, é exatamente isso mesmo. E também não "mexemos" nesse arquivo, tudo é gerenciado pelo composer

**Comment by iurygdeoliveira** [comment]
![image](https://user-images.githubusercontent.com/30157522/94743995-a8d81d00-034e-11eb-8111-6921bdf4bd36.png)

Nunca tinha visto este erro, experimente isntalar e desinstalar o bracket pair colorizer 2

**Comment by iurygdeoliveira** [comment]
![image](https://user-images.githubusercontent.com/30157522/94744065-c73e1880-034e-11eb-9969-e3e5447399be.png)

Existe um problema no caminho do arquivo index.php.  

Neste caso, olhando sua estrutura de diretórios, o index.php não deveria estar sendo invocado. Pois ele não existe dentro do diretório www
