### ISSUE TITLE
Declaração de Função e Retorno de Variável

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#381]
Gostaria de uma explanação sobre declaração de função e o retorno de variável, para que estes dois conceitos sejam melhor compreendidos, já que me parecem vitais para criarmos as funções em PHP para a resolução da prova.

Penso em algum tipo de esquema que demonstre uns dois esqueletos que identifique quem é quem e como podemos montar.
Passei 3 dias matutando em como colocar de forma adequada a fórmula matemática que havia considerado como solução para a primeira questão da prova.

**Comment by iareis** [comment]
A declaração de funções é feita a partir da palavra reservada **function** seguida do nome da função e de sua lista de argumentos, enquanto o corpo da função é delimitado por chaves ({ e }), entre as quais deve ficar todo o conjunto de instruções a ser executado quando a função for invocada.

**_<?php
**function funcaoDeclarada** ($arg_1, $arg_2, /* ..., */ $arg_n)
{
    echo "Exemplo de função.\n";
    **return** $valor_retornado;
}_**

**return** é uma palavra reservada do PHP que nesse contexto tem como finalidade retornar um valor encerrando a função. Nota: Caso return for omitido então o valor NULL será retornado.

**Comment by iurygdeoliveira** [comment]
@iareis vejo que você já encontrou a melhor resposta. Parabens
