### ISSUE TITLE
vscode - erro ao instalar o git flow

### ISSUE THREAD

**Issue by Agenildo** [iurygdeoliveira/novos_caminhos#383]
Oi Professor.
Tenho perdido muito tempo com vs code por conta de alguns erros.
este por exemplo havia deixado passar, mas para usar o gitflow ao instalar  ele informa :
Unable to install 'psykosoldi3r.vscode-git-flow' extension because it is not compatible with the current version of VS Code (version 1.35.1).

**Comment by fernandoifto** [comment]
Manda o print do código digitado e o erro.

**Comment by Agenildo** [comment]
Esta é a mensagem mostrada ao tentar instalar.
Unable to install 'psykosoldi3r.vscode-git-flow' extension because it is
not compatible with the current version of VS Code (version 1.35.1).

Em ter., 29 de set. de 2020 às 19:42, fernandoifto <notifications@github.com>
escreveu:

**Comment by fernandoifto** [comment]
Preciso ver o print mesmo

**Comment by fernandoifto** [comment]
Você clica nessa parte que desenhei de vermelho para anexar o print.
![Captura de tela de 2020-09-30 15-54-19](https://user-images.githubusercontent.com/8673558/94727755-91406a80-0335-11eb-9a60-5cd0fc60188e.png)

**Comment by iurygdeoliveira** [comment]
@Agenildo poderia em enviar o print ?

**Comment by mgckaled** [comment]
@Agenildo pode ser que VS Code esteja desatualizado. A versão mais atual é "Update 1.49.3".  Tente atualizar primeiro antes de instalar o plugin.
