### ISSUE TITLE
Terminal não reconhece comando PHP

### ISSUE THREAD

**Issue by 1bertoh** [iurygdeoliveira/novos_caminhos#387]
Meu Terminal não reconhece os comandos que iniciam com PHP, dá o seguinte erro:

PS C:\Users\HP\Desktop\projetos\PHP\novos_caminhos\www> php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php : O termo 'php' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se 
o caminho está correto e tente novamente.
No linha:1 caractere:1
+ php -r "copy('https://getcomposer.org/installer', 'composer-setup.php ...
+ ~~~
    + CategoryInfo          : ObjectNotFound: (php:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

 Vi por ai que o erro pode ser porque não ele não está nas variáveis de ambiente, mas estamos usando o docker.

**Comment by iurygdeoliveira** [comment]
@1bertoh tudo bem.

Sim estamos usando o docker, mas você está executando um comando fora do container docker, pelo que estou vendo.
E desta forma precisa instalar as bibliotecas php dentro em seu computador, vou te passar um tutorial interessante para instalar o php em sua máquina no windows.

https://blog.schoolofnet.com/como-instalar-o-php-no-windows-do-jeito-certo-e-usar-o-servidor-embutido/

**Comment by iurygdeoliveira** [comment]
Veja se resolve e nos dê um feedback

**Comment by 1bertoh** [comment]
@iurygdeoliveira  Sim, consegui. Obrigado professor

**Comment by 1bertoh** [comment]
Eu também tive uns problemas envolvendo o SSL/TLS quando o comando envolvia links, esse fórum me ajudou caso alguém venha se deparar com o mesmo problema:
https://stackoverflow.com/questions/35249620/the-openssl-extension-is-required-for-ssl-tls-protection
