### ISSUE TITLE
conteiners não estão aparecendo 

### ISSUE THREAD

**Issue by Luizedcarvalho** [iurygdeoliveira/novos_caminhos#388]
como faço para ativar os conteiners 
![2020-09-29 (3)](https://user-images.githubusercontent.com/70111956/94714726-eaeb6980-0322-11eb-90bb-b3a9acc1b244.png)

**Comment by fernandoifto** [comment]
Verifique se o docker esta iniciado, o Docker desktop.

**Comment by josepereirakls** [comment]
BOA NOITE, CASO O SEU DOCKER ESEJA INICIADO E NÃO ESTAR ABRINDO OS CONTEINER, FACA O SEGUINTE.
 PRIMWEIRO PASSO, DESISTALE A INSTENÇÃO DO DOCKER DEPOIS INSTALE NOVAMENTE.
 ai " docker-compose up"

Caso não der certo segunda opção:
desistale o docker de sua maquina e depois instale novemente.
depois use o comando docker-compose up

E se não funcionar faça o terceiro passo,
FAÇA P MESMO PROCEDIMENTO DO PREIRO PASSO QUE VAI DAR CEERTO.

**Comment by iurygdeoliveira** [comment]
@Luizedcarvalho seu docker desktop parece não estar funcionando.

**Comment by GMeireles** [comment]
Estava com o mesmo erro, você tem permitir o comando docker ser executado sem dar o sudo, porque se não a extensão docker vai dar erro por falta de permissão no sistema, pra fazer isso eu executei os comandos:
$ sudo groupadd docker
(cria um grupo unix chamado docker)

$ sudo usermod -aG docker $USER
(adiciona o seu usuário ao grupo docker)

De poweroff no sistema e ligue novamente

após ligado execute:
$ newgrp docker 
(para ativar as mudanças nos grupos)

e tente ligar um container sem o sudo, como:
$ docker run hello-world

depois disso a minha extensão voltou a funcionar, caso o seu ainda não funcione, eu encontrei a minha solução no site do docker: [https://docs.docker.com/engine/install/linux-postinstall/](url), lá explica esses comandos e também caso eles não funcionem.

Espero ter ajudado!
