### ISSUE TITLE
COMEÇANDO DO ZERO

### ISSUE THREAD

**Issue by albertovasconcelos** [iurygdeoliveira/novos_caminhos#390]
Tive um problema a alguns dias com meu pc e por esse motivo tive que começar tudo quase que praticamente do zero. Fiz um fork do repositório novamente. Professor peço que aprove novamente.

Estou usando o Windows 10 pro versão 2004, com WSL 2 que permite que eu possa usar o Linux dentro da plataforma Windows. Instalei o Docker desktop e o Visual Studio com extensões PHP.

Estou tentando agora correr atras das aulas e atividades para tentar alcançar os demais.

@iurygdeoliveir

**Comment by iurygdeoliveira** [comment]
@albertovasconcelos tranquilo !
