### ISSUE TITLE
FORKADO

### ISSUE THREAD

**Issue by anildogomes** [iurygdeoliveira/novos_caminhos#392]
Forkey a pasta novos_caminhos do professor Iury. 
Estou executando atividades e tutoriais nele. 
Quando fizer o push deverei colocar a URL do professor Iury?

**Comment by anildogomes** [comment]
Na verdade, preciso atualizar. No tutorial não ficou claro. Vídeo 5.1

**Comment by tsartori** [comment]
De uma olhada na issue #323 
Conte aqui se conseguiu resolver seu problema

**Comment by iurygdeoliveira** [comment]
@anildogomes e ai resolveu ?

**Comment by anildogomes** [comment]
Não consegui entender por aqui. Mas no video de orientações da segunda avaliação sim.(rs).
