### ISSUE TITLE
Organizando branchs e commits

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#399]
Caros colegas e prof. @iurygdeoliveira e @fernandoifto. Estou enviando um print de meu github local e de meu github remoto que está 34 branchs atrasado. Eu percebo que existe algo desorganizado. Quais os comandos para organizar tudo? fico aguardando ajuda.

![atv_prog_web](https://user-images.githubusercontent.com/69798042/95015703-c3e3af00-0624-11eb-9ed1-0c167e1a6cab.png)
![atv_prog_web2](https://user-images.githubusercontent.com/69798042/95015713-cd6d1700-0624-11eb-9a76-927828393e6f.png)

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva tudo bem.

Na branch master não deveiria estar aparecendo ainda a pasta 03 - webdesing. 
Depois que liberei a segunda prova, deixei a branch master apenas com as questões da prova, e depois crie uma branch paralela chamada **feature/webdesing**

**Comment by iurygdeoliveira** [comment]
Tela da minha branch master

![image](https://user-images.githubusercontent.com/30157522/95025881-9c600700-0663-11eb-8495-4d51ff0d524a.png)

**Comment by iurygdeoliveira** [comment]
Tela da minha branch feature/webdesing

![image](https://user-images.githubusercontent.com/30157522/95025903-bb5e9900-0663-11eb-9831-e270ee875f47.png)

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva perceba que na branch master a pasta 03 - webdesign não aparece, mas na branch feature/webdesing a pasta 03 - webdesign é exibida.

**Comment by iurygdeoliveira** [comment]
Para deixar seu repositorio da forma como o meu, assista a aula 15.1, postada hoje. 

https://youtu.be/lKnDNPbO10Y

**Comment by jalexandrersilva** [comment]
Prof @iurygdeoliveira minha branch master encontra-se ainda no formato antigo.
Só a feature/webdesing que está mais atualizada.
Pra atualizar a master tenho que dar um finish feature?
Segui todos os passos e a branch mater e a feature webdesing encontram-se desatualizadas.
Quais comandos preciso?
![atv_prog_web](https://user-images.githubusercontent.com/69798042/95082487-7a14ca80-06f1-11eb-83f1-12da1a8fbc71.png)
![atv_prog_web2](https://user-images.githubusercontent.com/69798042/95082500-80a34200-06f1-11eb-88cd-5034dedcec54.png)

**Comment by iurygdeoliveira** [comment]
_Pra atualizar a master tenho que dar um finish feature?_

Não finalize ainda, pois estamos aguardando o prazo final 2º prova terminar, para darmos um merge nas duas branchs, pode manter o trabalho na feature/webdesing

**Comment by jalexandrersilva** [comment]
Então obrigado professor. Vou aguardar novas orientações, vou trabalhar com a feature webdesing até seu fechamento.
