### ISSUE TITLE
Não aparece os containers e aparece mensagem de erro do php 

### ISSUE THREAD

**Issue by lotharbenmuyal** [iurygdeoliveira/novos_caminhos#400]
![erro2](https://user-images.githubusercontent.com/69872804/95028799-4bf3a400-0679-11eb-8f2e-cc3fd73d2f62.png)

como posso resolver?

**Comment by lotharbenmuyal** [comment]
![erro2](https://user-images.githubusercontent.com/69872804/95028785-39796a80-0679-11eb-810b-ac28f290ef03.png)

**Comment by iurygdeoliveira** [comment]
@lotharbenmuyal tudo bem

A questão do PHP, você irá conseguir resolver com este tutorial:
 https://blog.schoolofnet.com/como-instalar-o-php-no-windows-do-jeito-certo-e-usar-o-servidor-embutido/

**Comment by iurygdeoliveira** [comment]
@lotharbenmuyal a questão do container, provavelmente seu docker-desktop não está inicializado. Ele precisa estar funcionando para a extensão docker funcionar corretamente dentro do vscode

**Comment by lotharbenmuyal** [comment]
![erro](https://user-images.githubusercontent.com/69872804/95131182-047e1e00-0734-11eb-9e96-fc0f98034eb5.png)
mesmo com o docker aberto, já fiz até o tutorial do docker q apareceu, ele n acha os contêiners

**Comment by lotharbenmuyal** [comment]
![erro](https://user-images.githubusercontent.com/69872804/95131443-72c2e080-0734-11eb-9ed1-1410fa229cf3.png)
aparece somente o docker tutorial

**Comment by iurygdeoliveira** [comment]
@lotharbenmuyal após esse processo, você realizou o comando docker-compose up dentro da pasta onde o arquivo docker-compose.yml está presente ?

![image](https://user-images.githubusercontent.com/30157522/95268261-58106a80-080d-11eb-82d1-47fbb9491513.png)

**Comment by iurygdeoliveira** [comment]
Ou seja, dentro da pasta www

**Comment by fernandoifto** [comment]
A alguns dias descobri com um aluno se vc clicar com o botão direito do mouse no arquivo docker-compose.yml aparece o comando para vc selecionar mesma coisa de dar o comando no terminal.

![Capturar](https://user-images.githubusercontent.com/8673558/95275374-af6b0680-081e-11eb-937e-c631a0533d0d.PNG)

**Comment by iurygdeoliveira** [comment]
Só complementando a extensão docker precisa estar instalada tbm.
