### ISSUE TITLE
Extensão google chrome para verificação de tags de semântica

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#402]
Prof. @iurygdeoliveira e @fernandoifto, teve uma parte nos vídeos de tags html que não vi. Qual é o nome da extensão que o prof. Iury utiliza pra verificar como está a semântica do código html? Procurei mas não encontrei.

**Comment by fernandoifto** [comment]
Qual a URL do video aproximadamente em que minuto?

**Comment by jalexandrersilva** [comment]
Vídeos 14.3 14.4 e 14. 5. Essa extensão abre um pop-up do lado superior direito mostrando as tags h1 até h5

**Comment by jalexandrersilva** [comment]
Já encontrei a extensão, é a HTML5 Outliner Oferecido por: Dominykas Blyžė. Reconheci pelo ícone

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva isso mesmo
