### ISSUE TITLE
LIVE TIRA DÚVIDAS DIA 08/10/2020 AS 20:00 

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/novos_caminhos#403]
Olá alunos, utilizar essa issue, para postar dúvidas para o dia da live.

**Comment by anildogomes** [comment]
Como responder a prova em questão por questão. Com outros exemplos(rs)

**Comment by luizcssilva** [comment]
Boa noite professor
![image](https://user-images.githubusercontent.com/72242273/95146341-f2ac7300-0753-11eb-99e3-488c96e19e46.png)
meu vscode não passar desta pagina, sempre da erro?

**Comment by luizcssilva** [comment]
Outro erro 
![image](https://user-images.githubusercontent.com/72242273/95148550-fe029d00-0759-11eb-8292-b8591962b5ff.png)
fico no aguardo...

**Comment by jalexandrersilva** [comment]
Prof @iurygdeoliveira vamos supor que eu tenha dois buttons em HTML. Os dois tem ao lado quantas vezes foi clicado. Qual código pra quando eu clicar o HTML guardar essa informação dentro de algum arquivo dentro do servidor?

**Comment by iurygdeoliveira** [comment]
> Prof @iurygdeoliveira vamos supor que eu tenha dois buttons em HTML. Os dois tem ao lado quantas vezes foi clicado. Qual código pra quando eu clicar o HTML guardar essa informação dentro de algum arquivo dentro do servidor?

Isso dai é feito com Banco de Dados, ainda vamos ver isso no curso.

**Comment by iurygdeoliveira** [comment]
> Outro erro
> ![image](https://user-images.githubusercontent.com/72242273/95148550-fe029d00-0759-11eb-8292-b8591962b5ff.png)
> fico no aguardo...

@luizcssilva o comando ls -la é especifico para linux.  Para utilizar os comandos equivalente, instale o git bash ou o cmder

**Comment by JPeeMP** [comment]
Corrigir a prova!
