### ISSUE TITLE
Duvida - Atividade 03 - Design Web. 

### ISSUE THREAD

**Issue by layla9810** [iurygdeoliveira/novos_caminhos#404]
Professor, é necessário sempre criar uma feature? Ou posso fazer na master ou na develop? 
Fico muita confusa com varias feature.

**Comment by fernandoifto** [comment]
É um padrão de mercado a forma que o professor esta fazendo use sempre a develop apenas quando finalizar sincronize a master.

**Comment by iurygdeoliveira** [comment]
@layla9810 as features, são utilizadas para criação e desenvolvimento de novas funcionalidades, e após o termino, vc as integra na develop, e com a branch release, você faz a integração na master.

**Comment by layla9810** [comment]
Ok! Obrigada.
