### ISSUE TITLE
Inscrições Next Level Week 3º Edição.

### ISSUE THREAD

**Issue by mgckaled** [iurygdeoliveira/novos_caminhos#405]
Participei da 2º edição e recomendo MUITO. Para quem não conhece é uma sequência de vídeos que demonstra a criação de um aplicativo web do começo ao fim, com o passo a passo. Na últimas edições eles não utilizaram PHP no desenvolvimento web, acredito que nesse não terá também. Entretanto, há outras ferramentas web bem interessantes.

O evento é fornecido de forma GRATUITA pela [https://rocketseat.com.br/](https://rocketseat.com.br/). 

**Inscrições**: [https://nextlevelweek.com/inscricao/3](https://nextlevelweek.com/inscricao/3)
**Período**: 12 a 18 de outubro

Obs: Não tenho nenhum vínculo comercial com eles. Apenas fazendo a divulgação porque é muito interessante para quem está começando com programação e desenvolvimento web.

**Comment by fernandoifto** [comment]
Quem tiver tempo de participar é uma boa infelismente não terei tempo de participar.

**Comment by iurygdeoliveira** [comment]
@mgckaled já fiz minha inscrição na 3º NLW

**Comment by danielcanoli** [comment]
@mgckaled gostei, vou me inscrever tb!
