### ISSUE TITLE
Icones do Git Flow Ocultos

### ISSUE THREAD

**Issue by souzalimarafael** [iurygdeoliveira/novos_caminhos#408]
Professor, o ícone do git flow a esquerda do VScode não está visível para mim, porém, já está instalado.
Me dá um help por favor.

**Comment by iurygdeoliveira** [comment]
@souzalimarafael me manda um print da tela, deixa eu ver

**Comment by fernandoifto** [comment]
Uma coisa que notei é que não adianta apenas instalar a extensão do git flow vc tem que ter dado o comando git flow init antes para a extensão aparecer.

**Comment by souzalimarafael** [comment]
![gitflow_Print](https://user-images.githubusercontent.com/71615231/95339619-a152cf80-088a-11eb-817b-6bb5910b550d.png)

**Comment by souzalimarafael** [comment]
Tentei iniciar com o git flow init, mas continua não aparecendo

**Comment by Patryciah** [comment]
Aconteceu o mesmo comigo, porém, ao reiniciar, ainda não aparece o ícone.

**Comment by fernandoifto** [comment]
Já executou o comando **git flow init** antes?

**Comment by Patryciah** [comment]
@fernandoifto  sim, ja fiz todos os procedimentos sugeridos aqui, mas não dá certo.

Mensagem que aparece
git flow init
Fatal: Working tree contains unstaged changes. Aborting.

**Comment by Patryciah** [comment]
E depois disso, as configurações  e o ícone continuam ocultos.

**Comment by fernandoifto** [comment]
Provavelmente vc esta usando o PowerShell tem que usar o cmder ou o git bash.

**Comment by Patryciah** [comment]
@fernandoifto não é esse o problema. Estou confusa, não tem vídeo ensinando sobre o git flow?  olha o print e me ajude a entender o que está errado, por favor? Estou totalmente perdida. kkkkkk
![Captura de tela de 2020-10-08 20-48-35](https://user-images.githubusercontent.com/72561626/95524458-d6a10f80-09a7-11eb-8919-146d2a523d30.png)

**Comment by fernandoifto** [comment]
dar um git branch

**Comment by Patryciah** [comment]
@fernandoifto onde estão as orientaçoẽs sobre o git flow? preciso ver com calma para entender, e eu não encontrei videos na plataforma, vi que  tiveram alguns problemas com  alguns vídeos, estão em outra plataforma fora do classroon?

**Comment by fernandoifto** [comment]
https://www.youtube.com/watch?v=DkVMe66XIdQ foi nesse vídeo.
