### ISSUE TITLE
Erros vs code 

### ISSUE THREAD

**Issue by pedro21900** [iurygdeoliveira/novos_caminhos#409]
![Screenshot_20201006-130223_Remote Desktop](https://user-images.githubusercontent.com/61558221/95227345-64c49c80-07d4-11eb-8cdc-e63b20263f3d.jpg)

**Comment by AdennyFernandes** [comment]
Companheiro teste os procedimentos deste vídeo. Vc tem que editar o caminho do php, dentro da variável path. Bons estudos.
https://youtu.be/vBMvR8oow-4?t=465
Página do php https://windows.php.net/download#php-7.4
Extraia o arquivo e coloque no diretório C:
Baixe VC15 x64 Non Thread Safe (Se caso o seu sistema for 64bits)
ou VC15 x86 Thread Safe (Se caso o seu sistema for 32bits)

**Comment by danielcanoli** [comment]
@pedro21900 conseguiu avançar com as dicas do @AdennyFernandes ?
