### ISSUE TITLE
Erro vs code , alguém pode me ajudar .l?

### ISSUE THREAD

**Issue by pedro21900** [iurygdeoliveira/novos_caminhos#410]
![Screenshot_20201006-130223_Remote Desktop](https://user-images.githubusercontent.com/61558221/95227345-64c49c80-07d4-11eb-8cdc-e63b20263f3d.jpg)

**Comment by AdennyFernandes** [comment]
Companheiro teste os procedimentos deste vídeo. Vc tem que editar o caminho do php, dentro da variável path. Bons estudos.
https://youtu.be/vBMvR8oow-4?t=465

**Comment by iurygdeoliveira** [comment]
Isso mesmo @AdennyFernandes !

**Comment by AdennyFernandes** [comment]
Prezado Mestre. Satisfação. Obrigado pelo apoio moral. Agradecido pela
atenção. Estou aprendendo muito.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em ter., 6 de out. de 2020 às 20:07, Iury Gomes de Oliveira <
notifications@github.com> escreveu:

**Comment by santaali** [comment]
![Capturar](https://user-images.githubusercontent.com/70075977/96256976-f5973700-0f8f-11eb-9e16-1c1acf07db87.PNG)

Fiz os passos indicados, mas deu esse erro o meu php está nessa pasta que identifiquei.
