### ISSUE TITLE
Professor a prova está muito difícil. Estou com muitas dúvidas.

### ISSUE THREAD

**Issue by AdennyFernandes** [iurygdeoliveira/novos_caminhos#411]
Prezados Professores.

As questões apresentam uma situação, que é dada de acordo com as function da linguagem, que no caso é php.

As questões pedem para desenvolver um determinado código de acordo com os parâmetros pedidos.
Algum tipo de valor é dado, para se ter o retorno em questão. 

Minha dúvida é sobre:
-Terei que inserir o código como resposta da pergunta dentro da avaliação? 
-As respostas das questões é o desenvolvimento do código? Mostrar o código?
Exemplo:
Desenvolvo o código, realizo o teste do código na página http://phptester.net/
depois copio e colo na questão da prova?

OBS:
Estou tentando resolver a prova que está no seu repositório, sobre 10 questões.
Não sei se é a mesma avaliação que vai para o boletim.

**Comment by iurygdeoliveira** [comment]
Minha dúvida é sobre:
-Terei que inserir o código como resposta da pergunta dentro da avaliação?
**Apenas o valor retornado**

-As respostas das questões é o desenvolvimento do código? Mostrar o código?
**Apenas o valor retornado**

**Comment by AdennyFernandes** [comment]
Grato. Obrigado pela atenção.

**Comment by AriociCarlosAmorim** [comment]
olá professor, sou muito iniciante em programação, compreendo um pouco de algoritimos, inclusive assisti todas as aulas que o senhor nos enviou, mas não estou encontrando em nenhuma aula material para responder a avaliação, não consigo construir os códigos, como por exemplo, não encontrei nas aulas a função "almostIncreasingSequence", não consigo descobrir o que ela faz.
seria possível me informar algum material que eu possa verificar para eu responder a avaliação?

**Comment by iurygdeoliveira** [comment]
@AriociCarlosAmorim você deverá responder as questões dentro do proprio vscode, no material que foi disponibilizado via github.  Basta você realizar o git pull apartir do repositorio original na branch master, que o material é baixado automaticamente para seu computador.
