### ISSUE TITLE
Atalho para inserir comentários no código html

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#412]
Prof @iurygdeoliveira o senhor digitou a palavra CABEÇALHO E EXECUTOU UM ATALHO PRA FOCAR COMO COMENTÁRIO, ELE INSERE AUTOMATICAMENTE OS SINAIS E A SETA. Qual é esse atalho por favor

**Comment by iurygdeoliveira** [comment]
E qual vídeo ? Em qual parte ?

**Comment by jalexandrersilva** [comment]
Mestre @iurygdeoliveira Aqui vão uns exemplos..

digitou CABEÇALHO e com o atalho ficou <----- CABEÇALHO ----->
Digitou FIM DE CABEÇALHO e com o atalho ficou <----- FINAL DE CABEÇALHO ----->

**Comment by iurygdeoliveira** [comment]
CTRL + /

**Comment by jalexandrersilva** [comment]
Obrigado prof @iurygdeoliveira, sem querer incomodá-lo, o senhor tem uma lista dos mais utilizados?

Se bem que os snippers são ótimos, mas quais os principais atalhos? Obrigado e parabéns a toda equipe do curso.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva na verdade, esses comandos eu configuro os meus no VScode, e alguns que são padrões do VSCODE eu mantive, como o CTRL + /   e o CTRL + D.

O VScode tem essa filosofia, vc constroi seu ambiente de programação. 

Se você quiser olhar os comandos acessa a opção de SHORTCUTS, e lá vc vai encontrar todos os comandos habilitados no VSCODE.

**Comment by jalexandrersilva** [comment]
Obrigado
