### ISSUE TITLE
Problemas com o Docker

### ISSUE THREAD

**Issue by ghost** [iurygdeoliveira/novos_caminhos#413]
Instalei a extensão, porém, surge mensagem de erro informando que o docker não está instalado.
Como resolver isso?

**Comment by fernandoifto** [comment]
Prints

**Comment by Patryciah** [comment]
Não me lembro como adicionar print aqui. Estou pesquisando.

**Comment by fernandoifto** [comment]
Clica nessa parte que pintei de vermelho onde vc escreve o texto.

![Captura de tela de 2020-10-07 16-18-33](https://user-images.githubusercontent.com/8673558/95377619-353b9000-08b9-11eb-86a0-8cbcc8812818.png)

**Comment by Patryciah** [comment]
![Captura de tela de 2020-10-07 15-58-51](https://user-images.githubusercontent.com/72512737/95379084-42f21500-08bb-11eb-804b-3fb13b4e6838.

**Comment by Patryciah** [comment]
![Captura de tela de 2020-10-07 16-39-39](https://user-images.githubusercontent.com/72512737/95379443-c7449800-08bb-11eb-9d06-caf2b38fb6c1.png)

**Comment by AdennyFernandes** [comment]
Prezado vc precisa instalar o Docker na sua área de trabalho. 
Docker Desktop https://www.docker.com/get-started. Instalar apenas a extensão não irá funcionar.
Depois configure seu container no Docker. Pesquise no Youtube, pq não sei qual o sistema operacional vc está usando. No meu caso eu uso Windows 10 versão 1909 64 bits, baixei e instalei o Docker no pc. Cadastre uma conta no Docker. Vc precisa dar Play no seu container do Docker para o VC Code, reconhecer. Vc terá que baixar todas as imagens, através de linhas de comando, dentro do seu terminal. 
O professor Yuri tem o vídeo ensinando, mas caso ajude veja esse vídeo tb:
https://youtu.be/W8x8Lln3i5A?t=1
Bons estudos.

**Comment by fernandoifto** [comment]
Ela usa o Linux não tem o Docker Desktop acredito que vc tenha que executar o comando **sudo usermod -aG docker username**

Execute os comandos: docker -v e docker-compose -v apos nos mande o print da tela.

**Comment by iurygdeoliveira** [comment]
@ghost Se estiver mesmo usando linux, após dar o comando que o @fernandoifto citou, você necessita deslogar e logar em sua sessão novamente, e deve funcionar.

**Comment by Patryciah** [comment]
@fernandoifto, @iurygdeoliveira  estão instaladas as versões instaladas. Porém não compreendi ainda os procedimentos e configurações. Estou atrasada com o cronog rama devido a problemas de saúde, por isso peço desculpas por estar voltando a temas já ensinados, para pedir orientação.
![Captura de tela de 2020-10-08 20-48-35](https://user-images.githubusercontent.com/72561626/95529065-592dcd00-09b0-11eb-833f-6a7e28cb6b0d.png)

**Comment by fernandoifto** [comment]
Apareceu a extensão? executou o comando **sudo usermod -aG docker username**

**Comment by Patryciah** [comment]
Perdoem-me professor **@iurygdeoliveira**  e **@fernandoifto**, eu havia perdido o bloco de vídeos 06, por isso estou tão perdida. estou vendo agora e  caso haja ainda alguma dúvida, volto a postar aqui, está bem? Peço novamente desculpas, mas não foi desatenção, é que com as medicações de meu tratamento, eu acabo passando por confusões e desorientação. Mas, sigamos em frente, quero alcançar a turma.

**Comment by iurygdeoliveira** [comment]
@Patryciah tudo bem, patricia, estaremos aqui.
