### ISSUE TITLE
Porque o e-mail não aparece no final da aula no vídeo 10.7

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#417]
Refiz o código algumas vezes na tentativa de entender o motivo que fez o e-mail não aparecer no final da aula em que através das funções nativas de _array_implode_ e _array_explode_ eram retiradas da impressão (echo) no **exemplo prático** final as chaves. 

![image](https://user-images.githubusercontent.com/69777395/95487077-3c6ea680-096a-11eb-8677-0f5e3e80e791.png)

(...)

![image](https://user-images.githubusercontent.com/69777395/95487620-f0703180-096a-11eb-8134-ed3e93039087.png)

**Comment by iurygdeoliveira** [comment]
> Refiz o código algumas vezes na tentativa de entender o motivo que fez o e-mail não aparecer no final da aula em que através das funções nativas de _array_implode_ e _array_explode_ eram retiradas da impressão (echo) no **exemplo prático** final as chaves.
> 
> ![image](https://user-images.githubusercontent.com/69777395/95487077-3c6ea680-096a-11eb-8677-0f5e3e80e791.png)
> 
> (...)
> 
> ![image](https://user-images.githubusercontent.com/69777395/95487620-f0703180-096a-11eb-8134-ed3e93039087.png)

@iareis nessa imagem o atributo href, não é exibido mesmo para o usuario, apenas o conteúdo que fica dentro da tag a.  

A execução é assim mesmo,

**Comment by iareis** [comment]
Na verdade não entendi o motivo, pois no exemplo anterior aparece o e-mail. Porém como não vi as demais aulas ainda, pode ser falta de entendimento do conteúdo como um todo. Como foi informado ser um conteúdo mais avançado, devo aguardar um pouco mais. Obrigado.

**Comment by iareis** [comment]
Agora entendi com a explicação na LIVE.

**Comment by iareis** [comment]
RESPONDIDA.
