### ISSUE TITLE
ambiente Docker

### ISSUE THREAD

**Issue by Agenildo** [iurygdeoliveira/novos_caminhos#418]
seria possível disponibilizar pdf com o passo a passo para montar um ambiente de desenvolvimento do zero? A exemplo do ambiente que foi criado.
Pergunto pois se hoje precisasse faze-lo hoje  teria grandes problemas.

**Comment by fernandoifto** [comment]
Apenas as aulas mesmo e formato de vídeo.

**Comment by iurygdeoliveira** [comment]
@Agenildo dá uma olhada na issue #343 . Você encontrar muito material, produzido pela comunidade do curso.
