### ISSUE TITLE
ambiente de desenvolvimento

### ISSUE THREAD

**Issue by Agenildo** [iurygdeoliveira/novos_caminhos#419]
Seria possível disponibilizar pdf  com o passo a passo explicado para subir um ambiente de desenvolvimento a partir do zero?
Devido a problemas com as versões instaladas passei mais tempo tentando resolver erros do que treinando.

**Comment by fernandoifto** [comment]
Acredito que não será disponibilizado em pdf. até para fazer isso teria que ter um pdf para o linux ou para o windows 10 e outro para o windows 7. o material são os videos do classroom e a Issues com as duvidas.

**Comment by iurygdeoliveira** [comment]
@Agenildo dentro do material disponibilizado via github, existe esse tutorial, não é direcionado para a versão windows 7, mas para windows 10, e neste ponto você terá que fazer as adaptações. Esse tempo que o você gastou para resolver problemas, é parte do aprendizado mesmo, todo desenvolvedor passa por isso.
