### ISSUE TITLE
Continuo tendo problemas com o git flow

### ISSUE THREAD

**Issue by ghost** [iurygdeoliveira/novos_caminhos#421]
Estou tendo problemas com meu git flow. Mensagens de erro abaixo. Estou usando ubuntu versão 20.4 lts. Preciso de ajuda. @fernandoifto 
![Captura de tela de 2020-10-09 12-12-48](https://user-images.githubusercontent.com/72561626/95602316-207f0980-0a2b-11eb-8c76-5cb41711aca3.png)

**Comment by iareis** [comment]
Oi, boa noite. Uso o windows, mas gostaria de ver alguns prints de outros comandos... como **git status, git remote -v e git branch**, pois se vc já tentou várias vezes podem tem ficados resíduos que podem estar dificultando a expertise do vscode, isso pelo que andei lendo quando tive muitos problemas com o GIT FLOW a algum tempo...

**Comment by fernandoifto** [comment]
Isso mesmo esses prints que o @iareis  falou é necessario para entender melhor os problemas, as vezes você vai ter que apagar a pasta .git e recomeçar novamente, essa pasta .git fica oculta no Linux o atalho para ver é CTRL + H.
