### ISSUE TITLE
VS code php mensagem

### ISSUE THREAD

**Issue by Agenildo** [iurygdeoliveira/novos_caminhos#423]
Boa noite!
no canto inferior esquerdo  aparece mensagem sobre  a instalação do PHP.
Como posso resolver?

![Captura de tela de 2020-10-09 20-24-21](https://user-images.githubusercontent.com/20821106/95639553-40382100-0a6f-11eb-8d74-fcb5989b3141.png)

**Comment by iareis** [comment]
Se ainda não instalou a extensão PHP Intelephense, sugiro que o faça.
Caso já tenha instalado, você pode acessar os botões que o próprio sistema sugere e verificar as opções disponíveis.

![image](https://user-images.githubusercontent.com/69777395/95646179-2f51d480-0a9c-11eb-81b4-25eb58af8bf3.png)

**Comment by rafabritu** [comment]
Faz a reinstalação das bibliotecas do PHP e também da extensão PHP Intellesense
Bibliotecas do PHP : https://www.youtube.com/watch?v=oowi4ELroWM

**Comment by iurygdeoliveira** [comment]
@Agenildo é como o @iareis e o @rafabritu informarm.  Além disso, não deixei de dar um olhadinha na issue #343 tem muita informação boa por lá.
