### ISSUE TITLE
Os Links das aulas em sua conta no youtube Prof. Iury. Apenas os alunos tem acesso?

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#424]
Este assunto foi comentado não lembro se na LIVE ou em algum dos grupos whatsapp/Telegram. Mas refaço a pergunta, pois agora estava organizando meu tempo para assistir as aulas e resolvi organizar em uma planilha o tempo necessário para cada **atividade/aula/vídeo/módulo**, pois já havia rascunhado numa folha de papel e até enviado foto no whatsapp. 

Acabei fazendo uma planilha resumindo em HTML os links das aulas dos módulos 2 e 3 com o tempo em minutos de cada aula e o tempo total por módulo. Ainda não utilizei scripts para os cálculos, porém pensei nisso enquanto organizava a tabela.

Coloquei o arquivo por enquanto em um **repositório privado**.

Minha pergunta é, SE EU DEIXAR O REPOSITÓRIO PÚBLICO, qualquer pessoa terá acesso aos vídeos das aulas?
Ou apenas nós que estamos cadastrados no GOOGLE CLASSROOM? 

Minha idéia é facilitar a minha organização de tempo e a de outros que possam estar precisando de algo assim além do que já existe no https://classroom.google.com/w/MTQyMjE1MjA4MTE2/t/all...

![image](https://user-images.githubusercontent.com/69777395/95645878-96ba5500-0a99-11eb-874d-57a2dd457fec.png)

**Comment by iareis** [comment]
![image](https://user-images.githubusercontent.com/69777395/95668605-a5ae0f80-0b4c-11eb-848e-14361e1fa2f3.png)

**Comment by rafabritu** [comment]
Bacana ein, boa ideia!!

**Comment by iurygdeoliveira** [comment]
@iareis tudo bem.  Muito legal isso, parabens pela dedicação.

Contudo, não coloque isso como repositório publico, pois se houver muitas perguntas de dúvidas, não saberemos distinguir entre alunos e ouvintes, e desta forma, o tempo que queremos gastar com vocês, estaremos gastando com quem não é aluno. 

Mas após o termino do curso, pode colocar em um repositório publico sim

**Comment by iareis** [comment]
Entendido.

**Comment by iareis** [comment]
@iurygdeoliveira repositório alterado para PRIVADO!!!!
