### ISSUE TITLE
Mysql no docker

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#425]
Bom dia prof. @iurygdeoliveira , estou estudando um tutorial de banco de dados e ele mandou instalar o mysql. 

Pensei em instaciar o mysql com o docker, mas estou com algumas dificuldades práticas.

Eu cheguei até esse ponto das telas abaixo. As perguntas é: como enxergar o mysql no navegador?
Onde chegar pra criar database e criar tabelas?
Como conseguir enxergar a instância do mysql dentro do meu pc?
Agradeço a atenção.
![atv_prog_web](https://user-images.githubusercontent.com/69798042/95656453-e83c0180-0ae4-11eb-96b4-3d774294dd03.png)
![atv_prog_web2](https://user-images.githubusercontent.com/69798042/95656457-ec681f00-0ae4-11eb-82ba-47bbf81f0879.png)

**Comment by jalexandrersilva** [comment]
mais 2 telas co o problema
![atv_prog_web](https://user-images.githubusercontent.com/69798042/95660766-66f26800-0b00-11eb-87ac-de92f9b8806b.png)
![atv_prog_web2](https://user-images.githubusercontent.com/69798042/95660769-6c4fb280-0b00-11eb-8bb2-58b7cedad18b.png)

**Comment by jalexandrersilva** [comment]
Prof. @iurygdeoliveira passei da parte da manhã até agora e só consegui agora, com ajuda de respostas no github. 
Digitei o comando abaixo, que redirecionou o 172.17.0.2 para o localhost....
**docker run --rm -dit -e MYSQL_ROOT_PASSWORD=pass --name mysql2 -p 3306:3306 mysql:latest**
Mas se eu quisesse o servidor no endereço 172.17.0.2 que é o padrão, como eu deveria fazer?

**Comment by fernandoifto** [comment]
melhor esperar os videos com essa aula, existe varias imagens de banco de dados não sabemos o que o professor ira usar.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva parabens pelo dedicação. Iremos utilizar sim o mysql dentro do docker. Mas este momento ainda vai chegar, é na próxima disciplina.
