### ISSUE TITLE
Processo de terminal terminado - Código de saída 127

### ISSUE THREAD

**Issue by santaali** [iurygdeoliveira/novos_caminhos#426]
O terminal não está abrindo.

![image](https://user-images.githubusercontent.com/70075977/95680633-6f56ab80-0bb1-11eb-8119-a2d3e5274fb5.png)

**Comment by fernandoifto** [comment]
Você deixou dois terminais apague a linha 15 ou as linhas 16, 17, 18 e 19.

**Comment by santaali** [comment]
Resolvido.
