### ISSUE TITLE
Erro na branch feature/webdesing

### ISSUE THREAD

**Issue by theteustav** [iurygdeoliveira/novos_caminhos#427]
Olá

Eu não estou conseguindo trazer a branch feature/webdesing através do comando `git flow feature track webdesing`.
Alguém pode me ajudar?

![ERRO_Branch](https://user-images.githubusercontent.com/69881673/95690053-64207180-0beb-11eb-828b-99a7cdba87c4.png)

**Comment by jalexandrersilva** [comment]
bom dia colega, bom dia professores.
Companheiro, hoje pela manhã eu percebi o quanto estava desatualizado.... então fui fazendo algumas tentativas que resolveram.... aí voce é quem diz por onde já entende pra dar prosseguimento.

Eu apaguei a pasta novos_caminhos e dei um
git clone endereco http do repositorio_aluno
depois
git init flow
depois
git remote rename origin repositorio_aluno   (para modificar o nome do repositório clonado, que é o do aluno o forkado,
git remote add origin enredeço_repositorio_prof.iury
depois que voce define o origin remoto
git pull

digite git remote -v
deve haver 2 branchs, origin, repositorio_aluno 
Se executar git branch   - vai ver a develop e a master
ai é só dar um checkout no feature
git checkout feature/webdesing

o git graph pode ajudar a voce ver a branch feature/webdesign, se não consegui avise por favor pra gente ou o prof. ajudar... abraços

**Comment by santaali** [comment]
![git flow trash](https://user-images.githubusercontent.com/70075977/96141089-09cb2d80-0ed7-11eb-8472-a4ee1a622808.PNG)

O meu está dando esse erro.

**Comment by jalexandrersilva** [comment]
o git push que voce executou é pra atualizar seu repositorio de aluno

execute o git remote -v para ver aonde apontam as branchs. Olhe os resultados no meu:
origin  https://github.com/iurygdeoliveira/novos_caminhos.git (fetch)
origin  https://github.com/iurygdeoliveira/novos_caminhos.git (push)
repositorio_aluno       https://github.com/jalexandrersilva/novos_caminhos.git (fetch)
repositorio_aluno       https://github.com/jalexandrersilva/novos_caminhos.git (push)

eu renomeei o origin que aponta para o meu repositório para o nome repositorio_aluno
Depois dei o comando git remote add origin https://github.com/iurygdeoliveira/novos_caminhos.git

Depois desse add, voce executa o git pull.... o git pull , de acordo com esse [link explicativo](https://www.atlassian.com/br/git/tutorials/syncing/git-pull#:~:text=O%20comando%20git%20pull%20%C3%A9,de%20colabora%C3%A7%C3%A3o%20baseados%20em%20Git.), são dois comandos, o git fetch e o git merge.

Resumindo, veja  no git remote -v se está tudo apontado direito. Mande um print
Depois de incluir voce dá o git pull e não o git push

Tenta ai

**Comment by iurygdeoliveira** [comment]
Pessoal, só lembrando que comando git flow feature track webdesing, só necessita fazer uma única vez.

**Comment by iurygdeoliveira** [comment]
As próximos downloads, poderão utilizar o git pull
