### ISSUE TITLE
Correção Avaliação - Introdução aos algoritmos e programação

### ISSUE THREAD

**Issue by mgckaled** [iurygdeoliveira/novos_caminhos#429]
Existe uma diferença na nota da imagem do email e a nota da avaliação (formulário) Segue os prints abaixo. Gentileza verificar se algo está errado. Há um aluno (Jo Lopes Queiroz) que descreveu a mesma situação nos comentários do mural.  Desde já agradeço. 

![Screenshot_5](https://user-images.githubusercontent.com/58960702/95922597-00807a80-0d8a-11eb-8b5a-bdbf3335a0af.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/58960702/95922600-024a3e00-0d8a-11eb-8e5e-c4e9096364e1.jpg)

**Comment by jalexandrersilva** [comment]
Estou na mesma situação

**Comment by iurygdeoliveira** [comment]
Bom dia @mgckaled e @jalexandrersilva a prova está reaberta para correção

**Comment by wandersouzasantos** [comment]
Todos os alunos são obrigados a refazer?

**Comment by iurygdeoliveira** [comment]
@wandersouzasantos não refazer a prova, é apenas para facilitar a correção das notas. A equipe fará, mas como são muitos alunos isso poderá demorá um pouco.
