### ISSUE TITLE
Correção Avaliação - Introdução aos algoritmos e programação

### ISSUE THREAD

**Issue by L-WILIAN1987** [iurygdeoliveira/novos_caminhos#430]
![nota da avaliação](https://user-images.githubusercontent.com/69942630/96060246-5d516300-0e66-11eb-8a5c-af2a7dc000f6.JPG)
![nota avaliação 2](https://user-images.githubusercontent.com/69942630/96060251-5f1b2680-0e66-11eb-8485-cda7e5509991.JPG)

Boa Noite, Prof. Iury, 

Por favor, poderia me informar qual é a nota correta?

Att;

**Comment by iurygdeoliveira** [comment]
@L-WILIAN1987 bom dia, prova está reaberta para correção
