### ISSUE TITLE
Contribuição

### ISSUE THREAD

**Issue by jamilempc20** [iurygdeoliveira/novos_caminhos#432]
Professor, observei que até hoje minha contribuição não apareceu no seu repositório. 
Eu consegui subir e fiz  pull requests

https://photos.app.goo.gl/xvncdBUYy8XHbrXf7

https://photos.app.goo.gl/69vmzGxvVFzQx9Ca9

**Comment by iurygdeoliveira** [comment]
@jamilempc20 o que provavelmente aconteceu, foi que sua contribuição deve ter sido feita em alguma outra pasta diferente da pasta contribuição, e todas as contribuições foras desta pasta, eu estou vetando, para evitar que o material do curso fique desorganizado. Teve aluno que alterou 250 arquivo .... kkkk .... e quando fez o pull request, eu tive que bloquear né. Mas em minhas anotações no meu diário, todos os alunos que fizeram o pull request, foram anotados.

Mas se fizer uma adição dentro da pasta contribuição, eu vou incluir ela aqui. Blz ?
