### ISSUE TITLE
Problemas git clone e sincronização

### ISSUE THREAD

**Issue by ghost** [iurygdeoliveira/novos_caminhos#433]
Estou tendo problemas com git clone e sincronização git/ Github, tanto que nem consegui até hoje lançar a tarefa contribuição. Quando faço git commit, as mudanças vão para meu repositório de testes no Github e não para o repositório forkado. E depois que faço git clone, não consigo mais realizar nenhum comando git para o repositório remoto. Precisa de ajuda, pois acredito que preciso dessas funções ativas e corretas para seguir com as atividades.  Me ajudem por favor???

**Comment by jalexandrersilva** [comment]
Olá, tem uma resposta explicativas na issue #427. Leia ela toda e tente resolver seu problema

**Comment by Patryciahalaz** [comment]
olá, agradeço, vou verificar.
