### ISSUE TITLE
Aula 11.4: Nome da máquina (vendor-name) no composer.json

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#434]
Não entendi como deve ficar o "name" (nome da minha máquina) dentro do composer.jason...**aula 11.4**

![image](https://user-images.githubusercontent.com/69777395/96207771-644da380-0f42-11eb-85d8-9ba602413bb7.png)

**Comment by iareis** [comment]
Ao que parece, dando continuidade a aula, está funcionando o **autoload**, mas aparece esta mensagem sempre que tento um upload.

![image](https://user-images.githubusercontent.com/69777395/96273333-9b08d580-0fa5-11eb-9e3e-14d67cf63868.png)

**Comment by iareis** [comment]
Testei também com o PowerShell, mas nem abre campo...

![image](https://user-images.githubusercontent.com/69777395/96274470-e5d71d00-0fa6-11eb-9c98-c093e43748c7.png)

**Comment by iareis** [comment]
User@DESKTOP-BAG0H99 **MINGW64** /c/xampp/htdocs/IAR
$

No bash também aparece este **MINGW64** que no site http://www.mingw.org/ diz ser:

 MinGW (Minimalist GNU for Windows) é uma versão portada para Microsoft Windows do conjunto de ferramentas GNU. Este software inclui um conjunto de arquivos cabeçalho para a API do Windows que permite aos desenvolvedores usar o GCC para criar programas nativos em Windows sem precisar contar com uma emulação em tempo real de um sistema Unix-like.

MSYS (acrônimo para minimal system) é um pacote que fornece um ambiente simples de shell, suportanto o padrão POSIX suficientemente para permitir a execução de scripts autoconf. Ambos os pacotes foram originalmente ramificações do Cygwin, que fornece um suporte Unix-like maior para Windows. Ambos os pacotes são software livre; os cabeçalhos Win32 estão disponíveis em domínio público enquanto as ferramentes estão em GNU General Public License

O MSYS2, junto com a porta do compilador Mingw-w64, converte o código Unix em binários nativos do Windows. Isso tem a vantagem de que os usuários do software portado podem permanecer no Windows, em vez de alternar entre dois sistemas operacionais.

**Comment by iareis** [comment]
![image](https://user-images.githubusercontent.com/69777395/96279777-84667c80-0fad-11eb-9599-d28b68105709.png)

Retirei todo o código... e a descrição do erro parece ser apenas 1 string, mas substituir por qual caractere?
Ao salvar o arquivo ele automaticamente elimina a vírgula.

**Comment by iurygdeoliveira** [comment]
@iareis existe um padrão a ser seguido. 

![image](https://user-images.githubusercontent.com/30157522/96287678-aca7a880-0fb8-11eb-9aea-c98036f8365c.png)

Nome do usuario/nome da pasta

**Comment by iareis** [comment]
Prof. @iurygdeoliveira eu segui este padrão conforme a aula e o erro que apresentou para o Sr. também, mas de acordo com a linha abaixo:

User@DESKTOP-BAG0H99 MINGW64 /c/xampp/htdocs/IAR
$

Como o Sr. acha que deveria ficar?
Conforme meu primeiro print, já tenter **User/DESKTOP-BAG0H99** e não aceitou.
$

**Comment by iareis** [comment]
Agora com novas tentativas e verificando a mensagem de erro, o que significa o [2,13] ao final do erro? Poderia ser um string entre as linhas 2 e 13?

![image](https://user-images.githubusercontent.com/69777395/96293713-8e927600-0fc1-11eb-8ffd-34cf71f3646f.png)

**Comment by iareis** [comment]
Achei o erro. O nome deve ser todo em letras minúsculas...

![image](https://user-images.githubusercontent.com/69777395/96296702-124e6180-0fc6-11eb-8b55-a18f3ef42b22.png)

![image](https://user-images.githubusercontent.com/69777395/96296744-285c2200-0fc6-11eb-8045-09ed569c43c5.png)

**Comment by iareis** [comment]
Depois de toda esta pesquisa para resolver mais este problema bem que eu também poderia ter aquele ponto extra.

**Comment by iurygdeoliveira** [comment]
@iareis tba acho
