### ISSUE TITLE
Problema com Git flow feature

### ISSUE THREAD

**Issue by LisandraFarias** [iurygdeoliveira/novos_caminhos#437]
Olá, pessoal. 
Não estou conseguindo prosseguir com o git flow indicado no vídeo 6.8. Já pesquisei em várias fontes o porquê dessa mensagem estar aparecendo, fiz algumas alterações no repositório, mas o problema persiste. 
![Git flow feature](https://user-images.githubusercontent.com/70919764/96385293-562d9c00-1169-11eb-97d6-ef22db432e2e.png)
![Git flow init](https://user-images.githubusercontent.com/70919764/96385297-56c63280-1169-11eb-85bb-559965e9a299.png)

**Comment by fernandoifto** [comment]
O Git Flow já foi iniciado digite git branch.

**Comment by iurygdeoliveira** [comment]
@LisandraFarias podemos marcar um atendimento remoto, também para auxiliar.

**Comment by LisandraFarias** [comment]
Sim ele já havia sido inciado, por isso não entendi a mensagem. Pesquisei mais um pouco e segui conforme a mensagem de reinicialização do git flow. Esqueci de tirar os prints, mas consegui iniciar a feature e a release.

Fiz conforme indica nesse vídeo: https://www.youtube.com/watch?v=wzxBR4pOTTs&t=1223s

Acredito que agora conseguirei seguir com as demais atividades, pois esse problema e a instalação do Docker atrasaram minhas entregas. Obrigada @fernandoifto  e @iurygdeoliveira.

**Comment by iurygdeoliveira** [comment]
@LisandraFarias blz !
