### ISSUE TITLE
Como sair do erro fatal: Invalid value for pull.rebase: true. ?

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#440]
Fiz algo e não estou conseguindo identificar a fonte do problema. 
Este tentando um **git pull** na branch main, mas retorna erro **fatal: Invalid value for pull.rebase: true.** (marquei com "1" na imagem)...

Criei um sub-diretório testes para tentar identificar, mas retorna outro erro. (marquei com "3" na imagem)...

Na imagem abaixo marquei com "2" onde idendifica que tenho commits em conflito, os quais não estou conseguindo acertar. 
_Your branch and 'github/main' have diverged,
and have 3 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)_

![image](https://user-images.githubusercontent.com/69777395/96593935-76bc3a00-12c0-11eb-99bf-d2bda1d1362a.png)

Li sobre o *git rebase* mas não entendi bem seu funcionamento e fiquei preocupado em piorar mais. Mas li que terei que retornar o origin para upstream antes de tentar este comando...

![image](https://user-images.githubusercontent.com/69777395/96594843-6fe1f700-12c1-11eb-9887-739c3899c6fb.png)

![image](https://user-images.githubusercontent.com/69777395/96597082-ca7c5280-12c3-11eb-9dc2-9844c8a02054.png)

**Comment by danielcanoli** [comment]
Quando vc deu o push, as atualizações foram rejeitadas porque no repositório remoto tem informações que você não tem no repositório local. No caso a sua branch e o main estão divergentes, com commits diferentes. 
Aí teria que dar o git pull antes, pra buscar o que no remoto, ajustar e aí o push, mas vi que está dando erro no pull, tenta usar "git pull --rebase"

**Comment by iareis** [comment]
Muito obrigado @danielcanoli realmente funcionou.
Eu estava com receio de utilizar o comando pela descrição dele.

![image](https://user-images.githubusercontent.com/69777395/96667427-73ac6280-132f-11eb-97fb-fad77c3cea5e.png)
