### ISSUE TITLE
O navegador não abre arquivos index.php

### ISSUE THREAD

**Issue by AndreMarthins** [iurygdeoliveira/novos_caminhos#442]
o navegador parou de abrir arquivos index.php, a única opção que aparece é para download
![Captura de tela de 2020-10-20 17-22-02](https://user-images.githubusercontent.com/70108419/96639947-d33b4b80-12f8-11eb-97ff-7dd06b0089ff.png)

**Comment by fernandoifto** [comment]
Verifica se o conteiner do PHP esta ativo.

**Comment by AndreMarthins** [comment]
O container aparecia como ligado, mas, só depois que fiz um refresh é que funcionou corretamente.
Obrigado

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 21 de out de 2020 09:53, fernandoifto escreveu:
