### ISSUE TITLE
Nota da rpova de lógica não foi corrigida

### ISSUE THREAD

**Issue by JPeeMP** [iurygdeoliveira/novos_caminhos#445]
Professor, refiz a prova porém a nota não foi corrigida.

**Comment by iurygdeoliveira** [comment]
@JPeeMP estamos com uma dificuldade técnica no google forms, mas iremos publicar uma postagem, contendo as notas corrigidas. e que serão lançadas em diário.

**Comment by JPeeMP** [comment]
Certo, muuito obrigado pelo esclarecimento, fico no aguardo.
