### ISSUE TITLE
Como resolver? ERROR: 2 matches found based on name: network novos_caminhos_default is ambiguous

### ISSUE THREAD

**Issue by santaali** [iurygdeoliveira/novos_caminhos#448]
Tentando executar o comando _docker-compose up_, eu tinha conseguido uma vez, excluir todas as imagens porque tinha dado erro e agora está dando isso.
![composeup](https://user-images.githubusercontent.com/70075977/97094117-3f36f000-1628-11eb-891c-2e3391c7a66d.PNG)

**Comment by adennyfernandesphp** [comment]
Prezado tenta esses 2 comandos:
fin system stop
docker network prune

Senão resolver. Professor Iury resolve.

**Comment by adennyfernandesphp** [comment]
Bom talvez seja uma solução: Seu docker-compose.yml, deve estar assim.
![image](https://user-images.githubusercontent.com/70215330/97123017-6d8bfc80-1708-11eb-8bf2-08e3baef4109.png)

Copia e substitui o seu código por esse, talvez vc deverá setar uma nova porta em cima do 3306
version: "3"
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=Curso-Ifes
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
    php:
        build: ./docker/php
        volumes:
            - ./www:/usr/share/nginx/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - "mysql"
        environment:
            - MYSQL_USER=root
            - MYSQL_PASS=root
    nginx:
        image: nginx:latest
        volumes:
            - ./www:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9999:80"
        depends_on:
            - "php"
volumes:
    db_data:

Abra seu terminal e execute novamente esses comandos:
Construir Container
docker-compose build

Inicia os contêineres
docker-compose up

Acho que deve dar certo!

**Comment by iurygdeoliveira** [comment]
@santaali boa tarde.

Como está o seu docker-compose.yml ?

**Comment by santaali** [comment]
https://imgur.com/W6H741W

Consegui apagando os containers, mas o nginx1 está dando esse erro.

**Comment by adennyfernandesphp** [comment]
Prezado(a) colega tente usar o comando para baixar as imagens em algum terminal de sua preferência.
Comandos:
docker image pull mysql:5.7
docker image pull nginx
docker image pull php

Contruir
Use comando
docker-compose build

Integrar e subir
Use comando
docker-compose up

Se preferir pegue todo material, abra no VS Code, use o terminal bash
delete seu container e crie com o comando
docker run -d -p 80:80 docker/getting-started

se quiser alterar o nome do container
com o docker aberto na máquina com o container rodando. Use comando para verificar a descrição dele.
docker ps
pegue o id do container 
Use comando
docker rename "id do container"  "novonome"  (Obs: retire as aspas.)

Espero que dê certo.

**Comment by santaali** [comment]
segui todas as dicas e continua :C

![image](https://user-images.githubusercontent.com/70075977/97577793-a3fa9d80-19ce-11eb-9960-5ad4e0116372.png)

**Comment by adennyfernandesphp** [comment]
Prezada colega você está usando Xampp?
Não recomendo usar Xampp. Não precisa usar Xampp.
Se vc quiser, eu posso me conectar à sua máquina e te ajudar a fazer como
eu fiz no meu.
Deixar tudo organizado pra vc.
Você está disponível?
Você tem AnyDesk instalado na sua máquina?
Se tiver trabalhando, marque um dia e horário específico. Estou disponível
qualquer hora, ok.
Estou no Telegram do Curso, me procura lá.
Atenciosamente,
Adenny Fernandes

Em qui., 29 de out. de 2020 às 10:09, Alice Alves <notifications@github.com>
escreveu:

**Comment by adennyfernandesphp** [comment]
Acho que vc não entendeu. Acho que te deixei confusa. Vendo essa imagem,
você está tentando criar tudo ao mesmo tempo. Não vai dar certo. leia com
atenção.

Em qui., 29 de out. de 2020 às 12:18, Adenny Fernandes <adennyfer@gmail.com>
escreveu:

**Comment by adennyfernandesphp** [comment]
Vou tentar te ajudar, desta vez espero que leia com atenção, faça uma coisa de cada vez, espere finalizar os processos, por favor.

Feche todo os programas do curso.
Abra somente o VS code e o Docker.
Abra o terminal no VS code, e faça o seguinte comando.

Para deletar todas as images (Pode deletar sem medo)
docker image prune --all

Depois confira se existe alguma imagem ainda com o comando
Ver as imagens (como vc deletou anteriormente as imagens terá que estar vazio) 
docker images

Agora vc vai baixar as imagens tudo novamente.
Comandos
docker pull mysql ou docker image pull mysql
docker pull nginx ou docker image pull nginx
docker pull php ou docker image pull php

Preste atenção agora, não faça ainda o docker-compose up, AINDA NÃO.
Se vc tem o MySQL instalado em seu computador. Acesse o gerenciador de tarefas, procure a guia serviços, clique em abrir serviços.
dê um stop, pare o serviço mysql que estiver em execução.

Volte para o terminal no VS code. 
execute o comando
docker-compose up

Pronto, espero que dê certo.
Vc verá uma lista de códigos, não terá fim, ele ficará parado, normal. Olhe seu docker vê se as 3 imagens, mysql, nginx e php, estão correndo, executando.
Se estiver tudo correndo no docker, pode fechar seu terminal, clicando no x, sem problema, depois só abrir um novo terminal.

OBS: não pode dois serviços correr na mesma porta, por isso terá que desativar o serviço mysql. Se abrir o Mysql WorckBench, não poderá abrir o docker e vice-versa.
Uma dica importante, connect seu MySqlWorkbench no VS Code, connect seu localhost, configure certinho. Feito isso, vc poderá trabalhar no Worckbench, salvar seu banco de dados, sincronizar com VS Code, depois recriar o container com os dados atuais.

**Comment by iurygdeoliveira** [comment]
@santaali me parece que o docker compose não consegue encontrar o arquivo de configuração do nginx, ou então existe um outro container rodando. As dicas do @adennyfernandesphp estão precisas, acho que conseguirá resolver com elas

**Comment by santaali** [comment]
![image](https://user-images.githubusercontent.com/70075977/99193348-2b7a3780-2757-11eb-8df3-567463d6a7be.png)

Ainda não solucionei... As configurações são as seguintes tem algum erro?

server {
    listen       80;
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.php index.html index.htm;
        autoindex on;
        try_files $uri $uri/ /index.php?$args;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
        root           html;
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  /usr/share/nginx/html$fastcgi_script_name;
        include        fastcgi_params;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

**Comment by adennyfernandesphp** [comment]
Prezado(a) colega.
Gostaria de fazer uma observação:
Vc está no grupo do Telegram?
É preciso estar inserido dentro do grupo, para que possamos de ajudar. Até mesmo, se possível realizar o acesso remoto, para resolver seu problema. Nossos professores são os mais indicados para te ajudar, mas ele estão trabalhando muito, existem milhares de alunos, pode demorar um pouco eles responderem sua dúvida. Nós alunos, podemos ajudar de alguma forma também, pois sua dúvida pode ser a minha e de outros alunos. É preciso vc ter uma canal de comunicação em tempo real, como WhatsApp, Telegram. Postar dúvidas aqui nas Issues do GitHub, realmente pode demorar um pouco para obter a solução. É necessário acessar sua máquina, verificar a integridade dos arquivos, e realizar os procedimentos, conforme nossos Professores nos ensinaram. Caso o contrário será difícil de ajudar. Espero que compreenda. Paz e bem.
