### ISSUE TITLE
Problemas no Docker

### ISSUE THREAD

**Issue by Daslan-Mateus** [iurygdeoliveira/novos_caminhos#451]
Meus conteiners não executam
![image](https://user-images.githubusercontent.com/70038813/97226322-91a41800-17b2-11eb-8a09-6b29adb7fcff.png)

**Comment by adennyfernandesphp** [comment]
Delete esse container. 
Abra seu terminal e execute novamente esses comandos:
OBS:

Esteja dentro da pasta local, no terminal, que possui os dados do curso .

Use esses comandos para baixar as imagens
docker image pull mysql:5.7
docker image pull nginx

Depois use esses dois comandos no seu terminal

Construir Container
docker-compose build

Iniciar e executar os contêineres
docker-compose up


Pronto, acho que deve funcionar.

**Comment by iurygdeoliveira** [comment]
@Daslan-Mateus faz o seguinte remove os containers, e faz um docker-compose up novamente. qual é o resultado, printa aqui os resultados.

**Comment by Daslan-Mateus** [comment]
![image](https://user-images.githubusercontent.com/70038813/97641459-b2be7000-1a21-11eb-80cd-6515083ec7ad.png)
continua com erro

**Comment by adennyfernandesphp** [comment]
Para subir as imagens do mysql, baixe as imagens com o comando, docker pull mysql, no bash do vs code, primeiro, Se tiver usando  MySQl Workbench no Windows, entre no gerenciador de tarefas, pare o serviço do mysql que estiver usando, senão vai dar erro na porta 3306. Depois, faça o docker-compose up, vai criar o container com as imagens, mysql, php, nginx.
![image](https://user-images.githubusercontent.com/70215330/97646438-6fb6c980-1a2e-11eb-96cf-0f2684b61657.png)

Espero ter ajudado de alguma forma. Bons estudos.

**Comment by fernandoifto** [comment]
É como o @adennyfernandesphp falou você provavelmente esta com o outro MySql ativo em sua maquina, você vai ter que parar o serviço ou desinstalar o Mysql depois de configurar no Docker ele não será mais necessario.

**Comment by iurygdeoliveira** [comment]
@Daslan-Mateus é esse o caminho, nos dê um feedback

**Comment by Daslan-Mateus** [comment]
deu certo, muito obd pela ajuda de vcs.
