### ISSUE TITLE
Problemas na publicação da página

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#453]
Ola professor @iurygdeoliveira e colegas,

estou com um problema. Criei a pasta jalexandrersilva.github.io bem como criei o repositório. Coloquei os arquivos dentro e dei um commit via add files. Então fiz uma cópia do arquivo index.php para index.html mas não consigo subir esse arquivo.

Alguem pode me ajudar?

Consegui agora subir o arquivo index.html.... mas agora não sei como resolver. Alguem pode me ajudar?

**Comment by jalexandrersilva** [comment]
Consegui resolver, mas quando clico em resume.php ele faz o download... vou continuar mexendo, valeu.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva como é os prints ?

**Comment by adennyfernandesphp** [comment]
Prezado colega. Talvez isso possa te ajudar...
Renomeia suas pastas, elas deverão ficar assim:
contact.php
index.html
resume.html
works.html

Espero que isso possa te ajudar.

**Comment by jalexandrersilva** [comment]
Funcionou, obrigado
