### ISSUE TITLE
MYSQL no docker

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#455]
Bom dia galera. Prof @iurygdeoliveira o senhor nos ensinou a trabalhar com o docker. Eu até instalei, mas o MYSQL não será instalado a partir de imagens do docker? Pode nos ensinar?

**Comment by adennyfernandesphp** [comment]
Prezado(a) colega tente usar o comando para baixar as imagens em algum terminal de sua preferência.
Comandos:
docker image pull mysql:5.7
docker image pull nginx
docker image pull php

Contruir
Use comando
docker-compose build

Integrar e subir
Use comando
docker-compose up

Se preferir pegue todo material, abra no VS Code, use o terminal bash
delete seu container e crie com o comando
docker run -d -p 80:80 docker/getting-started

se quiser alterar o nome do container
com o docker aberto na máquina com o container rodando. Use comando para verificar a descrição dele.
docker ps
pegue o id do container
Use comando
docker rename "id do container" "novonome" (Obs: retire as aspas.)

Espero que dê certo.
OBS. Acho importante que vc esteja dentro da pasta local, onde estão os arquivos, através do terminal.

Espero ter ajudado, Senão der certo, nosso Mestre Yuri, resolve.

**Comment by iurygdeoliveira** [comment]
@jalexandrersilva eu fiz a demonstração de instalação do mysql dentro do docker, está no vídeos da prova. Chegou a ver ?

**Comment by adennyfernandesphp** [comment]
Para subir as imagens do mysql, baixe as imagens com o comando, docker pull mysql, no bash do vs code, primeiro, Se tiver usando  MySQl Workbench no Windows, entre no gerenciador de tarefas, pare o serviço do mysql que estiver usando, senão vai dar erro na porta 3306. Depois, faça o docker-compose up, vai criar o container com as imagens, mysql, php, nginx.
![image](https://user-images.githubusercontent.com/70215330/97646438-6fb6c980-1a2e-11eb-96cf-0f2684b61657.png)

Espero ter ajudado de alguma forma. Bons estudos.
