### ISSUE TITLE
como otimizar pesquisa no git de projetos, programas, sites.

### ISSUE THREAD

**Issue by silvoneizaghini** [iurygdeoliveira/novos_caminhos#477]
Poderiam os professores passar dicas para otimizar as pesquisas no git de projetos, programas, sites e dicas

**Comment by iurygdeoliveira** [comment]
No git ou no github ?

**Comment by silvoneizaghini** [comment]
como não domino nenhum dos dois. Desejo saber como otimizar as pesquisas
nos dois. obrigado

Em sáb., 14 de nov. de 2020 às 12:39, Iury Gomes de Oliveira <
notifications@github.com> escreveu:
