### ISSUE TITLE
Histórico de sites acessados pelo roteador

### ISSUE THREAD

**Issue by jalexandrersilva** [iurygdeoliveira/novos_caminhos#479]
Professores e colegas, boa tarde. Sei que essa pergunta não tem nada a ver com o curso. Mas não consegui encontrar resposta.

Tenho um roteador e vários smartphones e pc conectados.

Como eu faço pra ver o histórico de sites acessados? é pelo dns? servidor proxy ou firewal?? como eu configuro com a ajuda do docker?

**Comment by fernandoarantes26** [comment]
Em rede domestica nunca procurei sobre o assunto em redes corporativas geralmente é usado um firewall PfSense com o pacote Squid para armazenar cache, acredito que possa usar o docker contudo geralmente se usa uma maquina virtualizada ou um servidor dedicado. Talvez esse curso trate de algo próximo https://www.udemy.com/course/docker-para-desenvolvedores-e-administradores-de-redes/
