### ISSUE TITLE
Como criar um repositório do terminal (git) para o Github? 

### ISSUE THREAD

**Issue by mgckaled** [iurygdeoliveira/novos_caminhos#56]
#### PRECISO DE AJUDA!

Na verdade é uma dúvida que vai além da aula... Criei uma pasta com vários arquivos e agora quer subir com eles para um repositório que ainda não existe na minha conta do Github? É possivel realizar essa ação? Grato

**segue imagem do erro da tentativa**
![Screenshot_1](https://user-images.githubusercontent.com/58960702/91358126-a838ed80-e7c8-11ea-8445-7bb362d66acc.jpg)

**Comment by iurygdeoliveira** [comment]
Parabéns, você já está utilizando as issues !

@mgckaled essa opção não é possível, primeiro você necessita criar um repositorio no github, para somente depois subir os arquivos para ele.

Mas pelo erro informado pelo git, ele esta dizendo para você realizar um git pull e depois um git push, parece que o repositorio no github já existe.

**Comment by mgckaled** [comment]
@iurygdeoliveir o problema é que não localizei este repositório na minha conta.  Enfim, vou criar um repositório no GitHub e transferir manualmente os arquivos para depois executar o `git init` e o `git clone`. Obrigado! :+1: :v:

**Comment by iurygdeoliveira** [comment]
@mgckaled o link do repositorio está aqui: https://github.com/mgckaled/novos_caminhos.

Só acessar sua conta e ela já aparece

**Comment by iurygdeoliveira** [comment]
Transferir manualmente ?!? O git serve para vc não ter este trabalho.

**Comment by mgckaled** [comment]
@iurygdeoliveira sim. Eu Confundi rsrs. na verdade é outro repositório, sobre outro outro projeto... Obrigado

**Comment by mgckaled** [comment]
@iurygdeoliveira  Compartilhando aqui minha solução:

- criei um repositório com o mesmo nome da minha pasta com os arquivos do projeto
- dentro do diretório (bash) : `git init` (reinicializar o repositório)
- `git add -A` para incluir todos no stage
- `git commit` -m "Add all files"
- `git remote add github https://github.com/<nome-usuário>/<nome-repositório>`
- e por último: `git push -f github master` 

pronto, todos os arquivos subiram!
