### ISSUE TITLE
Contribuição para o git

### ISSUE THREAD

**Issue by reisweslley** [iurygdeoliveira/novos_caminhos#64]
Curti muito o exercício sobre o Git. Um único porém foi tentar enviar o arquivo do terminal para o servidor do Git.

**Comment by iurygdeoliveira** [comment]
@reisweslley  Meu jovem é assim mesmo, iremos praticar muito isso durante o curso, e isso irá se tornar algo natural para você

**Comment by iareis** [comment]
Ainda não terminei a atividade 4 inteira, mas toda esta parte Git me rendeu muita leitura para sair de uma nó que eu mesmo criei ao fazer um **EU_FAKE** no _GitHUB_ para fazer os testes de outro desenvolvedor. No fim consegui resolver e minha árvore ficou assim, igual na série DARK, com encruzilhadas, confesso que vou precisar de mais tempo para entender bem o processo.

![image](https://user-images.githubusercontent.com/69777395/91375305-aa16a700-e7f0-11ea-92e7-841669ccdc8a.png)
