### ISSUE TITLE
Me atrapalhei ao enviar a contribuição!

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#75]
Me atrapalhei ao enviar a contribuição respondendo as 2 questões. Ao enviar, foi ao meu repositório o diretório inteiro que havia clonado antes e o meu arquivo junto. E não estou sabendo como fazer para enviar para o **novos_caminhos** (Forked from iurygdeoliveira/novos_caminhos)... como faço para que o arquivo vá onde deve ir? Parece que ao escrever a pergunta vai surgindo uma resposta óbvia. Deveo criar uma subpasta /contribuicao/ com apenas meu arquivo ocultando todo o resto e proceder com os comandos?

![image](https://user-images.githubusercontent.com/69777395/91381882-c91c3580-e7fe-11ea-9119-0ae2713792f6.png)

**Comment by mgckaled** [comment]
@iareis não sou o professor mas talvez eu possa ajudar ...

quando for executar o `git add` e queira dar `commit` e o  `push` em apenas um arquivo digite o nome do arquivo (e seu diretório) logo depois do `add`, exemplo: `git add 02 - git/ IURI ALBURQUERQUE REIS`.

**Comment by iurygdeoliveira** [comment]
Extamente @mgckaled o git add .   (com o ponto) adiciona todos os arquivos que foram modificados de uma vez só.

" ... Ao enviar, foi ao meu repositório o diretório inteiro que havia clonado antes e o meu arquivo junto .."

**Mas é exatamente isso que git faz, não está errado não.**

" ...E não estou sabendo como fazer para enviar para o novos_caminhos (Forked from iurygdeoliveira/novos_caminhos) ..."

Você fara isso através da opção pull request no repositorio forkado em sua conta do github

**Comment by iareis** [comment]
Eu tentei algo antes de ler a resposta, depois me diga se funcionou e fiz junto ou tentei uma trapaça :(. Como não sabia o que fazer após tentar muitas vezes, criei um arquivo lá no GITHUB. 
x-x-x
Entendi, mas aproveito para uma segunda pergunta quanto aos espaços  **git add 02 - git/ IURI ALBURQUERQUE REIS**, pois tentei ir no diretório escrevendo **cd 02 - git** e não deu e, agora, não lembro, mas acho que foi no vídeo mesmo o uso de barras invertidas...

**Comment by iareis** [comment]
> @iareis não sou o professor mas talvez eu possa ajudar rsrs ...
> 
> quando for executar o `git add` e queira dar `commit` e o `push` em apenas um arquivo digite o nome do arquivo (e seu diretório) logo depois do `add`, exemplo: `git add 02 - git/ IURI ALBURQUERQUE REIS`.
> 
> Creio que o comando com o ponto (`git add .`) faz o stage de todos os arquivos modificados.

Achei que havia ocultado todos no **.gitignore**

**Comment by iurygdeoliveira** [comment]
Essa questão de espaços tem muito haver com o tipo de terminal está utilizando. No bash do linux e no cmder do windows isso é tranquilo e não dá problemas, já nos outros, eu não sei te falar.

**Comment by iareis** [comment]
OK. Entendi... Hoje a tarde vou instalar o Ubuntu no VirtualBox e iniciar a jornada seguindo suas dicas quando a necessidade em conhecer o ambiente linux... E creio que reinstalarei tudo novamente...

**Comment by iurygdeoliveira** [comment]
Tranquilo, lembrando que sua máquina deve ser boa, para conseguir suportar uma maquina virtual box.
