### ISSUE TITLE
DÚVIDAS PARA A LIVE DE SÁBADO AS 20:00

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/novos_caminhos#78]

**Comment by BrotherBoris** [comment]
Eu uso o Visual Studio para programar em uns projetos pessoais mas nunca tinha ouvido falar do VS code, e eu estava pesquisando qual é a a diferença entre os dois e qual tem mais benefícios , qual a sua opinião  sobre os dois?

**Comment by ronaldocbraga** [comment]
Professor, gostaria de saber se tem algum problema se meu terminal não ter modificado pro bash ou cmd. Ele permanece no powershell.

**Comment by iurygdeoliveira** [comment]
@BrotherBoris 

Visual Studio Code é considerado um editor de texto (acredita ?), que aceita inúmeros plugins, permitindo extrema personalização. Já o Visual Studio é considerado umar IDE. Ambos podem ser usados para codificar, mas via de regra uma IDE possui mais ferramentas, e na teoria usar o Visual Studio te dará uma melhor experiencia de desenvolvedor .

Particularmente eu, nunca usei o Visual Studio, e após realizar as instalações de plugins no Visual Studio Code, me sinto
muito confortável para utilizar, e de certa forma, isso caiu no gosto popular da comunidade de desenvolvimento.

**Comment by iurygdeoliveira** [comment]
@ronaldocbraga , não há problemas, contudo, você deverá se atentar para as particularidades do power shell, na hora de executar os comandos de terminal que possamos precisar.

**Comment by ronaldocbraga** [comment]
> @ronaldocbraga , não há problemas, contudo, você deverá se atentar para as particularidades do power shell, na hora de executar os comandos de terminal que possamos precisar.

Entendi. Tem algum lugar que eu possa estar consultando esses comandos pra facilitar a utilização?

**Comment by iurygdeoliveira** [comment]
> > @ronaldocbraga , não há problemas, contudo, você deverá se atentar para as particularidades do power shell, na hora de executar os comandos de terminal que possamos precisar.
> 
> Entendi. Tem algum lugar que eu possa estar consultando esses comandos pra facilitar a utilização?

**Comment by iurygdeoliveira** [comment]
@ronaldocbraga não conheço, mas deve ter sim alguma documentação na internet

**Comment by mgckaled** [comment]
@ronaldocbraga Veja se ajuda...

Dentro do VS Code digite `Crlt + Shift + P` e dentro do campo procure por "Terminal: Select Default Shell". 

![Screenshot_2](https://user-images.githubusercontent.com/58960702/91461293-319aff00-e85f-11ea-89cc-08345e0f12cb.jpg)

Daí deve aparecer as seguintes opções: 
![Screenshot_3](https://user-images.githubusercontent.com/58960702/91461325-3cee2a80-e85f-11ea-98df-f663c62e00a3.jpg)

Escolha o Bash e depois abra o terminal (`Ctrl + '). Dentro do terminal clique em adicionar ( + ) Pronto, você verá os 2 terminais 
![Screenshot_4](https://user-images.githubusercontent.com/58960702/91461628-9c4c3a80-e85f-11ea-88f6-0a4be4015275.jpg)

**Comment by iurygdeoliveira** [comment]
@mgckaled Criar uma issue especifica para isso, aqui, é apenas dúvidas para serem tiradas na live sábado. Ou vc realmentre está postando, para que essa dúvida seja retirada no sábado ?

**Comment by iareis** [comment]
Acredito que eu precise uma nova exposição sobre a Estrutura GIT, pois embora eu tenha conseguido entender o funcionamento, alguns momento eu fico sem entender em que ponto do processo eu estou:

ORIGEM -> ORIGEM/MASTER -> MASTER -> ORIGEM

E nesta confusão posso ter utilizado os comandos inadequados que nos meus testes ocasionaram o que me pareceram loops, difíceis ainda de serem decifrados e resolvidos. 

![image](https://user-images.githubusercontent.com/69777395/91480395-4ab0a980-e879-11ea-8595-b635d5ba03a0.png)

**Comment by AriociCarlosAmorim** [comment]
Professor, não consegui de jeito nenhum utilizar a chave ssh somente a https.

**Comment by italomded** [comment]
Professor, por que não utilizar o Git Bash dentro da pasta do projeto para ensinar os usuários do Windows ao invés do cmder?

**Comment by iurygdeoliveira** [comment]
> Professor, por que não utilizar o Git Bash dentro da pasta do projeto para ensinar os usuários do Windows ao invés do cmder?

Os diferentes terminais, são de livre escolha do aluno.

O cmder é considerado uma das melhores ferramentas para substituir o cmd por possibilitar a utilização de comandos UNIX (rm, ls, mv, cd e etc.) mais utilizados pelos desenvolvedores. O cmder possui poderosos recursos de edição de linha de comando, histórico dos comandos já utilizados anteriormente e auto-complete, permitindo boa agilidade no uso do terminal.

Mas o git bash pode ser utilizado também.

**Comment by suelmartins15** [comment]
**Como atualizar seu repositório depois de fazer Fork?**

Tive que formatar meu notebook e não está atualizado conforme o do curso, preciso refazer processo de excluir repositório e clonar novamente e fazer Fork? ou como faço para atualizar arquivos no meu repositório?

**Comment by LeandroSilvaLara** [comment]
Boa tarde, professor .
tiver alguns problema com esse error 
no git : fatal: unable to access 'https://github.com/iurygdeoliveira/novos_caminhos.git/': The requested URL returned error: 403
não estava conseguindo enviar para ti o repositório
acabei fazendo manualmente.

**Comment by Aiam32** [comment]
Professor, se possível tente explicar mais sobre o funcionamento da chave SSH.
Muito obrigado.

**Comment by mgckaled** [comment]
@iurygdeoliveira, você recomendaria usar o GitHub Desktop? Poderia abordar rapidamente os prós e o contras na Live? Grato

**Comment by iurygdeoliveira** [comment]
> Boa tarde, professor .
> tiver alguns problema com esse error
> no git : fatal: unable to access 'https://github.com/iurygdeoliveira/novos_caminhos.git/': The requested URL returned error: 403
> não estava conseguindo enviar para ti o repositório
> acabei fazendo manualmente.

Esse caso, é o mesmo tratado no issue #93 . Da uma olhadinha lá

**Comment by Jean-Sawano-Si** [comment]
Ansioso por esta live....

**Comment by wesleyssantos1979** [comment]
Boa tarde, estou revendo todas as aulas, instalei uma maquina virtual no meu PC com o virtualbox pra rodar o linux, estou acompanhando as aulas e fazendo nos 2 sistemas, gostaria de saber se é possível quando for ter as linhas de comando no linux disponibilizar. E estou na dúvida pois ainda não foquei como ver as extensões do vscode, ex gifgraph como colocou ele la encima apos a instalação pra visualizar. Obrigado.

**Comment by clelianidecdasilva** [comment]
Em qual plataforma o link da live será disponibilizado? Obrigada.
