### ISSUE TITLE
Como desinstalar programas no linux ?

### ISSUE THREAD

**Issue by reginaldoasousa** [iurygdeoliveira/novos_caminhos#83]
Olá

Iniciei o curso com um notebook que utilizo para trabalho. Depois das explicações, instalei o ubuntu 20.04 LTS em outra máquina e fiz novamente todo o procedimento no Linux.

Como nunca tinha visto o sistema operacional, estou tendo algumas dificuldades, mas estou gostando muito.

Minha dúvida é: 
- Como excluir tudo o que foi feito em relação às aulas (instalação, configurações... ) e fazer tudo novamente? Gostaria de refazer para praticar os comandos.

@iurygdeoliveira

**Comment by iurygdeoliveira** [comment]
No linux para desintalarmos programas pode ser:

sudo dpkg -r <nome do programa>

sudo apt-get remove --purge <nome do programa>

Para desinstalar o vscode, utilize o a palavra code em nome do programa
Para desinstalar o git, utilize a palavra git
