### ISSUE TITLE
MINHA CONTRIBUIÇÃO FOI DELETADA/SOBRESCRITA

### ISSUE THREAD

**Issue by jolopesqueiroz** [iurygdeoliveira/novos_caminhos#85]
minha contribuição arquivo "02 - git/contribuicao/JO LOPES QUEIROZ" foi deletada/sobrescrita e
não esta aparecendo na pasta de contribuições,
tenho que enviar de novo?

**Comment by iareis** [comment]
No erro que descrevi, o seu arquivo foi um dos que enviei por engano para o meu repositório, seria esta a questão?

**Comment by iareis** [comment]
Estes foram os nomes que estavam na minha máquina e enviei achando que estava enviando o meu!!! Se eu fui o responsável pelo seu, o mesmo deve ter ocorrido com estes outros!!!

![image](https://user-images.githubusercontent.com/69777395/91449780-e9291480-e851-11ea-845c-a60b5d1cef35.png)

**Comment by iareis** [comment]
> Estes foram os nomes que estavam na minha máquina e enviei achando que estava enviando o meu!!! Se eu fui o responsável pelo seu, o mesmo deve ter ocorrido com estes outros!!!
> 
> ![image](https://user-images.githubusercontent.com/69777395/91449780-e9291480-e851-11ea-845c-a60b5d1cef35.png)

**Confirmado**. Fui o responsável. Estes nomes não estão nas contribuições. Professor, como faço para mandar eles de volta? Estão no meu repositório...

**Comment by jolopesqueiroz** [comment]
minha contribuição já foi confirmada mais depois desapareceu do "https://github.com/iurygdeoliveira/novos_caminhos/tree/master/02%20-%20git/contribuicao" acho que você pode restaurar ela, pois a vi no git graph

confirmação no google classroom:

Iury Gomes de Oliveira 24 de ago.
Confirmado

**Comment by RafaelBuzzo** [comment]
Bom dia!
Muito interessante, também estou com esta dúvida, pois fiz um clone agora da pasta e meu nome nao aparece (RAFAEL NOSCHANG BUZZO), mas na imagem que o Iares colocou consegui ver meu arquivo.

**Comment by iareis** [comment]
> minha contribuição já foi confirmada mais depois desapareceu do "https://github.com/iurygdeoliveira/novos_caminhos/tree/master/02%20-%20git/contribuicao" acho que o professor pode restaurar ela, pois a vi no git graph
> 
> confirmação no google classroom:
> 
> Iury Gomes de Oliveira 24 de ago.
> Confirmado

Acredito que ele não possa mais, pois no vídeo da Atividade 5, ele atualizou tudo!!! Acho que eu tenho que conseguir passar do meu repositório, para a pasta contribuições,,, todos os arquivos da imagem que enviei, só não sei como?

**Comment by jolopesqueiroz** [comment]
professor 

O Merge pull request #28 from tsartori/master "https://github.com/iurygdeoliveira/novos_caminhos/pull/28/files" removeu 2 CONTRIBUICOES

O Merge pull request #44 from gabibaudi/master "https://github.com/iurygdeoliveira/novos_caminhos/pull/44/files" removeu 9 CONTRIBUICOES, inclusive a minha "JO LOPES QUEIROZ"

**Comment by iurygdeoliveira** [comment]
> minha contribuição arquivo "02 - git/contribuicao/JO LOPES QUEIROZ" foi deletada/sobrescrita e
> não esta aparecendo na pasta de contribuições,
> tenho que enviar de novo?

No git/github é assim, um pode sobrescrever o código do outro, aqui é apenas um exemplo didático, não precisa se preocupar

**Comment by iurygdeoliveira** [comment]
> Bom dia!
> Muito interessante, também estou com esta dúvida, pois fiz um clone agora da pasta e meu nome nao aparece (RAFAEL NOSCHANG BUZZO), mas na imagem que o Iares colocou consegui ver meu arquivo.

Pessoal, eu sobrescrevi os arquivos, simulando uma alteração

**Comment by iurygdeoliveira** [comment]
> professor
> 
> O Merge pull request #28 from tsartori/master "https://github.com/iurygdeoliveira/novos_caminhos/pull/28/files" removeu 2 CONTRIBUICOES
> 
> O Merge pull request #44 from gabibaudi/master "https://github.com/iurygdeoliveira/novos_caminhos/pull/44/files" removeu 9 CONTRIBUICOES, inclusive a minha "JO LOPES QUEIROZ"

Isso mesmo, aqui é um exemplo didático do mundo real.
Lembrem-se as notas serão avaliadas pelo trabalho prático ao final da disciplina.
