### ISSUE TITLE
Atividade 5 - Uso de Ferramentas

### ISSUE THREAD

**Issue by maarcusf** [iurygdeoliveira/novos_caminhos#86]
Não tenho dúvidas sobre. Estou postando apenas para  adicionar o trabalho da atividade 5.

Hoje utilizo o PhpStorm para programar em PHP onde eu trabalho. É uma IDE bem completa, muito boa e fácil de utilizar.
Utilizo o VSCode para programar em JavaScript, utilizando NodeJs, é bem bacana. A única questão é a instalação dos plugins, mas é super tranquilo. Abraços. 

Parabéns pela didática de utilizar o Git, é uma ferramenta de extrema importância para o meio profissional e até para estudos. Hoje creio que quase 100% das empresas utilizam o GIT para controle de versionamento, é uma prática muito boa, ficando bem acima do SVN. 

Utilizo o Git desde a faculdade, e me ajudou muito a ter um repositório de meus projetos da faculdade, onde não me preocupava muito em ter que salvar arquivo em pen-drive ou em pasta na nuvem. Fazia a atividade na faculdade enviava pro Git, chegava em casa fazia um "pull" e continuava a atividade e assim por diante.

**Comment by iurygdeoliveira** [comment]
@maarcusf Que maravilha !

Vou seguir você, vamos aumentar o network, quem sabe algum dia, trabalhamos em conjunto em um projeto.

Abraços !
