### ISSUE TITLE
Posso deletar algum arquivo dentro da pasta .git ?

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#89]
Estou com alguns erros indicando deletar um arquivo. Tentei usar **git rm** mas não consegui. Qual comando devo utilizar?

![image](https://user-images.githubusercontent.com/69777395/91459911-981f1d80-e85d-11ea-8813-b0eceba420e7.png)

![image](https://user-images.githubusercontent.com/69777395/91460181-e59b8a80-e85d-11ea-84eb-539bac63a418.png)

![image](https://user-images.githubusercontent.com/69777395/91460344-15e32900-e85e-11ea-8ab3-248e10678649.png)

**Comment by iareis** [comment]
Estou preso num **loop**.  E não consegui identificar onde está o Branch que acusa no status.

![image](https://user-images.githubusercontent.com/69777395/91470947-bf7ce700-e86b-11ea-9048-e53abd5d2490.png)

**Comment by iareis** [comment]
DESCOBRI.
**rm -f .git/index.lock**

OU 

**rm -f index.lock** se já estiver na GIT_DIR

**Comment by zander-br** [comment]
@iareis , apenas um conselho eu procuraria não mexer muito no diretório **.git** pois isso poderia estar causando algum problema no seu repositório e até mesmo corrompendo tudo... Acho que vale mais como uma dica.

**Comment by iareis** [comment]
Mas quem criou o arquivo index.lock? O que eu deveria ter feito?
Foi só retirar ele e voltei a conseguir utilizar os comandos.

**Comment by iurygdeoliveira** [comment]
@iareis tudo bem !

O colega @zander-br está correto, não se mexe dentro da pasta .git, ele é controlada de forma automática pelo próprio git.
Não precisamos nos preocupar com o que acontece dentro dela, apenas nos assegurar que ela não será deletada, de resto, o próprio git toma de conta, e quando necessitar fazer alguma configuração no seu git, utilize o comando **git config**

Mas fica tranquilo, que bom que está malinando, é assim que se descobre e aprende as coisas.
