### ISSUE TITLE
Branch origin/master desatualizada, como atualizar  ?

### ISSUE THREAD

**Issue by iareis** [iurygdeoliveira/novos_caminhos#92]
_Mensagem: Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded._

Quando realizei a atividade 4 achei ter entendido a totalidade dos conceitos da **Estrutura de Funcionamento GIT**, porém a cada exercício que me proponho, crio uma série de dificuldades que fazem eu me perder de onde realmente está o meu problema?

Já estava perdido, mas no meu raciocínio, eu teria que estar na origem e esses foram meus passos seguintes foram:

**git status**
On branch master
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    02 - git/CONTRIBUIR/IURI ALBUQUERQUE REIS

no changes added to commit (use "git add" and/or "git commit -a")

**git checkout HEAD**
D       02 - git/CONTRIBUIR/IURI ALBUQUERQUE REIS
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

**git pull origen**
fatal: 'origen' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.

**git restore 02 - git/CONTRIBUIR/IURI ALBUQUERQUE REIS**
error: pathspec '02' did not match any file(s) known to git
error: pathspec '-' did not match any file(s) known to git
error: pathspec 'git/CONTRIBUIR/IURI' did not match any file(s) known to git
error: pathspec 'ALBUQUERQUE' did not match any file(s) known to git
error: pathspec 'REIS' did not match any file(s) known to git

**git pull origin**
Updating 2ed95ce..afe26df
Fast-forward
 02 - git/CONTRIBUIR/IURI ALBUQUERQUE REIS | 7 -------
 1 file changed, 7 deletions(-)
 delete mode 100644 02 - git/CONTRIBUIR/IURI ALBUQUERQUE REIS

**git status**
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

![image](https://user-images.githubusercontent.com/69777395/91479999-b0506600-e878-11ea-9828-2b4a48e7d4e8.png

O PROCEDIMENTO E O RACIOCÍNIO FORAM CORRETOS?

**Comment by iurygdeoliveira** [comment]
@iareis Blz cara !

Olha só, todos esses comandos que digitou na sequência não irão funcionar.

Ao dar o comando git status, o próprio git está informando que sua branch local origin/master está atrasado em 1 commit.

E que para atualizar, você deve dar comando **git pull**.

Dê o comando git status, se aparecer a mesma mensagem, dê o comango git pull, e veja se resolveu.
