### ISSUE TITLE
Como Contribuir nos Projetos ?

### ISSUE THREAD

**Issue by RicardoLMattos** [iurygdeoliveira/novos_caminhos#93]
Não estou conseguindo enviar a contribuição, quando chega na parte em que executa o comando git push, dá erro e não sei mais o que fazer.

![image](https://user-images.githubusercontent.com/69875676/91482710-e09a0380-e87c-11ea-8740-dc9401f520b2.png)

**Comment by zander-br** [comment]
Olá Ricardo, o erro que está dando está relacionando a permissão pois pelo que eu entendi você está tentando fazer um `git push` no repositório do professor e se não me engano você precisa fazer no seu e mandar um **Pull requests** para o repositório dele, mais acredito que em breve o professor irá auxiliar melhor nessa questão.

Mais de qualquer forma fica minha contribuição. ☺️

**Comment by RicardoLMattos** [comment]
Valeu Anderson! obrigado pela sua contribuição, depois eu vejo isso

**Comment by theteustav** [comment]
@RicardoLMattos, copie o link do Clone with HTTPS do GitHub, depois entre no terminal do VS Code e faça a seguinte sequencia de comandos:

git clone (cole o link copiado)

(Faça sua contribuição no código)

git status  (para ver se sua contribuição aparece em vermelho)
git add .
git commit -m "Contribuição"
git push

Muitos de nós tivemos este mesmo erro e conseguimos resolver fazendo esse procedimento acima citado.
Espero que eu tenha ajudado.

**Comment by iurygdeoliveira** [comment]
@RicardoLMattos os colegas @theteustav e @zander-br estão certos.

Com as dicas deles conseguiu resolver ?  Você está tentando contribuir diretamente no meu projeto original. 
Primeiro faça uma contribuição no seu projeto "forkado" e depois faça um pull requeste para o meu projeto original.

Me diga depois se conseguiu resolver, blz ?

**Comment by AnaCavalcante** [comment]
Boa tarde professor! Gostaria de saber se o sr recebeu a minha contribuição: Ana_Lidia_Queiroz_Cavalcante.

Preciso da sua confirmação para saber se deu certo. Porque me deu muito trabalho (rsrsr), pois o que sr fez no vídeo já foi direto do seu repositório local e assim o sr não mostrou como era feito o git clone. Ai bati a cabeça pra saber de onde tinha que fazer os comandos rsrsr...mas espero ter dado certo.

**Comment by iurygdeoliveira** [comment]
@AnaCavalcante Recebi sim

**Comment by RicardoLMattos** [comment]
> @RicardoLMattos os colegas @theteustav e @zander-br estão certos.
> 
> Com as dicas deles conseguiu resolver ? Você está tentando contribuir diretamente no meu projeto original.
> Primeiro faça uma contribuição no seu projeto "forkado" e depois faça um pull requeste para o meu projeto original.
> 
> Me diga depois se conseguiu resolver, blz ?

Será que agora foi professor?

![image](https://user-images.githubusercontent.com/69875676/91619519-a192ad80-e963-11ea-9c12-b80c05386f50.png)

**Comment by iurygdeoliveira** [comment]
Sim, mas está dando conflito com as atualizações do meu repositorio, mas fique tranquilo, isso eu resolvo por aqui
