### ISSUE TITLE
Como atualizar o repositório clonado (forkado), depois que o repositório original recebeu novas atualizações ?

### ISSUE THREAD

**Issue by theteustav** [iurygdeoliveira/novos_caminhos#97]
Entendo que no VS Code fazemos o GIT PUSH para subir as nossas atualizações/contribuições para o nosso repositório clonado, e em seguida, fazemos o PULL REQUEST para que as nossas atualizações/contribuições sejam implementadas no repositório original.

Minha dúvida é: **Qual é a boa prática de atualização do repositório clonado às atualizações ocorrentes no repositório original?**

Se é deletando o repositório clonado e dando um "FORK " novamente, ou se há um procedimento mais prático para isso.

**Comment by tsartori** [comment]
Estou com a mesma duvida, pois ao realizar um git pull me retorna "Already up to date". E os novos arquivos que o @iurygdeoliveira deu merge no projeto principal não são acrescentados.
![image](https://user-images.githubusercontent.com/21146217/91508545-2de29900-e8ae-11ea-9688-34988c572479.png)

**Comment by mizaelc** [comment]
## Oi! Tentarei responder.
Procurei e testei os comando e cheguei a seguinte conclusão:
Vamos imaginar os repositórios que estamos a mexer e dar nomes a eles:
1. _NCiury_ = Repositório "novos_caminhos" - Que é do prof. Iury.
2. _NCgit_ = Repositório "novos_caminhos"( **fork** ) - Que está na sua conta GITHUB (**remoto**).
3. _NCpc_ = Repositório "novos_caminhos"( **fork** ) - Que está no seu COMPUTADOR (**local**).

### Comandos
Primeiro vamos aos comandos para atualizar o _NCgit_.
Para o ato, temos que ter o link do _NCiury_. Aqui você vai pegar o link do jeito que usa, https ou ssh.
Com o link copiado vamos aos comandos:

Ira atualizar o repositório _NCpc_ - `git pull Link_do_NCiuty`

Pronto com este comando você vai pegar as coisas novas do repositório do _NCiury_ e colocar no _NCpc_.
Depois, você ira fazer o `push` do seu repositório _NCpc_, que agora está atualizada, e manda para o _NCgit_.
Para isto usamos os comando a seguir.

```
git add .
git commit -m "atualizando repositório NCgit"
git push
```

Agora você acabou de atualizar o _NCgit_, seu repositório remoto. 👍 
Não esqueça de está dentro da pasta ao executar os comandos.

> OBS.:
> Esta foi a maneira que achei para atualizar repositório.
> Espero que tenha ajudado!    ✌️

**Comment by mgckaled** [comment]
@mizaelc funcionou perfeitamente. Boa!

**Comment by daniellamlima** [comment]
Também segui esses comandos @mizaelc e aqui funcionou!!

**Comment by theteustav** [comment]
Aqui deu certo. Obrigado @mizaelc

**Comment by iurygdeoliveira** [comment]
Para complementar, dar uma olhadinha na issue #155

**Comment by UMJS** [comment]
Deu certo **@mizaelc** 👍 , fiquei tão emocionado que eu seguir você aqui no GuitHub. Você tem minha palavra que eu não brigo se você seguir de volta!
